# Поиск услуг: кандидатогенерация

До 50 объявлений на запрос. Основная метрика — macro Recall@50.

## 1. Настройки

In [1]:
from pathlib import Path
import gc
import hashlib
import json
import os
import importlib.metadata
import platform
import random
import shutil
import subprocess
from time import perf_counter

import bm25s
import torch
from sklearn.model_selection import train_test_split
from scipy.stats import bootstrap
from scipy.sparse import csr_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from sparse_dot_topn import sp_matmul_topn

import numpy as np
import pandas as pd
import psutil
import pyarrow.parquet as pq
from IPython.display import display

DATA_DIR = Path("dataset")
SEED = 42
DEVICE_REQUEST = os.environ.get("AVITO_DEVICE", "auto").lower()
VALIDATION_SIZE = 0.2
SPLIT_PATH = Path("split.csv")
EXPERIMENTS_PATH = Path("experiments.csv")
BM25_CONFIG = {"k1": 1.2, "b": 0.75, "method": "lucene", "backend": "numpy"}
TOKEN_PATTERN = r"(?u)\b\w+\b"
RECALL_K = (1, 5, 10, 20, 50)
E1_VARIANTS = {
    "E1_title": {"title": 1.0, "description": 0.0},
    "E1_description": {"title": 0.0, "description": 1.0},
    "E1_title1_description1": {"title": 1.0, "description": 1.0},
    "E1_title2_description1": {"title": 2.0, "description": 1.0},
    "E1_title4_description1": {"title": 4.0, "description": 1.0},
}
TFIDF_VARIANTS = {
    "E2_word": {"analyzer": "word", "ngram_range": (1, 2), "token_pattern": TOKEN_PATTERN,
                "min_df": 2, "max_features": 300_000},
    "E2_char": {"analyzer": "char_wb", "ngram_range": (3, 5),
                "min_df": 2, "max_features": 200_000},
}
TFIDF_COMMON = {"lowercase": False, "norm": "l2", "sublinear_tf": True,
                "smooth_idf": True, "dtype": np.float32}
TFIDF_BATCH_SIZE = 256
TFIDF_THREADS = min(8, os.cpu_count() or 1)
E2_CONFIDENCE = 1 - 0.05 / len(TFIDF_VARIANTS)
BOOTSTRAP_RESAMPLES = 2000
BOOTSTRAP_CONFIDENCE = 1 - 0.05 / len(E1_VARIANTS)
random.seed(SEED)
np.random.seed(SEED)
pd.set_option("display.max_colwidth", 100)
RRF_VARIANTS = {
    "E4_n100_c60": {"depth": 100, "c": 60},
    "E4_n200_c60": {"depth": 200, "c": 60},
    "E4_n200_c20": {"depth": 200, "c": 20},
}
E4_CONFIDENCE = 1 - 0.05 / len(RRF_VARIANTS)
NEAR_COPY_SAMPLE = 500
NEAR_COPY_THRESHOLD = 0.95

HARRIER_MODELS = {
    "H270": {"model": "microsoft/harrier-oss-v1-270m", "revision": "31de22b673913c7d658c0f03f792d77c2dcf8ebd", "dimension": 640},
}
HARRIER_COMMON = {
    "max_length": 512, "batch_size": 16, "search_batch_size": 64,
    "dtype": "float32", "pooling": "lasttoken", "normalize_embeddings": True,
    "query_prefix": "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery: ",
    "document_prefix": "", "similarity": "cosine", "search": "exact matrix multiplication",
    "document_text": "raw title + newline + raw description",
    "query_text": "lexicographically first raw text per normalized text",
    "tie_break": "item_id ascending",
}
# Сохраняем порог первоначального протокола после исключения 0.6B.
HARRIER_CONFIDENCE = 0.975

/home/alexiva05/projects/pythonProjects/avito/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def select_device(requested: str) -> torch.device:
    if requested not in {"auto", "cpu", "cuda", "mps"}:
        raise ValueError("AVITO_DEVICE: auto, cpu, cuda или mps")
    if requested == "auto":
        requested = ("cuda" if torch.cuda.is_available() else
                     "mps" if torch.backends.mps.is_available() else "cpu")
    if requested == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA недоступна: проверьте GPU, драйвер и сборку PyTorch")
    if requested == "mps" and not torch.backends.mps.is_available():
        raise RuntimeError("MPS недоступен: требуется совместимый Mac и сборка PyTorch")
    return torch.device(requested)


def check_device(device: torch.device) -> None:
    # Проверяем вычисления и градиенты, а не только наличие устройства.
    x = torch.arange(12, dtype=torch.float32).reshape(3, 4).to(device)
    x.requires_grad_(True)
    loss = (x @ x.T).sum()
    loss.backward()
    expected_gradient = 2 * torch.arange(12, dtype=torch.float32).reshape(3, 4).sum(0)
    torch.testing.assert_close(x.grad.cpu(), expected_gradient.expand(3, 4))
    torch.testing.assert_close(loss.detach().cpu(), torch.tensor(1134.0))


DEVICE = select_device(DEVICE_REQUEST)
torch.manual_seed(SEED)
if DEVICE.type == "cuda":
    torch.cuda.manual_seed_all(SEED)
    torch.backends.cudnn.benchmark = False
elif DEVICE.type == "mps":
    torch.mps.manual_seed(SEED)
check_device(DEVICE)
print(f"PyTorch {torch.__version__}; устройство: {DEVICE}; вычисления и градиенты: OK")

PyTorch 2.14.0+cu130; устройство: cuda; вычисления и градиенты: OK

## 2. Данные

In [3]:
QUERY_FIELDS = [
    "search_query", "search_location_id", "search_is_delivery_search",
    "search_infm_params_text", "search_category",
]


def normalize_text(values: pd.Series) -> pd.Series:
    """Нижний регистр и нормализация пробелов."""
    return values.fillna("").str.lower().str.replace(r"\s+", " ", regex=True).str.strip()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def resources(root: Path) -> dict:
    try:
        gpu = subprocess.run(
            ["nvidia-smi", "--query-gpu=name,memory.total,driver_version", "--format=csv,noheader"],
            capture_output=True, text=True, check=True, timeout=10,
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        gpu = "unavailable"
    return {
        "python": platform.python_version(), "platform": platform.platform(),
        "cpu_physical": psutil.cpu_count(logical=False), "cpu_logical": psutil.cpu_count(),
        "ram_total_bytes": psutil.virtual_memory().total,
        "ram_available_bytes": psutil.virtual_memory().available,
        "disk_free_bytes": shutil.disk_usage(root).free, "gpu": gpu,
        "versions": {name: importlib.metadata.version(name) for name in
                     ["pandas", "numpy", "pyarrow", "nbformat", "nbclient", "psutil", "bm25s", "scikit-learn", "torch"]},
    }

In [4]:
def audit_data(data_dir: Path) -> dict:
    tables, files, columns, examples = {}, [], [], {}
    for name in ["benchmark_items", "benchmark_queries", "train"]:
        path = data_dir / f"{name}.parquet"
        frame = pd.read_parquet(path)
        tables[name] = frame
        files.append({"file": path.name, "bytes": path.stat().st_size,
                      "rows": len(frame), "columns": len(frame.columns), "sha256": sha256(path)})
        schema = pq.read_schema(path)
        for column in frame:
            values = frame[column]
            columns.append({"table": name, "column": column, "type": str(schema.field(column).type),
                            "nulls": int(values.isna().sum()), "unique": int(values.nunique()),
                            "empty_strings": int(values.eq("").sum())})
        examples[name] = frame.head(3).map(
            lambda x: str(x)[:240] if pd.notna(x) else None)

    items, queries, train = (tables[n] for n in ["benchmark_items", "benchmark_queries", "train"])
    for frame, key, pattern in [(items, "item_id", r"[0-9a-f]{16}"),
                                (train, "item_id", r"[0-9a-f]{16}"),
                                (queries, "query_id", r".{16}")]:
        if not frame[key].str.fullmatch(pattern).fillna(False).all():
            raise ValueError(f"Invalid {key}")
    if not items.item_id.is_unique or not queries.query_id.is_unique:
        raise ValueError("Duplicate benchmark IDs require an explicit resolution")

    # В train нет query_id; группируем по тексту и контексту.
    identity = train[QUERY_FIELDS].copy()
    identity["search_query"] = normalize_text(identity.search_query)
    group_ids = identity.groupby(QUERY_FIELDS, dropna=False, sort=True).ngroup()
    pairs = pd.DataFrame({"group": group_ids, "item_id": train.item_id}).drop_duplicates()
    pairs["in_corpus"] = pairs.item_id.isin(items.item_id)
    positives = pairs.groupby("group").agg(positives=("item_id", "size"), in_corpus=("in_corpus", "sum"))
    contexts = identity.drop_duplicates().groupby("search_query", dropna=False).size()
    item_text = pd.DataFrame({field: normalize_text(items[field]) for field in
                              ["item_title_raw", "item_description_raw"]})
    title_counts = item_text.groupby("item_title_raw").size()
    summary = {
        "train_rows": len(train), "corpus_items": len(items), "benchmark_queries": len(queries),
        "train_has_query_id": "query_id" in train, "train_has_explicit_label": False,
        "label_assumption": "Each train row is a positive interaction; no explicit label is provided.",
        "query_context_groups": len(positives),
        "normalized_train_texts": int(identity.search_query.nunique()),
        "texts_with_multiple_contexts": int(contexts.gt(1).sum()),
        "duplicate_positive_rows_after_normalization": len(train) - len(pairs),
        "unique_positive_pairs": len(pairs),
        "positive_pairs_outside_corpus": int((~pairs.in_corpus).sum()),
        "unique_positive_items_outside_corpus": int(pairs.loc[~pairs.in_corpus, "item_id"].nunique()),
        "groups_without_retrievable_positive": int(positives.in_corpus.eq(0).sum()),
        "positive_count_distribution": positives.positives.describe(percentiles=[.5, .9, .99]).to_dict(),
        "macro_recall_corpus_ceiling": float((positives.in_corpus / positives.positives).mean()),
        "empty_train_query_rows": int(identity.search_query.eq("").sum()),
        "empty_benchmark_query_rows": int(normalize_text(queries.search_query).eq("").sum()),
        "benchmark_repeated_text_rows": int(normalize_text(queries.search_query).duplicated().sum()),
        "duplicate_item_text_rows": int(item_text.duplicated().sum()),
        "repeated_title_groups": int(title_counts.gt(1).sum()),
        "near_duplicate_status": "Not measured; repeated titles alone do not prove near duplication.",
        "event_time_columns": [c for c in train if any(t in c.lower() for t in ["timestamp", "date", "event_time"])],
        "dense_float32_384_bytes": len(items) * 384 * 4,
        "dense_float32_768_bytes": len(items) * 768 * 4,
    }
    return {
        "summary": summary, "files": pd.DataFrame(files),
        "columns": pd.DataFrame(columns), "examples": examples,
        "resources": resources(data_dir.parent),
    }

In [5]:
audit = audit_data(DATA_DIR)
summary = audit["summary"]
files = audit["files"]
files["Размер, МиБ"] = (files["bytes"] / 2**20).round(2)
display(files[["file", "rows", "columns", "Размер, МиБ"]].rename(
    columns={"file": "Файл", "rows": "Строки", "columns": "Поля"}))
display(files[["file", "sha256"]])

                        Файл  Строки  Поля  Размер, МиБ
0    benchmark_items.parquet  189212    14       186.61
1  benchmark_queries.parquet    2452     6         0.12
2              train.parquet  497673    19       467.53

,file,sha256
0,benchmark_items.parquet,193b3a3961464620cbf8d8797152b7f90cae1826ca749fb7817a210984a09899
1,benchmark_queries.parquet,e49de4fb76f03979a4af96034817767d39ae5de9f94e254fed028243188dda06
2,train.parquet,e150ab7a5c98769f643b95ee3a02dc0f664b647facd69a7d280ec6d48ca554a7

`benchmark_items` — корпус объявлений, `benchmark_queries` — итоговые запросы,
`train` — пары запрос–объявление.

In [6]:
columns = audit["columns"]
column_names = {"column": "Поле", "type": "Тип Parquet", "nulls": "Пропуски",
                "unique": "Уникальные значения", "empty_strings": "Пустые строки"}
for table in files["file"].str.removesuffix(".parquet"):
    print(table)
    display(columns.loc[columns["table"].eq(table)].drop(columns="table").rename(columns=column_names))

benchmark_items

,Поле,Тип Parquet,Пропуски,Уникальные значения,Пустые строки
0,item_title_raw,string,0,119952,0
1,item_rating_reviews_count,double,11615,1170,0
2,item_rating,double,17631,6007,0
3,item_price,"decimal128(27, 15)",0,2949,0
4,item_microcat_id,int64,0,752,0
5,item_longitude,"decimal128(18, 15)",1,120004,0
6,item_location_id,int64,0,2877,0
7,item_latitude,"decimal128(17, 15)",1,119778,0
8,item_is_phone_hidden,bool,0,2,0
9,item_is_message_forbidden,bool,0,2,0
10,item_infm_params_text,string,0,187397,0
11,item_id,string,0,189212,0
12,item_description_raw,string,35,168134,0
13,item_category_id,int64,0,47,0

benchmark_queries

,Поле,Тип Parquet,Пропуски,Уникальные значения,Пустые строки
14,query_id,large_string,0,2452,0
15,search_query,large_string,0,2452,0
16,search_location_id,int64,0,273,0
17,search_is_delivery_search,int32,0,1,0
18,search_infm_params_text,large_string,0,132,1546
19,search_category,int64,0,2,0

train

,Поле,Тип Parquet,Пропуски,Уникальные значения,Пустые строки
20,search_query,string,0,74529,0
21,search_location_id,int64,0,2782,0
22,search_is_delivery_search,int32,0,2,0
23,search_infm_params_text,string,0,3724,163999
24,search_category,int64,0,4,0
25,item_title_raw,string,0,210029,0
26,item_rating_reviews_count,double,19211,1372,0
27,item_rating,double,28232,8832,0
28,item_price,"decimal128(27, 15)",0,2992,0
29,item_microcat_id,int64,0,212,0
30,item_longitude,"decimal128(18, 15)",4,228567,0
31,item_location_id,int64,0,2637,0
32,item_latitude,"decimal128(17, 15)",4,227858,0
33,item_is_phone_hidden,bool,0,2,0
34,item_is_message_forbidden,bool,0,2,0
35,item_infm_params_text,string,0,343205,0
36,item_id,string,0,344825,0
37,item_description_raw,string,0,327348,0
38,item_category_id,int64,0,8,0

### Примеры

Для отображения обрезаем значения до 240 символов.

In [7]:
for table, title in [("benchmark_queries", "Итоговый запрос"),
                     ("benchmark_items", "Объявление из корпуса"),
                     ("train", "Строка обучающей разметки")]:
    examples = audit["examples"][table]
    print(title)
    display(examples.iloc[0].rename("Пример значения").to_frame())

Итоговый запрос

                                         Пример значения
query_id                                70DfDUpwjxB4lzFd
search_query               перевозки владикавказ тбилиси
search_location_id                                649820
search_is_delivery_search                              0
search_infm_params_text
search_category                                      114

Объявление из корпуса

                                                                                                               Пример значения
item_title_raw                                                              Ремонт/выкуп компьют. и ноутбуков с выездом на дом
item_rating_reviews_count                                                                                                 57.0
item_rating                                                                                                                5.0
item_price                                                                                                 500.000000000000000
item_microcat_id                                                                                                       2097573
item_longitude                                                                                              42.047193961004901
item_location_id                                                                                                        631060
item_latitude                                                                                               44.228180450924000
item_is_phone_hidden                                                                                                     False
item_is_message_forbidden                                                                                                False
item_infm_params_text      Вид услуги Компьютерная помощь Место оказания услуг пр-т Ленина Тип стоимости за услугу Начальна...
item_id                                                                                                       111eb8b979577d79
item_description_raw       Выезд на дом в любое время, вплоть до 23:00\n\n● Диагностика устройств;\n\n● Чистка от пыли и за...
item_category_id                                                                                                           114

Строка обучающей разметки

                                                                                                               Пример значения
search_query                                                                                                скупка телевизоров
search_location_id                                                                                                      652430
search_is_delivery_search                                                                                                    0
search_infm_params_text
search_category                                                                                                            114
item_title_raw                                                                                              Скупка б/у техники
item_rating_reviews_count                                                                                                 91.0
item_rating                                                                                                  4.989010989010989
item_price                                                                                                   1.000000000000000
item_microcat_id                                                                                                       2303374
item_longitude                                                                                              39.712818145751953
item_location_id                                                                                                        652430
item_latitude                                                                                               54.629230499267578
item_is_phone_hidden                                                                                                      True
item_is_message_forbidden                                                                                                False
item_infm_params_text      Вид услуги Место оказания услуг Первомайский пр-т, 66 Тип стоимости за услугу Работаете с юрлица...
item_id                                                                                                       e8b685dffe1a408e
item_description_raw       Скупаю практически любую современную новую и б/у технику(обязательно рабочую), до 80% от рыночно...
item_category_id                                                                                                           114

В train нет `query_id`, явной метки релевантности и времени событий.
Каждую строку считаем позитивным взаимодействием.
Для BM25 используем заголовок и описание.

## 3. Запросы и повторы

Запрос определяем сочетанием пяти `search_*` полей. В тексте приводим буквы к нижнему
регистру и нормализуем пробелы. Одинаковый текст с разными фильтрами — разные запросы
для метрики, но одна группа для split.

In [8]:
query_counts = {
    "Строки train": summary["train_rows"],
    "Различные нормализованные тексты": summary["normalized_train_texts"],
    "Запросы с учётом контекста": summary["query_context_groups"],
    "Тексты с несколькими контекстами": summary["texts_with_multiple_contexts"],
    "Повторные позитивные пары": summary["duplicate_positive_rows_after_normalization"],
    "Уникальные позитивные пары": summary["unique_positive_pairs"],
}
display(pd.Series(query_counts, name="Количество").to_frame())
distribution = summary["positive_count_distribution"]
display(pd.Series({"Минимум": distribution["min"], "Медиана": distribution["50%"],
                   "90-й перцентиль": distribution["90%"], "99-й перцентиль": distribution["99%"],
                   "Максимум": distribution["max"], "Среднее": distribution["mean"]},
                  name="Позитивов на запрос с контекстом").to_frame().round(2))

                                  Количество
Строки train                          497673
Различные нормализованные тексты       73904
Запросы с учётом контекста            354313
Тексты с несколькими контекстами       27894
Повторные позитивные пары              30644
Уникальные позитивные пары            467029

                 Позитивов на запрос с контекстом
Минимум                                      1.00
Медиана                                      1.00
90-й перцентиль                              2.00
99-й перцентиль                              6.00
Максимум                                   278.00
Среднее                                      1.32

У большинства запросов один позитив, у некоторых — сотни.
Повторные пары запрос–объявление учитываем один раз.

## 4. Покрытие позитивов корпусом

Проверяем наличие размеченных `item_id` в корпусе. Позитивы вне корпуса
оставляем в знаменателе Recall.

In [9]:
total = summary["unique_positive_pairs"]
outside = summary["positive_pairs_outside_corpus"]
coverage = pd.DataFrame({
    "Позитивные пары": [total - outside, outside],
}, index=["Объявление есть в корпусе", "Объявления нет в корпусе"])
coverage["Доля пар, %"] = (100 * coverage["Позитивные пары"] / total).round(2)
display(coverage)
display(pd.Series({
    "Запросы с контекстом": summary["query_context_groups"],
    "Из них без доступных позитивов": summary["groups_without_retrievable_positive"],
}, name="Количество").to_frame())
print(f"Верхняя граница macro Recall по доступности корпуса: {summary['macro_recall_corpus_ceiling']:.2%}")

                           Позитивные пары  Доля пар, %
Объявление есть в корпусе            29571         6.33
Объявления нет в корпусе            437458        93.67

                                Количество
Запросы с контекстом                354313
Из них без доступных позитивов      327764

Верхняя граница macro Recall по доступности корпуса: 6.08%

Вне корпуса — 437 458 из 467 029 позитивных пар.
Верхняя граница macro Recall на всех train-группах — **6,08%**;
ограничение top-50 может снизить её ещё сильнее.

## 5. Дубли объявлений и пустые запросы

Сравниваем нормализованные заголовки и описания.

In [10]:
display(pd.Series({
    "Повторные строки title + description в корпусе": summary["duplicate_item_text_rows"],
    "Группы повторяющихся заголовков": summary["repeated_title_groups"],
    "Пустые запросы в train": summary["empty_train_query_rows"],
    "Пустые итоговые запросы": summary["empty_benchmark_query_rows"],
    "Повторные тексты итоговых запросов": summary["benchmark_repeated_text_rows"],
}, name="Количество").to_frame())

                                                Количество
Повторные строки title + description в корпусе       19097
Группы повторяющихся заголовков                      15195
Пустые запросы в train                                   0
Пустые итоговые запросы                                  0
Повторные тексты итоговых запросов                       1

Найдено 19 097 повторов заголовка и описания при разных item_id.
Сохраняем все ID: метрика различает такие объявления.
Benchmark ID уникальны, пустых поисковых текстов нет.

## 6. Ресурсы

In [11]:
resource_info = audit["resources"]
display(pd.Series({
    "Python": resource_info["python"],
    "CPU: физические ядра / потоки": f"{resource_info['cpu_physical']} / {resource_info['cpu_logical']}",
    "RAM всего, ГиБ": round(resource_info["ram_total_bytes"] / 2**30, 1),
    "RAM доступно, ГиБ": round(resource_info["ram_available_bytes"] / 2**30, 1),
    "Диск свободно, ГиБ": round(resource_info["disk_free_bytes"] / 2**30, 1),
    "GPU / память, МиБ / драйвер": resource_info["gpu"],
}, name="Значение").to_frame())
display(pd.DataFrame({
    "Размерность": [384, 768],
    "Embeddings float32, МиБ": [round(summary[f"dense_float32_{d}_bytes"] / 2**20, 1) for d in [384, 768]],
}))
display(pd.Series(resource_info["versions"], name="Версия библиотеки").to_frame())

                                                                    Значение
Python                                                                3.12.3
CPU: физические ядра / потоки                                        16 / 32
RAM всего, ГиБ                                                          60.4
RAM доступно, ГиБ                                                       42.0
Диск свободно, ГиБ                                                    1307.5
GPU / память, МиБ / драйвер    NVIDIA GeForce RTX 5090, 32607 MiB, 595.91.07

   Размерность  Embeddings float32, МиБ
0          384                    277.2
1          768                    554.3

             Версия библиотеки
pandas                   3.0.6
numpy                    2.5.3
pyarrow                 25.0.1
nbformat                5.11.1
nbclient                0.11.0
psutil                   7.2.2
bm25s                   0.3.11
scikit-learn             1.9.1
torch                   2.14.0

Embeddings float32 займут 277–554 МиБ при размерности 384–768,
без учёта модели, батчей и индекса.

## 7. Валидация

Откладываем 20% уникальных нормализованных текстов, seed 42.
Все контексты и позитивы одного текста остаются вместе. Повторные пары удаляем.
Временной split невозможен: в данных нет времени событий.

Словарь BM25 строим по корпусу объявлений. Validation labels используются только для оценки.

In [12]:
items = pd.read_parquet(DATA_DIR / "benchmark_items.parquet").sort_values("item_id").reset_index(drop=True)
train = pd.read_parquet(DATA_DIR / "train.parquet", columns=QUERY_FIELDS + ["item_id"])
train["search_query"] = normalize_text(train["search_query"])
texts = np.sort(train["search_query"].unique())
train_texts, validation_texts = train_test_split(
    texts, test_size=VALIDATION_SIZE, random_state=SEED, shuffle=True)
validation_texts = set(validation_texts)
text_ids = {text: hashlib.sha256(text.encode("utf-8")).hexdigest() for text in texts}
split = pd.DataFrame({
    "text_id": [text_ids[text] for text in texts],
    "split": ["validation" if text in validation_texts else "train" for text in texts],
}).sort_values("text_id").reset_index(drop=True)
assert split["text_id"].is_unique
if SPLIT_PATH.exists():
    pd.testing.assert_frame_equal(pd.read_csv(SPLIT_PATH), split)
else:
    split.to_csv(SPLIT_PATH, index=False)
SPLIT_HASH = sha256(SPLIT_PATH)

train["group_id"] = train.groupby(QUERY_FIELDS, dropna=False, sort=True).ngroup()
train["split"] = np.where(train["search_query"].isin(validation_texts), "validation", "train")
assert train.groupby("group_id")["split"].nunique().eq(1).all()
assert set(train_texts).isdisjoint(validation_texts)
assert len(train_texts) + len(validation_texts) == len(texts)
pairs = train[["group_id", "item_id"]].drop_duplicates()
queries = train.drop_duplicates("group_id").set_index("group_id")[["search_query", "split"]]
queries["positives"] = pairs.groupby("group_id")["item_id"].agg(frozenset)
corpus_ids = frozenset(items["item_id"])
queries["available"] = queries["positives"].map(lambda values: values & corpus_ids)
queries["n_positives"] = queries["positives"].map(len)
queries["n_available"] = queries["available"].map(len)
validation = queries.loc[queries["split"].eq("validation")].copy()
assert queries["n_positives"].gt(0).all()
assert len(pairs) == summary["unique_positive_pairs"]
display(queries.groupby("split").agg(
    texts=("search_query", "nunique"), groups=("search_query", "size"),
    positive_pairs=("n_positives", "sum"), available_pairs=("n_available", "sum")))
print(f"SHA-256 split: {SPLIT_HASH}")
print(f"Validation: {validation.n_available.eq(0).sum():,} групп без доступных позитивов")

            texts  groups  positive_pairs  available_pairs
split
train       59123  285932          379842            23844
validation  14781   68381           87187             5727

SHA-256 split: bc175ad59e9f1cd311579a22c1c23682aa27fbac75a03c6f6141fe4ee2e0732e
Validation: 63,229 групп без доступных позитивов

### Пересечение объявлений

Одно объявление может быть позитивом разных запросов в обеих частях split.
Считаем общие item_id и совпадения текстов среди доступных позитивов.
Объявления с одинаковыми текстами сохраняем под исходными ID.

In [13]:
train_positive_ids = frozenset(pairs.loc[pairs.group_id.isin(queries.index[queries.split.eq("train")]), "item_id"])
val_positive_ids = frozenset(pairs.loc[pairs.group_id.isin(validation.index), "item_id"])
item_signatures = pd.Series(list(zip(
    normalize_text(items["item_title_raw"]), normalize_text(items["item_description_raw"])
)), index=items.item_id)
train_signatures = set(item_signatures.loc[item_signatures.index.isin(train_positive_ids)])
val_corpus_signatures = item_signatures.loc[item_signatures.index.isin(val_positive_ids)]
display(pd.Series({
    "Общие позитивные item_id между частями": len(train_positive_ids & val_positive_ids),
    "Validation item_id в корпусе": len(val_corpus_signatures),
    "Из них с текстом среди train-позитивов корпуса": int(val_corpus_signatures.isin(train_signatures).sum()),
}, name="Количество").to_frame())
del item_signatures, train_signatures, val_corpus_signatures

                                                Количество
Общие позитивные item_id между частями               25513
Validation item_id в корпусе                          4809
Из них с текстом среди train-позитивов корпуса        2269

## 8. Метрики

Macro Recall@K усредняем по запросам с контекстом. Позитивы вне корпуса остаются
в знаменателе. Дубликаты выдачи удаляем до отсечения top-K.
Запросы без разметки исключаем из среднего и считаем отдельно.

Дополнительно считаем HitRate@50 и Recall@50 по доступным позитивам —
только среди групп, где есть хотя бы один такой позитив.

In [14]:
def query_metrics(positives, candidates, ks=RECALL_K):
    positives = set(positives)
    unique = list(dict.fromkeys(candidates))
    recalls = {f"Recall@{k}": len(positives.intersection(unique[:k])) / len(positives)
               if positives else np.nan for k in ks}
    recalls["HitRate@50"] = float(bool(positives.intersection(unique[:50]))) if positives else np.nan
    return recalls


def evaluate(query_table, predictions):
    rows = []
    for query in query_table.itertuples():
        candidates = predictions[query.search_query]
        values = query_metrics(query.positives, candidates)
        values["available_Recall@50"] = query_metrics(query.available, candidates)["Recall@50"]
        rows.append(values)
    return pd.DataFrame(rows, index=query_table.index)


assert query_metrics({"a", "b"}, ["a", "a", "b"], (1, 2))["Recall@2"] == 1
assert query_metrics({"a", "outside"}, ["a"])["Recall@50"] == 0.5
assert query_metrics({"outside"}, ["a"])["Recall@50"] == 0
assert query_metrics({"a"}, [])["HitRate@50"] == 0
assert np.isnan(query_metrics(set(), ["a"])["Recall@50"])
# Macro: равный вес запросов, независимо от числа позитивов.
assert np.mean([query_metrics({"a", "b"}, ["a"])["Recall@50"],
                query_metrics({"c"}, ["c"])["Recall@50"]]) == 0.75
print("Метрики: проверки пройдены")

Метрики: проверки пройдены

## 9. E0 — BM25

BM25 по заголовку и описанию: `bm25s`, вариант `lucene`, `k1=1.2`, `b=0.75`, float32.
Параметры без подбора.

Нижний регистр, нормализация пробелов, токены `\w+`. Сохраняем одиночные буквы,
числа, стоп-слова и «ё». Без стемминга и лемматизации.

При равных оценках сортируем по item_id. Нулевые оценки не включаем.
Один текст ищем один раз, каждый контекст оцениваем отдельно.

In [15]:
def tokenize(texts):
    return bm25s.tokenize(texts, lower=False, stopwords=[], token_pattern=TOKEN_PATTERN,
                          return_ids=False, show_progress=False)


def bm25_scores(model, tokens):
    # get_scores() в bm25s не принимает пустой список токенов.
    return model.get_scores_from_ids(model.get_tokens_ids(tokens))


def top_k(scores, k=50):
    if k <= 0:
        return np.empty(0, dtype=np.int64)
    selected = np.flatnonzero(scores > 0)
    if len(selected) > k:
        threshold = np.partition(scores[selected], -k)[-k]
        higher = selected[scores[selected] > threshold]
        tied = selected[scores[selected] == threshold][:k - len(higher)]
        selected = np.concatenate([higher, tied])
    return selected[np.lexsort((selected, -scores[selected]))]


assert tokenize(["ё  Ё  A-15 и"])[0] == ["ё", "Ё", "A", "15", "и"]
assert top_k(np.array([2., 1., 1., 0.]), 2).tolist() == [0, 1]
assert top_k(np.zeros(3)).tolist() == []
assert top_k(np.ones(60), 50).tolist() == list(range(50))
rng = np.random.default_rng(SEED)
for size in (1, 20, 100):
    scores = rng.integers(0, 5, size).astype(np.float32)
    expected = sorted(np.flatnonzero(scores > 0), key=lambda i: (-scores[i], i))[:50]
    assert top_k(scores).tolist() == expected

small_ids = np.array(["0000000000000001", "0000000000000002", "0000000000000003"])
small = bm25s.BM25(**BM25_CONFIG)
small.index(tokenize(["ремонт авто", "ремонт авто", "уборка кухни"]), show_progress=False)
assert small_ids[top_k(bm25_scores(small, ["ремонт"]))].tolist() == small_ids[:2].tolist()
assert top_k(bm25_scores(small, ["несуществующийтокен"])).tolist() == []
assert top_k(bm25_scores(small, [])).tolist() == []
# Для одинаковых документов длины 2 оценка каждого совпадения известна из формулы.
expected_score = np.log(1 + (3 - 2 + 0.5) / (2 + 0.5)) / (1 + BM25_CONFIG["k1"])
np.testing.assert_allclose(bm25_scores(small, ["ремонт"])[:2], expected_score, rtol=1e-6)
print("BM25, top-k и соответствие item_id: проверки пройдены")

BM25, top-k и соответствие item_id: проверки пройдены

In [16]:
start = perf_counter()
corpus_text = normalize_text(items["item_title_raw"].fillna("") + " " + items["item_description_raw"].fillna(""))
corpus_tokens = tokenize(corpus_text.tolist())
retriever = bm25s.BM25(**BM25_CONFIG)
retriever.index(corpus_tokens, show_progress=False)
index_seconds = perf_counter() - start
item_ids = items["item_id"].to_numpy()
assert items["item_id"].is_unique and items["item_id"].is_monotonic_increasing
assert retriever.scores["num_docs"] == len(item_ids)
index_bytes = sum(value.nbytes for value in retriever.scores.values() if isinstance(value, np.ndarray))
del corpus_tokens
_ = gc.collect()
print(f"Индексация: {index_seconds:.2f} с; массивы индекса: {index_bytes / 2**20:.1f} МиБ")

Индексация: 21.41 с; массивы индекса: 183.3 МиБ

In [17]:
predictions, query_seconds = {}, []
val_texts = sorted(validation["search_query"].unique())
start = perf_counter()
val_tokens = tokenize(val_texts)
for text, tokens in zip(val_texts, val_tokens):
    query_start = perf_counter()
    positions = top_k(bm25_scores(retriever, tokens), max(RECALL_K))
    predictions[text] = item_ids[positions].tolist()
    query_seconds.append(perf_counter() - query_start)
search_seconds = perf_counter() - start
assert set(predictions) == set(val_texts)
assert all(len(ids) <= 50 and len(ids) == len(set(ids)) and set(ids) <= corpus_ids
           for ids in predictions.values())
per_query = evaluate(validation, predictions)
metrics = per_query.mean()
assert per_query["Recall@50"].notna().all()
assert per_query[[f"Recall@{k}" for k in RECALL_K]].diff(axis=1).iloc[:, 1:].ge(0).all().all()
ceiling = (validation["n_available"].clip(upper=50) / validation["n_positives"]).mean()
assert metrics["Recall@50"] <= ceiling + 1e-12
display(metrics.rename("Значение").to_frame().round(6))
display(pd.Series({
    "Validation-группы": len(validation),
    "Группы без разметки": int(validation.n_positives.eq(0).sum()),
    "Группы с доступными позитивами": int(validation.n_available.gt(0).sum()),
    "Уникальные тексты для поиска": len(val_texts),
    "Тексты без кандидатов": sum(not values for values in predictions.values()),
    "Верхняя граница Recall@50": ceiling,
    "Индексация, с": index_seconds,
    "Поиск с токенизацией, с": search_seconds,
    "Поиск без токенизации, p50 мс": float(np.percentile(query_seconds, 50) * 1000),
    "Поиск без токенизации, p95 мс": float(np.percentile(query_seconds, 95) * 1000),
    "Массивы индекса, МиБ": index_bytes / 2**20,
    "RSS процесса после поиска, МиБ": psutil.Process().memory_info().rss / 2**20,
}, name="Значение").to_frame())

                     Значение
Recall@1             0.001626
Recall@5             0.005165
Recall@10            0.008089
Recall@20            0.012069
Recall@50            0.019168
HitRate@50           0.023369
available_Recall@50  0.297620

                                    Значение
Validation-группы               68381.000000
Группы без разметки                 0.000000
Группы с доступными позитивами   5152.000000
Уникальные тексты для поиска    14781.000000
Тексты без кандидатов              45.000000
Верхняя граница Recall@50           0.061306
Индексация, с                      21.406764
Поиск с токенизацией, с             3.486597
Поиск без токенизации, p50 мс       0.174310
Поиск без токенизации, p95 мс       0.544020
Массивы индекса, МиБ              183.349854
RSS процесса после поиска, МиБ   4658.273438

Поиск последовательный, на CPU. Индексация включает подготовку текста и токенизацию.
RSS показывает память всего процесса после поиска, а не пиковое потребление индекса.

In [18]:
experiment = {
    "experiment": "E0", "status": "completed", "config": json.dumps(BM25_CONFIG, sort_keys=True),
    "token_pattern": TOKEN_PATTERN, "fields": "title + description", "seed": SEED,
    "validation_size": VALIDATION_SIZE, "split_sha256": SPLIT_HASH,
    "corpus_sha256": sha256(DATA_DIR / "benchmark_items.parquet"),
    "train_sha256": sha256(DATA_DIR / "train.parquet"),
    "bm25s_version": importlib.metadata.version("bm25s"), "device": "cpu",
    **{name: float(value) for name, value in metrics.items()}, "delta_Recall@50": 0.0,
    "index_seconds": index_seconds, "search_seconds": search_seconds,
    "index_MiB": index_bytes / 2**20, "validation_groups": len(validation),
    "conclusion": f"Recall@50={metrics['Recall@50']:.4%}; по доступным позитивам={metrics['available_Recall@50']:.2%}",
}
experiments = pd.DataFrame([experiment])
# Повторный запуск обновляет E0; результаты других экспериментов сохраняются.
if EXPERIMENTS_PATH.exists():
    previous = pd.read_csv(EXPERIMENTS_PATH)
    experiments = pd.concat([previous.loc[previous.experiment.ne("E0")], experiments], ignore_index=True)
experiments.to_csv(EXPERIMENTS_PATH, index=False)
display(experiments[["experiment", "status", "Recall@1", "Recall@5", "Recall@10", "Recall@20", "Recall@50"]])

,experiment,status,Recall@1,Recall@5,Recall@10,Recall@20,Recall@50
0,E1_title,completed,0.001385,0.004453,0.006679,0.009545,0.014627
1,E1_description,completed,0.001275,0.004290,0.007144,0.010456,0.016294
2,E1_title1_description1,completed,0.001782,0.005579,0.008227,0.012068,0.018960
3,E1_title2_description1,completed,0.001769,0.005324,0.008113,0.011961,0.018315
4,E1_title4_description1,completed,0.001545,0.005050,0.007639,0.011418,0.017560
5,E2_word,completed,0.000755,0.002981,0.005523,0.009084,0.015504
6,E2_char,completed,0.000714,0.002582,0.004389,0.007419,0.013516
7,E3,completed,0.001363,0.004886,0.007467,0.011443,0.018395
8,E0,completed,0.001626,0.005165,0.008089,0.012069,0.019168

BM25: **Recall@50 = 1,92%** по 68 381 validation-группе.
У 63 229 групп нет позитивов в корпусе; верхняя граница Recall@50 — **6,13%**.
По доступным позитивам среди 5 152 групп Recall@50 — **29,76%**.
У 45 текстов нет совпадений со словарём корпуса.

## 10. E1 — вес заголовка

Гипотеза: совпадения в заголовке полезнее совпадений в длинном описании.
Сравниваем два поля отдельно и `w × BM25(title) + BM25(description)` при `w ∈ {1, 2, 4}`.
Это сумма оценок двух независимых индексов, не BM25F.

В каждом поле свои IDF и нормализация длины. Корпус, split, токенизация, `k1` и `b` те же, что в E0.
Нулевой вес исключает поле; равенства оценок разрешаем по item_id.

In [19]:
def weighted_bm25_scores(models, tokens, weights):
    scores = np.zeros(models["title"].scores["num_docs"], dtype=np.float32)
    for field, weight in weights.items():
        if weight:
            scores += weight * bm25_scores(models[field], tokens)
    return scores


def cluster_delta_interval(baseline, candidate, text_groups, confidence=BOOTSTRAP_CONFIDENCE):
    clustered = pd.DataFrame({
        "delta": np.asarray(candidate) - np.asarray(baseline),
        "text": np.asarray(text_groups),
    }).groupby("text", sort=True)["delta"].agg(["sum", "size"])
    # Пересэмплируем тексты, но сохраняем равный вес контекстных запросов в macro Recall.
    result = bootstrap(
        (clustered["sum"].to_numpy(), clustered["size"].to_numpy()),
        lambda totals, counts, axis: totals.sum(axis=axis) / counts.sum(axis=axis),
        paired=True, vectorized=True, n_resamples=BOOTSTRAP_RESAMPLES, batch=64,
        confidence_level=confidence, method="percentile", rng=np.random.default_rng(SEED),
    )
    return float(result.confidence_interval.low), float(result.confidence_interval.high)


small_description = bm25s.BM25(**BM25_CONFIG)
small_description.index(tokenize(["уборка кухни", "уборка кухни", "ремонт авто"]), show_progress=False)
small_fields = {"title": small, "description": small_description}
np.testing.assert_array_equal(
    weighted_bm25_scores(small_fields, ["ремонт"], E1_VARIANTS["E1_title"]),
    bm25_scores(small, ["ремонт"]))
np.testing.assert_array_equal(
    weighted_bm25_scores(small_fields, ["ремонт"], E1_VARIANTS["E1_description"]),
    bm25_scores(small_description, ["ремонт"]))
combined = weighted_bm25_scores(small_fields, ["ремонт"], E1_VARIANTS["E1_title2_description1"])
np.testing.assert_allclose(combined, 2 * bm25_scores(small, ["ремонт"]) + bm25_scores(small_description, ["ремонт"]))
assert small_ids[top_k(combined, 1)].tolist() == ["0000000000000003"]
assert top_k(weighted_bm25_scores(small_fields, [], E1_VARIANTS["E1_title1_description1"])).tolist() == []
assert cluster_delta_interval([0, 0, 0], [.25, .25, .25], ["a", "a", "b"]) == (.25, .25)
assert cluster_delta_interval([.5, 1, 0], [.5, 1, 0], ["a", "a", "b"]) == (0, 0)
print("Оценки полей, соответствие ID и bootstrap: проверки пройдены")

Оценки полей, соответствие ID и bootstrap: проверки пройдены

In [20]:
field_models, field_index_seconds, field_index_bytes = {}, {}, {}
for field, column in [("title", "item_title_raw"), ("description", "item_description_raw")]:
    start = perf_counter()
    field_tokens = tokenize(normalize_text(items[column]).tolist())
    model = bm25s.BM25(**BM25_CONFIG)
    model.index(field_tokens, show_progress=False)
    assert model.scores["num_docs"] == len(item_ids)
    field_models[field] = model
    field_index_seconds[field] = perf_counter() - start
    field_index_bytes[field] = sum(value.nbytes for value in model.scores.values() if isinstance(value, np.ndarray))
    del field_tokens
_ = gc.collect()
display(pd.DataFrame({
    "Индексация, с": field_index_seconds,
    "Массивы индекса, МиБ": {field: size / 2**20 for field, size in field_index_bytes.items()},
}))

             Индексация, с  Массивы индекса, МиБ
title             1.503129              6.860123
description      21.668928            181.266212

Интервалы изменения Recall@50: парный bootstrap по текстам, 2 000 повторов.
Для пяти сравнений с E0 используем интервалы 99% (поправка Бонферрони).
Выбор лучшего веса и оценка сделаны на одном validation split.

In [21]:
e1_rows = []
e1_per_query = {"E0": per_query}
best_e1_experiment, best_e1_recall = None, -np.inf
best_e1_predictions = None
for name, weights in E1_VARIANTS.items():
    variant_predictions, variant_query_seconds = {}, []
    start = perf_counter()
    variant_tokens = tokenize(val_texts)
    for text, tokens in zip(val_texts, variant_tokens):
        query_start = perf_counter()
        positions = top_k(weighted_bm25_scores(field_models, tokens, weights), max(RECALL_K))
        variant_predictions[text] = item_ids[positions].tolist()
        variant_query_seconds.append(perf_counter() - query_start)
    variant_search_seconds = perf_counter() - start
    assert set(variant_predictions) == set(val_texts)
    assert all(len(ids) <= 50 and len(ids) == len(set(ids)) and set(ids) <= corpus_ids
               for ids in variant_predictions.values())
    variant_per_query = evaluate(validation, variant_predictions)
    assert variant_per_query.index.equals(per_query.index)
    assert variant_per_query["Recall@50"].notna().all()
    assert variant_per_query[[f"Recall@{k}" for k in RECALL_K]].diff(axis=1).iloc[:, 1:].ge(0).all().all()
    variant_metrics = variant_per_query.mean()
    assert variant_metrics["Recall@50"] <= ceiling + 1e-12
    ci_low, ci_high = cluster_delta_interval(
        per_query["Recall@50"], variant_per_query["Recall@50"], validation["search_query"])
    active_fields = [field for field, weight in weights.items() if weight]
    row = {
        **experiment, "experiment": name,
        "config": json.dumps({**BM25_CONFIG, "field_weights": weights}, sort_keys=True),
        "fields": " + ".join(active_fields),
        **{metric: float(value) for metric, value in variant_metrics.items()},
        "delta_Recall@50": variant_metrics["Recall@50"] - metrics["Recall@50"],
        "delta_ci_low": ci_low, "delta_ci_high": ci_high,
        "bootstrap_confidence": BOOTSTRAP_CONFIDENCE, "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
        "index_seconds": sum(field_index_seconds[field] for field in active_fields),
        "index_MiB": sum(field_index_bytes[field] for field in active_fields) / 2**20,
        "search_seconds": variant_search_seconds,
        "search_p50_ms": float(np.percentile(variant_query_seconds, 50) * 1000),
        "search_p95_ms": float(np.percentile(variant_query_seconds, 95) * 1000),
        "rss_MiB": psutil.Process().memory_info().rss / 2**20,
        "empty_query_texts": sum(not ids for ids in variant_predictions.values()),
        "conclusion": f"Recall@50={variant_metrics['Recall@50']:.4%}; веса полей={weights}",
    }
    e1_rows.append(row)
    e1_per_query[name] = variant_per_query
    if variant_metrics["Recall@50"] > best_e1_recall:
        best_e1_experiment, best_e1_recall = name, variant_metrics["Recall@50"]
        best_e1_predictions = variant_predictions
    print(f"{name}: Recall@50={variant_metrics['Recall@50']:.4%}")

experiments = pd.concat([
    experiments.loc[~experiments.experiment.isin(E1_VARIANTS)], pd.DataFrame(e1_rows)
], ignore_index=True)
assert experiments.experiment.is_unique
experiments.to_csv(EXPERIMENTS_PATH, index=False)
comparison = experiments.loc[experiments.experiment.isin(["E0", *E1_VARIANTS])].copy()
display(comparison[["experiment", "Recall@1", "Recall@5", "Recall@10", "Recall@20", "Recall@50",
                    "available_Recall@50", "delta_Recall@50", "delta_ci_low", "delta_ci_high"]].round(6))
display(comparison[["experiment", "index_seconds", "search_seconds", "index_MiB"]].round(2))
best_experiment = best_e1_experiment if best_e1_recall > metrics["Recall@50"] else "E0"
print(f"Лучший вариант E1: {best_e1_experiment} — {best_e1_recall:.4%}")
print(f"Лучший вариант с учётом E0: {best_experiment}")

E1_title: Recall@50=1.4627%

E1_description: Recall@50=1.6294%

E1_title1_description1: Recall@50=1.8960%

E1_title2_description1: Recall@50=1.8315%

E1_title4_description1: Recall@50=1.7560%

,experiment,Recall@1,Recall@5,Recall@10,Recall@20,Recall@50,available_Recall@50,delta_Recall@50,delta_ci_low,delta_ci_high
3,E0,0.001626,0.005165,0.008089,0.012069,0.019168,0.297620,0.000000,NaN,NaN
4,E1_title,0.001385,0.004453,0.006679,0.009545,0.014627,0.233371,-0.004541,-0.005846,-0.003337
5,E1_description,0.001275,0.004290,0.007144,0.010456,0.016294,0.253143,-0.002873,-0.003556,-0.002169
6,E1_title1_description1,0.001782,0.005579,0.008227,0.012068,0.018960,0.298519,-0.000207,-0.000954,0.000481
7,E1_title2_description1,0.001769,0.005324,0.008113,0.011961,0.018315,0.290581,-0.000853,-0.001760,0.000089
8,E1_title4_description1,0.001545,0.005050,0.007639,0.011418,0.017560,0.278194,-0.001607,-0.002670,-0.000536

               experiment  index_seconds  search_seconds  index_MiB
3                      E0          21.41            3.49     183.35
4                E1_title           1.50            2.27       6.86
5          E1_description          21.67            3.94     181.27
6  E1_title1_description1          23.17            4.76     188.13
7  E1_title2_description1          23.17            4.76     188.13
8  E1_title4_description1          23.17            4.77     188.13

Лучший вариант E1: E1_title1_description1 — 1.8960%
Лучший вариант с учётом E0: E0

Время поиска измерено отдельно для каждой конфигурации, включая токенизацию запросов.
Для суммы полей стоимость индексации — сумма двух индексов. Индексы между вариантами
переиспользуются; RSS включает все загруженные индексы и результаты.

In [22]:
delta = e1_per_query[best_e1_experiment]["Recall@50"] - per_query["Recall@50"]
display(pd.Series({
    "Группы с ростом Recall@50": int(delta.gt(0).sum()),
    "Группы со снижением Recall@50": int(delta.lt(0).sum()),
    "Без изменения": int(delta.eq(0).sum()),
}, name=best_e1_experiment).to_frame())

# Первые три различных текста каждого типа в алфавитном порядке.
examples = []
titles_by_id = items.set_index("item_id")["item_title_raw"]
for label, improved in [("Найден только E1", True), ("Найден только E0", False)]:
    seen_texts = set()
    for query in validation.sort_values("search_query", kind="stable").itertuples():
        if query.search_query in seen_texts:
            continue
        base = predictions[query.search_query]
        candidate = best_e1_predictions[query.search_query]
        difference = (set(candidate) - set(base)) if improved else (set(base) - set(candidate))
        changed_positives = sorted(query.available & difference)
        if not changed_positives:
            continue
        item_id = changed_positives[0]
        examples.append({
            "Случай": label, "Запрос": query.search_query, "group_id": query.Index,
            "item_id": item_id, "Заголовок позитива": titles_by_id[item_id],
            "Ранг E0": base.index(item_id) + 1 if item_id in base else ">50",
            "Ранг E1": candidate.index(item_id) + 1 if item_id in candidate else ">50",
        })
        seen_texts.add(query.search_query)
        if len(seen_texts) == 3:
            break
display(pd.DataFrame(examples))

                               E1_title1_description1
Группы с ростом Recall@50                         262
Группы со снижением Recall@50                     264
Без изменения                                   67855

,Случай,Запрос,group_id,item_id,Заголовок позитива,Ранг E0,Ранг E1
0,Найден только E1,3d печать,412,6cb949d70341a638,3D печать,>50,26
1,Найден только E1,volkswagen polo,2835,20277fdaf89ff58f,"Volkswagen Polo 2015 Аренда авто с выкупом, лизинг",>50,15
2,Найден только E1,аварийное вскрытие замков двери 24/7,3190,d86a5c4ef8197e64,Аварийное вскрытие замков двери 24/7,>50,3
3,Найден только E0,3d печать,361,de068bbdaf44201d,Печать на 3D принтере (3Д моделирование),11,>50
4,Найден только E0,sup аренда,2710,1e38849ba62257fb,"Лучшие сапы в Пензе,сапборд в аренду,сап в аренду",22,>50
5,Найден только E0,автовоз из владивостока,5099,4c1e821887b89a0a,Услуги автовоза-доставка автомобилей по России,43,>50

Лучший E1 — сумма полей 1:1: **Recall@50 = 1,896%**, против **1,917%** у E0.
Разница — **−0,021 п.п.**, 99% bootstrap-интервал: **[−0,095; +0,048] п.п.**
Улучшение не подтверждено. Усиление заголовка до 2:1 и 4:1 снижает Recall@50.

Сумма 1:1 немного улучшает Recall@1/5/10, но не основную метрику.
Для суммы полей нужны два индекса. Сохраняем E0: у него наибольший Recall@50
на этом split и меньшее время поиска.

## 11. E2 — TF-IDF

Word TF-IDF учитывает слова и соседние пары слов; character TF-IDF — фрагменты слов,
которые могут совпасть при опечатках и изменении окончаний.
Оба варианта используют заголовок и описание, L2-нормализацию и cosine similarity.

Словарь и IDF считаем только по корпусу. Редкие n-граммы (`df < 2`) исключаем;
лимит словаря — 300 тыс. для word и 200 тыс. для char, чтобы ограничить память.
TF — `1 + log(count)`. Стоп-слова сохраняем. Параметры фиксированы без подбора.

Поиск точный, батчами на CPU. При равных оценках выбираем меньший item_id;
нулевые совпадения не включаем в выдачу.

In [23]:
def sparse_top_k(query_matrix, documents_t, k=50, batch_size=TFIDF_BATCH_SIZE, n_threads=TFIDF_THREADS):
    results, tie_rows = [], 0
    if k <= 0 or documents_t.shape[1] == 0:
        return [np.empty(0, dtype=np.int64) for _ in range(query_matrix.shape[0])], 0
    for start in range(0, query_matrix.shape[0], batch_size):
        query_batch = query_matrix[start:start + batch_size]
        matches = sp_matmul_topn(query_batch, documents_t, top_n=min(k + 1, documents_t.shape[1]),
                                threshold=0.0, sort=True, n_threads=n_threads)
        for i in range(query_batch.shape[0]):
            row = matches.getrow(i)
            positive = row.data > 0
            ids, scores = row.indices[positive], row.data[positive]
            order = np.lexsort((ids, -scores))
            # k+1 позволяет заметить равенство на границе top-k.
            if len(order) > k and scores[order[k - 1]] == scores[order[k]]:
                full_scores = (query_batch.getrow(i) @ documents_t).toarray().ravel()
                results.append(top_k(full_scores, k))
                tie_rows += 1
            else:
                results.append(ids[order[:k]])
    return results, tie_rows


rng = np.random.default_rng(SEED)
toy_docs = csr_matrix(rng.integers(0, 3, (70, 12)).astype(np.float32))
toy_queries = csr_matrix(rng.integers(0, 3, (6, 12)).astype(np.float32))
for threads in (1, TFIDF_THREADS):
    found, _ = sparse_top_k(toy_queries, toy_docs.T.tocsr(), k=5, batch_size=2, n_threads=threads)
    expected = (toy_queries @ toy_docs.T).toarray()
    for i in range(len(found)):
        np.testing.assert_array_equal(found[i], top_k(expected[i], 5))
identical_docs = csr_matrix(np.ones((60, 2), dtype=np.float32))
found, ties = sparse_top_k(csr_matrix([[1., 1.], [0., 0.]], dtype=np.float32), identical_docs.T.tocsr())
assert found[0].tolist() == list(range(50)) and found[1].tolist() == [] and ties == 1

# Искусственные примеры проверяют токенизацию, а не качество на validation.
toy_texts = ["ремонт холодильников", "химчистка диванов", "ремонт iphone 13", "чистка кондиционеров"]
toy_query_texts = ["холодилник", "диван", "iphone13", "кондиционер"]
toy_vectorizer = TfidfVectorizer(**TFIDF_COMMON, analyzer="char_wb", ngram_range=(3, 5))
toy_matrix = toy_vectorizer.fit_transform(toy_texts)
toy_q = toy_vectorizer.transform(toy_query_texts)
found, _ = sparse_top_k(toy_q, toy_matrix.T.tocsr(), k=1)
assert [int(ids[0]) for ids in found] == [0, 1, 2, 3]
np.testing.assert_allclose(np.asarray(toy_matrix.multiply(toy_matrix).sum(axis=1)).ravel(), 1, atol=1e-6)
assert toy_vectorizer.transform([""]).nnz == 0
print("Разреженный top-k, равенства, пустые запросы и токенизация: проверки пройдены")

Разреженный top-k, равенства, пустые запросы и токенизация: проверки пройдены

In [24]:
tfidf_models, tfidf_index_rows = {}, []
for name, config in TFIDF_VARIANTS.items():
    start = perf_counter()
    vectorizer = TfidfVectorizer(**TFIDF_COMMON, **config)
    matrix = vectorizer.fit_transform(corpus_text).tocsr()
    documents_t = matrix.T.tocsr()
    duration = perf_counter() - start
    assert matrix.shape[0] == len(item_ids) and matrix.dtype == np.float32
    norms = np.asarray(matrix.multiply(matrix).sum(axis=1)).ravel()
    np.testing.assert_allclose(norms[norms > 0], 1, atol=2e-5)
    index_bytes_tfidf = sum(a.nbytes for m in (matrix, documents_t) for a in (m.data, m.indices, m.indptr))
    tfidf_models[name] = (vectorizer, documents_t)
    tfidf_index_rows.append({
        "experiment": name, "index_seconds": duration, "features": matrix.shape[1],
        "nonzero_values": matrix.nnz, "empty_documents": int((norms == 0).sum()),
        "index_MiB": index_bytes_tfidf / 2**20,
    })
    print(f"{name}: {matrix.shape[1]:,} признаков; {duration:.1f} с")
    del matrix, norms
    _ = gc.collect()
tfidf_index_info = pd.DataFrame(tfidf_index_rows).set_index("experiment")
display(tfidf_index_info.round(2))

E2_word: 300,000 признаков; 45.3 с

E2_char: 200,000 признаков; 131.2 с

,index_seconds,features,nonzero_values,empty_documents,index_MiB
experiment,,,,,
E2_word,45.30,300000,40294947,2,616.72
E2_char,131.22,200000,319117616,0,4870.83

Время индексации включает построение TF-IDF и транспонирование.
Размер матриц указан до удаления исходной CSR; словарь Python в него не входит.
Время поиска включает преобразование запросов и извлечение top-50.
97,5% bootstrap-интервалы рассчитаны для двух сравнений с E0 (Бонферрони), по текстам запросов.
TF-IDF использует до 8 CPU-потоков; BM25 измерен последовательно. Время отражает эти режимы запуска.

In [25]:
e2_rows, e2_predictions, e2_per_query = [], {}, {}
for name, (vectorizer, documents_t) in tfidf_models.items():
    start = perf_counter()
    query_matrix = vectorizer.transform(val_texts).tocsr()
    positions, tie_rows = sparse_top_k(query_matrix, documents_t, max(RECALL_K))
    candidate_predictions = {text: item_ids[ids].tolist() for text, ids in zip(val_texts, positions)}
    duration = perf_counter() - start
    assert set(candidate_predictions) == set(val_texts)
    assert all(len(ids) <= 50 and len(ids) == len(set(ids)) and set(ids) <= corpus_ids
               for ids in candidate_predictions.values())
    candidate_per_query = evaluate(validation, candidate_predictions)
    assert candidate_per_query.index.equals(per_query.index)
    assert candidate_per_query["Recall@50"].notna().all()
    assert candidate_per_query[[f"Recall@{k}" for k in RECALL_K]].diff(axis=1).iloc[:, 1:].ge(0).all().all()
    candidate_metrics = candidate_per_query.mean()
    assert candidate_metrics["Recall@50"] <= ceiling + 1e-12
    ci_low, ci_high = cluster_delta_interval(per_query["Recall@50"], candidate_per_query["Recall@50"],
                                             validation["search_query"], confidence=E2_CONFIDENCE)
    config = {**TFIDF_COMMON, **TFIDF_VARIANTS[name], "dtype": "float32",
              "batch_size": TFIDF_BATCH_SIZE, "threads": TFIDF_THREADS}
    row = {
        **experiment, "experiment": name, "config": json.dumps(config, sort_keys=True),
        "bm25s_version": None, "sklearn_version": importlib.metadata.version("scikit-learn"),
        "sparse_dot_topn_version": importlib.metadata.version("sparse-dot-topn"),
        "token_pattern": TOKEN_PATTERN if name == "E2_word" else None,
        **{metric: float(value) for metric, value in candidate_metrics.items()},
        **tfidf_index_info.loc[name].to_dict(), "search_seconds": duration,
        "delta_Recall@50": candidate_metrics["Recall@50"] - metrics["Recall@50"],
        "delta_ci_low": ci_low, "delta_ci_high": ci_high,
        "bootstrap_confidence": E2_CONFIDENCE, "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
        "rss_MiB": psutil.Process().memory_info().rss / 2**20,
        "empty_query_texts": sum(not ids for ids in candidate_predictions.values()),
        "boundary_tie_queries": tie_rows,
        "conclusion": f"Recall@50={candidate_metrics['Recall@50']:.4%}; {TFIDF_VARIANTS[name]['analyzer']} TF-IDF",
    }
    e2_rows.append(row)
    e2_predictions[name] = candidate_predictions
    e2_per_query[name] = candidate_per_query
    print(f"{name}: Recall@50={candidate_metrics['Recall@50']:.4%}; поиск {duration:.1f} с")

experiments = pd.concat([experiments.loc[~experiments.experiment.isin(TFIDF_VARIANTS)], pd.DataFrame(e2_rows)], ignore_index=True)
assert experiments.experiment.is_unique
experiments.to_csv(EXPERIMENTS_PATH, index=False)
display(experiments[["experiment", "Recall@1", "Recall@5", "Recall@10", "Recall@20", "Recall@50",
                     "available_Recall@50", "delta_Recall@50"]].round(6))
display(experiments.loc[experiments.experiment.isin(TFIDF_VARIANTS),
    ["experiment", "delta_ci_low", "delta_ci_high", "index_seconds", "search_seconds", "index_MiB", "empty_query_texts", "boundary_tie_queries"]].round(4))

E2_word: Recall@50=1.5504%; поиск 1.8 с

E2_char: Recall@50=1.3516%; поиск 12.3 с

,experiment,Recall@1,Recall@5,Recall@10,Recall@20,Recall@50,available_Recall@50,delta_Recall@50
0,E3,0.001363,0.004886,0.007467,0.011443,0.018395,0.287525,-0.000773
1,E0,0.001626,0.005165,0.008089,0.012069,0.019168,0.297620,0.000000
2,E1_title,0.001385,0.004453,0.006679,0.009545,0.014627,0.233371,-0.004541
3,E1_description,0.001275,0.004290,0.007144,0.010456,0.016294,0.253143,-0.002873
4,E1_title1_description1,0.001782,0.005579,0.008227,0.012068,0.018960,0.298519,-0.000207
5,E1_title2_description1,0.001769,0.005324,0.008113,0.011961,0.018315,0.290581,-0.000853
6,E1_title4_description1,0.001545,0.005050,0.007639,0.011418,0.017560,0.278194,-0.001607
7,E2_word,0.000755,0.002981,0.005523,0.009084,0.015504,0.239996,-0.003664
8,E2_char,0.000714,0.002582,0.004389,0.007419,0.013516,0.204643,-0.005652

,experiment,delta_ci_low,delta_ci_high,index_seconds,search_seconds,index_MiB,empty_query_texts,boundary_tie_queries
7,E2_word,-0.0045,-0.0029,45.2994,1.7806,616.7183,196.0,758.0
8,E2_char,-0.0067,-0.0047,131.2216,12.3439,4870.8331,1.0,713.0

### Какие позитивы находят методы

Считаем уникальные размеченные пары запрос–объявление, включая недоступные в корпусе.
Пары имеют равный вес в этой таблице; основная метрика выше усреднена по запросам.

In [26]:
pair_rows, e2_changed_examples = [], []
for name, candidate_predictions in e2_predictions.items():
    counts = {"Оба": 0, "Только E0": 0, "Только TF-IDF": 0, "Ни один": 0}
    example_counts = {"Только E0": set(), "Только TF-IDF": set()}
    for query in validation.sort_values("search_query", kind="stable").itertuples():
        base, candidate = predictions[query.search_query], candidate_predictions[query.search_query]
        base_found, candidate_found = query.positives & set(base), query.positives & set(candidate)
        counts["Оба"] += len(base_found & candidate_found)
        counts["Только E0"] += len(base_found - candidate_found)
        counts["Только TF-IDF"] += len(candidate_found - base_found)
        counts["Ни один"] += len(query.positives - (base_found | candidate_found))
        for label, changed in [("Только E0", base_found - candidate_found), ("Только TF-IDF", candidate_found - base_found)]:
            if changed and len(example_counts[label]) < 5 and query.search_query not in example_counts[label]:
                item_id = sorted(changed)[0]
                e2_changed_examples.append({
                    "Метод": name, "Случай": label, "Запрос": query.search_query, "group_id": query.Index,
                    "item_id": item_id, "Заголовок": titles_by_id[item_id],
                    "Ранг E0": base.index(item_id) + 1 if item_id in base else ">50",
                    "Ранг TF-IDF": candidate.index(item_id) + 1 if item_id in candidate else ">50",
                })
                example_counts[label].add(query.search_query)
    assert sum(counts.values()) == validation.n_positives.sum()
    pair_rows.append({"Метод": name, **counts, "Всего пар": sum(counts.values())})
display(pd.DataFrame(pair_rows).set_index("Метод"))
# Примеры выбираются по алфавиту, без отбора по величине улучшения.
display(pd.DataFrame(e2_changed_examples))

          Оба  Только E0  Только TF-IDF  Ни один  Всего пар
Метод
E2_word  1143        512            184    85348      87187
E2_char   882        773            235    85297      87187

,Метод,Случай,Запрос,group_id,item_id,Заголовок,Ранг E0,Ранг TF-IDF
0,E2_word,Только E0,3d печать,362,b2b8ad0d0f44ca87,"3D Печать, 3D Сканирование, 3D Моделирование 24/7",42,>50
1,E2_word,Только TF-IDF,3d печать,399,5496b03fc45256c7,3д/3D печать,>50,38
2,E2_word,Только E0,mercari выкуп,2071,fab5bf956436a174,Байер Япония (Mercari/Yahoo/Rakuten и тд),1,>50
3,E2_word,Только E0,smas лифтинг,2527,6fce025768d766a2,Микроигольчатый РФ лифтинг. Лицо+Шея. Ищу моделей,42,>50
4,E2_word,Только TF-IDF,volkswagen polo,2835,20277fdaf89ff58f,"Volkswagen Polo 2015 Аренда авто с выкупом, лизинг",>50,36
5,E2_word,Только E0,автовоз из владивостока,5099,4c1e821887b89a0a,Услуги автовоза-доставка автомобилей по России,43,>50
6,E2_word,Только TF-IDF,автовоз москва,5164,aa6a7171651854df,Автовоз в/из Екатеринбург. Перевозка автомобилей,>50,49
7,E2_word,Только TF-IDF,автовыкуп,5257,94afaadfef830f43,Автовыкуп Липецк. Выкуп авто сегодня. Продать авто,>50,18
8,E2_word,Только E0,автоэлектрик круглосуточно,10083,9328d4b848a5a3d6,Автоэлектрик,22,>50
9,E2_word,Только TF-IDF,активация vr очки,11880,86b708dd82f85a62,"Настройка Oculus Quest 2,3,3s VR шлем",>50,37
10,E2_char,Только E0,3d печать,424,c9a823ae64fbd1eb,Профессиональная 3D печать,25,>50
11,E2_char,Только TF-IDF,3d печать,339,dd09a2bfab222d0f,3D печать,>50,39
12,E2_char,Только TF-IDF,ip видеонаблюдение,1466,960ee99868b1118f,Монтаж и обслуживание видеонаблюдения,>50,9
13,E2_char,Только E0,mercari выкуп,2071,fab5bf956436a174,Байер Япония (Mercari/Yahoo/Rakuten и тд),1,>50
14,E2_char,Только E0,sla печать,2512,b765441de5364699,"Художественная SLA печать,покрас 3D моделей",31,>50
15,E2_char,Только E0,smas лифтинг,2527,6fce025768d766a2,Микроигольчатый РФ лифтинг. Лицо+Шея. Ищу моделей,42,>50
16,E2_char,Только E0,sup аренда,2710,1e38849ba62257fb,"Лучшие сапы в Пензе,сапборд в аренду,сап в аренду",22,>50
17,E2_char,Только TF-IDF,автоэвакуатор,8771,d75a53b7c51b0c3a,Услуги эвакуатора,>50,4
18,E2_char,Только TF-IDF,айртач,11405,43ae68e79842e537,"Сложное окрашивание волос, айртач, мелирование",>50,38
19,E2_char,Только TF-IDF,алмазная резка,12066,8546e0014c433061,Алмазная резка и бурение,>50,20

Word TF-IDF получил **Recall@50 = 1,550%**, character — **1,352%**,
BM25 — **1,917%**. Интервалы разницы с E0 целиком ниже нуля.
Оба TF-IDF уступают BM25 как самостоятельные методы отбора.

При этом word нашёл 184 позитивные пары вне top-50 BM25, char — 235.
Это дополняемость выдач, а не доказательство улучшения гибрида.

Для «автоэвакуатор» char нашёл позитив на 4-м месте: в описании — «услуги автоэвакуатора».
Для «ip видеонаблюдение» — на 9-м: в объявлении используется форма «видеонаблюдения».
Оба позитива отсутствуют в top-50 BM25. Обратный пример — «mercari выкуп»:
BM25 поставил позитив первым, оба TF-IDF не включили его в top-50.
Основным lexical baseline остаётся BM25.

## 12. E3 — zero-shot dense retrieval

Гипотеза: семантические embeddings найдут позитивы без точного совпадения слов.
Одна модель `intfloat/multilingual-e5-small`, без обучения и подбора параметров.
Заголовок и описание сохраняют регистр; для каждого нормализованного запроса берём
лексикографически первый исходный текст из train, без обращения к позитивам.

384 измерения, mean pooling с маской padding, L2-нормализация, cosine similarity.
Префиксы `query: ` и `passage: `, максимум 512 токенов с обрезкой справа.
Точный поиск по всему корпусу в float32; равенства разрешаем по item_id.
Отрицательные и нулевые оценки допустимы. Контексты и знаменатель Recall прежние.
Для разницы с E0 — парный bootstrap по текстам, 2000 повторов, 95% интервал.

In [27]:
from sentence_transformers import SentenceTransformer

DENSE_CONFIG = {
    "model": "intfloat/multilingual-e5-small",
    "revision": "614241f622f53c4eeff9890bdc4f31cfecc418b3",
    "dimension": 384, "pooling": "mean", "normalize_embeddings": True,
    "similarity": "cosine", "dtype": "float32", "max_length": 512,
    "query_prefix": "query: ", "document_prefix": "passage: ",
    "batch_size": 32, "search_batch_size": 64,
    "query_text": "lexicographically first raw text per normalized text",
    "document_text": "raw title + newline + raw description",
    "tie_break": "item_id ascending", "search": "exact matrix multiplication",
}
DENSE_DIR = Path(".cache/e3")
DENSE_DIR.mkdir(parents=True, exist_ok=True)
# Отключаем TF32: поиск и encoder используют float32 без autocast.
torch.set_float32_matmul_precision("highest")
torch.set_num_threads(min(8, os.cpu_count() or 1))
start = perf_counter()
encoder = SentenceTransformer(
    DENSE_CONFIG["model"], revision=DENSE_CONFIG["revision"],
    cache_folder=".cache/huggingface", device=str(DEVICE),
    local_files_only=True, trust_remote_code=False,
)
encoder.float().eval()
encoder.max_seq_length = DENSE_CONFIG["max_length"]
encoder.tokenizer.truncation_side = "right"
assert encoder.get_embedding_dimension() == 384
assert encoder[1].pooling_mode == "mean"
assert encoder[1].include_prompt
model_load_seconds = perf_counter() - start
print(f"Модель: {DENSE_CONFIG['model']}; revision: {DENSE_CONFIG['revision']}")
print(f"Устройство: {DEVICE}; загрузка модели: {model_load_seconds:.2f} с")
print(encoder)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 25962.44it/s]

Модель: intfloat/multilingual-e5-small; revision: 614241f622f53c4eeff9890bdc4f31cfecc418b3
Устройство: cuda; загрузка модели: 1.34 с
SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({'module_input_name': 'sentence_embedding', 'module_output_name': 'sentence_embedding'})
)

In [28]:
def synchronize_device(device):
    if device.type == "cuda":
        torch.cuda.synchronize(device)
    elif device.type == "mps":
        torch.mps.synchronize()


@torch.inference_mode()
def dense_top_k(query_vectors, document_vectors, k=50, device=DEVICE, batch_size=64):
    if k < 1 or batch_size < 1 or len(document_vectors) < 1:
        raise ValueError("Нужны положительные k, batch_size и непустой корпус")
    if query_vectors.ndim != 2 or document_vectors.ndim != 2 or query_vectors.shape[1] != document_vectors.shape[1]:
        raise ValueError("Несовместимые размерности embeddings")
    if not np.isfinite(query_vectors).all() or not np.isfinite(document_vectors).all():
        raise ValueError("Embeddings содержат NaN/inf")
    documents = torch.as_tensor(document_vectors, dtype=torch.float32, device=device)
    k = min(k, len(documents))
    positions, boundary_ties = [], 0
    for begin in range(0, len(query_vectors), batch_size):
        queries_batch = torch.as_tensor(query_vectors[begin:begin + batch_size], dtype=torch.float32, device=device)
        scores = queries_batch @ documents.T
        values, indices = torch.topk(scores, min(k + 1, len(documents)), dim=1, sorted=True)
        values, indices = values.cpu().numpy(), indices.cpu().numpy()
        for row in range(len(values)):
            if k < len(documents) and values[row, k - 1] == values[row, k]:
                # topk произвольно выбирает равные элементы: восстанавливаем всю границу.
                full = scores[row].cpu().numpy()
                threshold = values[row, k - 1]
                higher = np.flatnonzero(full > threshold)
                tied = np.flatnonzero(full == threshold)[:k - len(higher)]
                chosen = np.concatenate([higher, tied])
                chosen = chosen[np.lexsort((chosen, -full[chosen]))]
                boundary_ties += 1
            else:
                chosen = indices[row, :k]
                chosen = chosen[np.lexsort((chosen, -values[row, :k]))]
            positions.append(chosen)
    return positions, boundary_ties


# Дубли, нулевые и отрицательные оценки, k больше корпуса, разные батчи и ID mapping.
rng = np.random.default_rng(SEED)
test_documents = rng.integers(-2, 3, size=(73, 8)).astype(np.float32)
test_documents[10:65] = test_documents[0]
test_queries = np.vstack([rng.integers(-2, 3, size=(7, 8)), np.zeros((1, 8))]).astype(np.float32)
full_scores = test_queries @ test_documents.T
test_devices = [torch.device("cpu")] + ([DEVICE] if DEVICE.type != "cpu" else [])
for test_device in test_devices:
    for k in (1, 50, 100):
        expected = [np.lexsort((np.arange(len(row)), -row))[:k] for row in full_scores]
        for batch_size in (1, 3, 64):
            actual, _ = dense_top_k(test_queries, test_documents, k, test_device, batch_size)
            for found, reference in zip(actual, expected):
                np.testing.assert_array_equal(found, reference)
    empty, _ = dense_top_k(np.empty((0, 8), dtype=np.float32), test_documents, device=test_device)
    assert empty == []
    negative, _ = dense_top_k(np.ones((1, 2), dtype=np.float32), -np.ones((60, 2), dtype=np.float32), device=test_device)
    np.testing.assert_array_equal(negative[0], np.arange(50))
print("Exact top-k: проверки пройдены на", ", ".join(map(str, test_devices)))

Exact top-k: проверки пройдены на cpu, cuda

In [29]:
start = perf_counter()
dense_documents = (items.item_title_raw.fillna("") + "\n" + items.item_description_raw.fillna("")).tolist()
raw_queries = pd.read_parquet(DATA_DIR / "train.parquet", columns=["search_query"])
raw_queries["normalized"] = normalize_text(raw_queries.search_query)
raw_query_map = raw_queries.sort_values("search_query").drop_duplicates("normalized").set_index("normalized").search_query
dense_queries = raw_query_map.loc[val_texts].fillna("").tolist()
assert normalize_text(pd.Series(dense_queries)).tolist() == val_texts
del raw_queries, raw_query_map
synchronize_device(DEVICE)
corpus_embeddings = encoder.encode(
    dense_documents, prompt=DENSE_CONFIG["document_prefix"],
    batch_size=DENSE_CONFIG["batch_size"], normalize_embeddings=True, show_progress_bar=True,
)
synchronize_device(DEVICE)
dense_index_seconds = perf_counter() - start
start = perf_counter()
query_embeddings = encoder.encode(
    dense_queries, prompt=DENSE_CONFIG["query_prefix"],
    batch_size=DENSE_CONFIG["batch_size"], normalize_embeddings=True, show_progress_bar=True,
)
synchronize_device(DEVICE)
dense_query_encode_seconds = perf_counter() - start
for vectors, count in [(corpus_embeddings, len(item_ids)), (query_embeddings, len(val_texts))]:
    assert vectors.shape == (count, 384) and vectors.dtype == np.float32
    assert np.isfinite(vectors).all()
    np.testing.assert_allclose(np.linalg.norm(vectors, axis=1), 1, atol=2e-5)
start = perf_counter()
np.save(DENSE_DIR / "corpus.npy", corpus_embeddings, allow_pickle=False)
np.save(DENSE_DIR / "queries.npy", query_embeddings, allow_pickle=False)
pd.DataFrame({"row": np.arange(len(item_ids)), "item_id": item_ids}).to_csv(DENSE_DIR / "items.csv", index=False)
pd.DataFrame({"row": np.arange(len(val_texts)), "text_id": [text_ids[t] for t in val_texts]}).to_csv(DENSE_DIR / "queries.csv", index=False)
dense_metadata = {
    "config": DENSE_CONFIG, "device": str(DEVICE), "split_sha256": SPLIT_HASH,
    "corpus_sha256": experiment["corpus_sha256"], "train_sha256": experiment["train_sha256"],
    "versions": {name: importlib.metadata.version(name) for name in
                 ["sentence-transformers", "transformers", "tokenizers", "huggingface-hub", "torch"]},
    "files": {name: sha256(DENSE_DIR / name) for name in ["corpus.npy", "queries.npy", "items.csv", "queries.csv"]},
}
(DENSE_DIR / "metadata.json").write_text(json.dumps(dense_metadata, ensure_ascii=False, indent=2))
dense_save_seconds = perf_counter() - start
np.testing.assert_array_equal(pd.read_csv(DENSE_DIR / "items.csv", dtype={"item_id": str}).item_id, item_ids)
np.testing.assert_array_equal(np.load(DENSE_DIR / "corpus.npy", mmap_mode="r"), corpus_embeddings)
display(pd.Series({
    "Документы": len(corpus_embeddings), "Тексты запросов": len(query_embeddings),
    "Кодирование корпуса, с": dense_index_seconds, "Кодирование запросов, с": dense_query_encode_seconds,
    "Сохранение и контрольные суммы, с": dense_save_seconds,
    "Документов/с": len(item_ids) / dense_index_seconds,
    "Embeddings корпуса, МиБ": corpus_embeddings.nbytes / 2**20,
}, name="Значение").to_frame())

Batches:   0%|          | 0/5913 [00:00<?, ?it/s]

Batches:   0%|          | 2/5913 [00:00<07:06, 13.87it/s]

Batches:   0%|          | 5/5913 [00:00<04:58, 19.80it/s]

Batches:   0%|          | 8/5913 [00:00<04:29, 21.89it/s]

Batches:   0%|          | 11/5913 [00:00<04:16, 23.02it/s]

Batches:   0%|          | 14/5913 [00:00<04:06, 23.94it/s]

Batches:   0%|          | 17/5913 [00:00<04:02, 24.36it/s]

Batches:   0%|          | 20/5913 [00:00<04:00, 24.54it/s]

Batches:   0%|          | 23/5913 [00:00<04:00, 24.50it/s]

Batches:   0%|          | 26/5913 [00:01<03:57, 24.83it/s]

Batches:   0%|          | 29/5913 [00:01<03:56, 24.83it/s]

Batches:   1%|          | 32/5913 [00:01<03:55, 24.99it/s]

Batches:   1%|          | 35/5913 [00:01<03:55, 24.96it/s]

Batches:   1%|          | 38/5913 [00:01<03:55, 24.93it/s]

Batches:   1%|          | 41/5913 [00:01<03:55, 24.92it/s]

Batches:   1%|          | 44/5913 [00:01<03:55, 24.90it/s]

Batches:   1%|          | 47/5913 [00:01<03:56, 24.85it/s]

Batches:   1%|          | 50/5913 [00:02<03:54, 25.01it/s]

Batches:   1%|          | 53/5913 [00:02<03:54, 24.96it/s]

Batches:   1%|          | 56/5913 [00:02<03:55, 24.84it/s]

Batches:   1%|          | 59/5913 [00:02<03:54, 24.98it/s]

Batches:   1%|          | 62/5913 [00:02<03:52, 25.15it/s]

Batches:   1%|          | 65/5913 [00:02<03:50, 25.37it/s]

Batches:   1%|          | 68/5913 [00:02<03:54, 24.95it/s]

Batches:   1%|          | 71/5913 [00:02<03:54, 24.95it/s]

Batches:   1%|▏         | 74/5913 [00:03<03:54, 24.93it/s]

Batches:   1%|▏         | 77/5913 [00:03<03:53, 25.03it/s]

Batches:   1%|▏         | 80/5913 [00:03<03:53, 25.02it/s]

Batches:   1%|▏         | 83/5913 [00:03<03:52, 25.08it/s]

Batches:   1%|▏         | 86/5913 [00:03<03:50, 25.26it/s]

Batches:   2%|▏         | 89/5913 [00:03<03:48, 25.50it/s]

Batches:   2%|▏         | 92/5913 [00:03<03:46, 25.72it/s]

Batches:   2%|▏         | 95/5913 [00:03<03:48, 25.46it/s]

Batches:   2%|▏         | 98/5913 [00:03<03:48, 25.40it/s]

Batches:   2%|▏         | 101/5913 [00:04<03:47, 25.55it/s]

Batches:   2%|▏         | 104/5913 [00:04<03:46, 25.64it/s]

Batches:   2%|▏         | 107/5913 [00:04<03:44, 25.83it/s]

Batches:   2%|▏         | 110/5913 [00:04<03:43, 25.93it/s]

Batches:   2%|▏         | 113/5913 [00:04<03:44, 25.85it/s]

Batches:   2%|▏         | 116/5913 [00:04<03:43, 25.92it/s]

Batches:   2%|▏         | 119/5913 [00:04<03:45, 25.68it/s]

Batches:   2%|▏         | 122/5913 [00:04<03:44, 25.84it/s]

Batches:   2%|▏         | 125/5913 [00:05<03:42, 26.00it/s]

Batches:   2%|▏         | 128/5913 [00:05<03:41, 26.07it/s]

Batches:   2%|▏         | 131/5913 [00:05<03:41, 26.12it/s]

Batches:   2%|▏         | 134/5913 [00:05<03:40, 26.22it/s]

Batches:   2%|▏         | 137/5913 [00:05<03:39, 26.26it/s]

Batches:   2%|▏         | 140/5913 [00:05<03:40, 26.19it/s]

Batches:   2%|▏         | 143/5913 [00:05<03:40, 26.11it/s]

Batches:   2%|▏         | 146/5913 [00:05<03:40, 26.16it/s]

Batches:   3%|▎         | 149/5913 [00:05<03:39, 26.22it/s]

Batches:   3%|▎         | 152/5913 [00:06<03:39, 26.26it/s]

Batches:   3%|▎         | 155/5913 [00:06<03:38, 26.35it/s]

Batches:   3%|▎         | 158/5913 [00:06<03:38, 26.31it/s]

Batches:   3%|▎         | 161/5913 [00:06<03:41, 25.96it/s]

Batches:   3%|▎         | 164/5913 [00:06<03:41, 25.95it/s]

Batches:   3%|▎         | 167/5913 [00:06<03:40, 26.01it/s]

Batches:   3%|▎         | 170/5913 [00:06<03:39, 26.11it/s]

Batches:   3%|▎         | 173/5913 [00:06<03:38, 26.25it/s]

Batches:   3%|▎         | 176/5913 [00:06<03:38, 26.31it/s]

Batches:   3%|▎         | 179/5913 [00:07<03:37, 26.36it/s]

Batches:   3%|▎         | 182/5913 [00:07<03:39, 26.16it/s]

Batches:   3%|▎         | 185/5913 [00:07<03:38, 26.22it/s]

Batches:   3%|▎         | 188/5913 [00:07<03:37, 26.31it/s]

Batches:   3%|▎         | 191/5913 [00:07<03:37, 26.27it/s]

Batches:   3%|▎         | 194/5913 [00:07<03:37, 26.34it/s]

Batches:   3%|▎         | 197/5913 [00:07<03:37, 26.25it/s]

Batches:   3%|▎         | 200/5913 [00:07<03:36, 26.42it/s]

Batches:   3%|▎         | 203/5913 [00:07<03:39, 26.06it/s]

Batches:   3%|▎         | 206/5913 [00:08<03:39, 26.02it/s]

Batches:   4%|▎         | 209/5913 [00:08<03:39, 26.03it/s]

Batches:   4%|▎         | 212/5913 [00:08<03:38, 26.12it/s]

Batches:   4%|▎         | 215/5913 [00:08<03:36, 26.26it/s]

Batches:   4%|▎         | 218/5913 [00:08<03:36, 26.25it/s]

Batches:   4%|▎         | 221/5913 [00:08<03:36, 26.32it/s]

Batches:   4%|▍         | 224/5913 [00:08<03:36, 26.27it/s]

Batches:   4%|▍         | 227/5913 [00:08<03:35, 26.37it/s]

Batches:   4%|▍         | 230/5913 [00:09<03:35, 26.39it/s]

Batches:   4%|▍         | 233/5913 [00:09<03:35, 26.40it/s]

Batches:   4%|▍         | 236/5913 [00:09<03:35, 26.37it/s]

Batches:   4%|▍         | 239/5913 [00:09<03:34, 26.50it/s]

Batches:   4%|▍         | 242/5913 [00:09<03:36, 26.16it/s]

Batches:   4%|▍         | 245/5913 [00:09<03:35, 26.28it/s]

Batches:   4%|▍         | 248/5913 [00:09<03:35, 26.33it/s]

Batches:   4%|▍         | 251/5913 [00:09<03:35, 26.26it/s]

Batches:   4%|▍         | 254/5913 [00:09<03:34, 26.38it/s]

Batches:   4%|▍         | 257/5913 [00:10<03:34, 26.43it/s]

Batches:   4%|▍         | 260/5913 [00:10<03:32, 26.58it/s]

Batches:   4%|▍         | 263/5913 [00:10<03:33, 26.52it/s]

Batches:   4%|▍         | 266/5913 [00:10<03:32, 26.56it/s]

Batches:   5%|▍         | 269/5913 [00:10<03:32, 26.53it/s]

Batches:   5%|▍         | 272/5913 [00:10<03:31, 26.61it/s]

Batches:   5%|▍         | 275/5913 [00:10<03:32, 26.49it/s]

Batches:   5%|▍         | 278/5913 [00:10<03:32, 26.56it/s]

Batches:   5%|▍         | 281/5913 [00:10<03:31, 26.61it/s]

Batches:   5%|▍         | 284/5913 [00:11<03:33, 26.38it/s]

Batches:   5%|▍         | 287/5913 [00:11<03:33, 26.39it/s]

Batches:   5%|▍         | 290/5913 [00:11<03:32, 26.40it/s]

Batches:   5%|▍         | 293/5913 [00:11<03:45, 24.97it/s]

Batches:   5%|▌         | 296/5913 [00:11<03:41, 25.39it/s]

Batches:   5%|▌         | 299/5913 [00:11<03:37, 25.80it/s]

Batches:   5%|▌         | 302/5913 [00:11<03:34, 26.13it/s]

Batches:   5%|▌         | 305/5913 [00:11<03:32, 26.35it/s]

Batches:   5%|▌         | 308/5913 [00:11<03:31, 26.46it/s]

Batches:   5%|▌         | 311/5913 [00:12<03:31, 26.53it/s]

Batches:   5%|▌         | 314/5913 [00:12<03:30, 26.57it/s]

Batches:   5%|▌         | 317/5913 [00:12<03:29, 26.66it/s]

Batches:   5%|▌         | 320/5913 [00:12<03:29, 26.75it/s]

Batches:   5%|▌         | 323/5913 [00:12<03:29, 26.71it/s]

Batches:   6%|▌         | 326/5913 [00:12<03:30, 26.50it/s]

Batches:   6%|▌         | 329/5913 [00:12<03:30, 26.57it/s]

Batches:   6%|▌         | 332/5913 [00:12<03:29, 26.69it/s]

Batches:   6%|▌         | 335/5913 [00:12<03:29, 26.62it/s]

Batches:   6%|▌         | 338/5913 [00:13<03:28, 26.68it/s]

Batches:   6%|▌         | 341/5913 [00:13<03:29, 26.66it/s]

Batches:   6%|▌         | 344/5913 [00:13<03:29, 26.59it/s]

Batches:   6%|▌         | 347/5913 [00:13<03:28, 26.66it/s]

Batches:   6%|▌         | 350/5913 [00:13<03:28, 26.72it/s]

Batches:   6%|▌         | 353/5913 [00:13<03:27, 26.76it/s]

Batches:   6%|▌         | 356/5913 [00:13<03:26, 26.87it/s]

Batches:   6%|▌         | 359/5913 [00:13<03:26, 26.95it/s]

Batches:   6%|▌         | 362/5913 [00:13<03:25, 27.06it/s]

Batches:   6%|▌         | 365/5913 [00:14<03:25, 27.05it/s]

Batches:   6%|▌         | 368/5913 [00:14<03:26, 26.86it/s]

Batches:   6%|▋         | 371/5913 [00:14<03:26, 26.89it/s]

Batches:   6%|▋         | 374/5913 [00:14<03:26, 26.88it/s]

Batches:   6%|▋         | 377/5913 [00:14<03:25, 26.89it/s]

Batches:   6%|▋         | 380/5913 [00:14<03:26, 26.78it/s]

Batches:   6%|▋         | 383/5913 [00:14<03:26, 26.79it/s]

Batches:   7%|▋         | 386/5913 [00:14<03:26, 26.76it/s]

Batches:   7%|▋         | 389/5913 [00:15<03:26, 26.79it/s]

Batches:   7%|▋         | 392/5913 [00:15<03:25, 26.84it/s]

Batches:   7%|▋         | 395/5913 [00:15<03:25, 26.84it/s]

Batches:   7%|▋         | 398/5913 [00:15<03:25, 26.87it/s]

Batches:   7%|▋         | 401/5913 [00:15<03:24, 26.94it/s]

Batches:   7%|▋         | 404/5913 [00:15<03:23, 27.05it/s]

Batches:   7%|▋         | 407/5913 [00:15<03:24, 26.90it/s]

Batches:   7%|▋         | 410/5913 [00:15<03:30, 26.19it/s]

Batches:   7%|▋         | 413/5913 [00:15<03:29, 26.27it/s]

Batches:   7%|▋         | 416/5913 [00:16<03:29, 26.19it/s]

Batches:   7%|▋         | 419/5913 [00:16<03:30, 26.12it/s]

Batches:   7%|▋         | 422/5913 [00:16<03:31, 25.99it/s]

Batches:   7%|▋         | 425/5913 [00:16<03:31, 25.96it/s]

Batches:   7%|▋         | 428/5913 [00:16<03:30, 26.08it/s]

Batches:   7%|▋         | 431/5913 [00:16<03:28, 26.33it/s]

Batches:   7%|▋         | 434/5913 [00:16<03:28, 26.31it/s]

Batches:   7%|▋         | 437/5913 [00:16<03:28, 26.31it/s]

Batches:   7%|▋         | 440/5913 [00:16<03:29, 26.14it/s]

Batches:   7%|▋         | 443/5913 [00:17<03:29, 26.17it/s]

Batches:   8%|▊         | 446/5913 [00:17<03:30, 25.94it/s]

Batches:   8%|▊         | 449/5913 [00:17<03:30, 25.98it/s]

Batches:   8%|▊         | 452/5913 [00:17<03:30, 25.92it/s]

Batches:   8%|▊         | 455/5913 [00:17<03:30, 25.95it/s]

Batches:   8%|▊         | 458/5913 [00:17<03:28, 26.10it/s]

Batches:   8%|▊         | 461/5913 [00:17<03:29, 25.98it/s]

Batches:   8%|▊         | 464/5913 [00:17<03:28, 26.14it/s]

Batches:   8%|▊         | 467/5913 [00:17<03:28, 26.16it/s]

Batches:   8%|▊         | 470/5913 [00:18<03:28, 26.08it/s]

Batches:   8%|▊         | 473/5913 [00:18<03:29, 25.97it/s]

Batches:   8%|▊         | 476/5913 [00:18<03:30, 25.85it/s]

Batches:   8%|▊         | 479/5913 [00:18<03:30, 25.87it/s]

Batches:   8%|▊         | 482/5913 [00:18<03:27, 26.14it/s]

Batches:   8%|▊         | 485/5913 [00:18<03:26, 26.24it/s]

Batches:   8%|▊         | 488/5913 [00:18<03:27, 26.11it/s]

Batches:   8%|▊         | 491/5913 [00:18<03:30, 25.71it/s]

Batches:   8%|▊         | 494/5913 [00:19<03:30, 25.74it/s]

Batches:   8%|▊         | 497/5913 [00:19<03:30, 25.72it/s]

Batches:   8%|▊         | 500/5913 [00:19<03:29, 25.85it/s]

Batches:   9%|▊         | 503/5913 [00:19<03:27, 26.04it/s]

Batches:   9%|▊         | 506/5913 [00:19<03:28, 25.95it/s]

Batches:   9%|▊         | 509/5913 [00:19<03:27, 26.08it/s]

Batches:   9%|▊         | 512/5913 [00:19<03:28, 25.89it/s]

Batches:   9%|▊         | 515/5913 [00:19<03:27, 26.04it/s]

Batches:   9%|▉         | 518/5913 [00:19<03:26, 26.12it/s]

Batches:   9%|▉         | 521/5913 [00:20<03:27, 25.95it/s]

Batches:   9%|▉         | 524/5913 [00:20<03:28, 25.88it/s]

Batches:   9%|▉         | 527/5913 [00:20<03:26, 26.14it/s]

Batches:   9%|▉         | 530/5913 [00:20<03:24, 26.31it/s]

Batches:   9%|▉         | 533/5913 [00:20<03:28, 25.85it/s]

Batches:   9%|▉         | 536/5913 [00:20<03:27, 25.95it/s]

Batches:   9%|▉         | 539/5913 [00:20<03:26, 26.04it/s]

Batches:   9%|▉         | 542/5913 [00:20<03:23, 26.39it/s]

Batches:   9%|▉         | 545/5913 [00:20<03:22, 26.49it/s]

Batches:   9%|▉         | 548/5913 [00:21<03:23, 26.40it/s]

Batches:   9%|▉         | 551/5913 [00:21<03:23, 26.32it/s]

Batches:   9%|▉         | 554/5913 [00:21<03:22, 26.41it/s]

Batches:   9%|▉         | 557/5913 [00:21<03:23, 26.37it/s]

Batches:   9%|▉         | 560/5913 [00:21<03:23, 26.25it/s]

Batches:  10%|▉         | 563/5913 [00:21<03:22, 26.38it/s]

Batches:  10%|▉         | 566/5913 [00:21<03:23, 26.22it/s]

Batches:  10%|▉         | 569/5913 [00:21<03:23, 26.26it/s]

Batches:  10%|▉         | 572/5913 [00:22<03:27, 25.78it/s]

Batches:  10%|▉         | 575/5913 [00:22<03:24, 26.06it/s]

Batches:  10%|▉         | 578/5913 [00:22<03:24, 26.08it/s]

Batches:  10%|▉         | 581/5913 [00:22<03:23, 26.15it/s]

Batches:  10%|▉         | 584/5913 [00:22<03:22, 26.32it/s]

Batches:  10%|▉         | 587/5913 [00:22<03:22, 26.24it/s]

Batches:  10%|▉         | 590/5913 [00:22<03:22, 26.27it/s]

Batches:  10%|█         | 593/5913 [00:22<03:23, 26.17it/s]

Batches:  10%|█         | 596/5913 [00:22<03:21, 26.38it/s]

Batches:  10%|█         | 599/5913 [00:23<03:20, 26.49it/s]

Batches:  10%|█         | 602/5913 [00:23<03:20, 26.43it/s]

Batches:  10%|█         | 605/5913 [00:23<03:21, 26.37it/s]

Batches:  10%|█         | 608/5913 [00:23<03:20, 26.40it/s]

Batches:  10%|█         | 611/5913 [00:23<03:21, 26.37it/s]

Batches:  10%|█         | 614/5913 [00:23<03:22, 26.20it/s]

Batches:  10%|█         | 617/5913 [00:23<03:21, 26.24it/s]

Batches:  10%|█         | 620/5913 [00:23<03:21, 26.27it/s]

Batches:  11%|█         | 623/5913 [00:23<03:20, 26.34it/s]

Batches:  11%|█         | 626/5913 [00:24<03:20, 26.42it/s]

Batches:  11%|█         | 629/5913 [00:24<03:20, 26.41it/s]

Batches:  11%|█         | 632/5913 [00:24<03:19, 26.48it/s]

Batches:  11%|█         | 635/5913 [00:24<03:20, 26.38it/s]

Batches:  11%|█         | 638/5913 [00:24<03:20, 26.25it/s]

Batches:  11%|█         | 641/5913 [00:24<03:19, 26.44it/s]

Batches:  11%|█         | 644/5913 [00:24<03:20, 26.22it/s]

Batches:  11%|█         | 647/5913 [00:24<03:21, 26.18it/s]

Batches:  11%|█         | 650/5913 [00:24<03:19, 26.32it/s]

Batches:  11%|█         | 653/5913 [00:25<03:20, 26.22it/s]

Batches:  11%|█         | 656/5913 [00:25<03:23, 25.89it/s]

Batches:  11%|█         | 659/5913 [00:25<03:21, 26.02it/s]

Batches:  11%|█         | 662/5913 [00:25<03:19, 26.26it/s]

Batches:  11%|█         | 665/5913 [00:25<03:18, 26.45it/s]

Batches:  11%|█▏        | 668/5913 [00:25<03:18, 26.42it/s]

Batches:  11%|█▏        | 671/5913 [00:25<03:18, 26.43it/s]

Batches:  11%|█▏        | 674/5913 [00:25<03:19, 26.28it/s]

Batches:  11%|█▏        | 677/5913 [00:25<03:19, 26.22it/s]

Batches:  12%|█▏        | 680/5913 [00:26<03:18, 26.39it/s]

Batches:  12%|█▏        | 683/5913 [00:26<03:18, 26.33it/s]

Batches:  12%|█▏        | 686/5913 [00:26<03:18, 26.32it/s]

Batches:  12%|█▏        | 689/5913 [00:26<03:17, 26.46it/s]

Batches:  12%|█▏        | 692/5913 [00:26<03:17, 26.40it/s]

Batches:  12%|█▏        | 695/5913 [00:26<03:17, 26.43it/s]

Batches:  12%|█▏        | 698/5913 [00:26<03:18, 26.23it/s]

Batches:  12%|█▏        | 701/5913 [00:26<03:16, 26.56it/s]

Batches:  12%|█▏        | 704/5913 [00:27<03:14, 26.80it/s]

Batches:  12%|█▏        | 707/5913 [00:27<03:15, 26.67it/s]

Batches:  12%|█▏        | 710/5913 [00:27<03:15, 26.58it/s]

Batches:  12%|█▏        | 713/5913 [00:27<03:14, 26.69it/s]

Batches:  12%|█▏        | 716/5913 [00:27<03:16, 26.50it/s]

Batches:  12%|█▏        | 719/5913 [00:27<03:16, 26.40it/s]

Batches:  12%|█▏        | 722/5913 [00:27<03:15, 26.60it/s]

Batches:  12%|█▏        | 725/5913 [00:27<03:15, 26.47it/s]

Batches:  12%|█▏        | 728/5913 [00:27<03:16, 26.43it/s]

Batches:  12%|█▏        | 731/5913 [00:28<03:15, 26.56it/s]

Batches:  12%|█▏        | 734/5913 [00:28<03:15, 26.43it/s]

Batches:  12%|█▏        | 737/5913 [00:28<03:17, 26.14it/s]

Batches:  13%|█▎        | 740/5913 [00:28<03:18, 26.12it/s]

Batches:  13%|█▎        | 743/5913 [00:28<03:18, 26.11it/s]

Batches:  13%|█▎        | 746/5913 [00:28<03:17, 26.20it/s]

Batches:  13%|█▎        | 749/5913 [00:28<03:16, 26.23it/s]

Batches:  13%|█▎        | 752/5913 [00:28<03:16, 26.27it/s]

Batches:  13%|█▎        | 755/5913 [00:28<03:14, 26.55it/s]

Batches:  13%|█▎        | 758/5913 [00:29<03:14, 26.47it/s]

Batches:  13%|█▎        | 761/5913 [00:29<03:13, 26.56it/s]

Batches:  13%|█▎        | 764/5913 [00:29<03:14, 26.45it/s]

Batches:  13%|█▎        | 767/5913 [00:29<03:14, 26.41it/s]

Batches:  13%|█▎        | 770/5913 [00:29<03:13, 26.63it/s]

Batches:  13%|█▎        | 773/5913 [00:29<03:13, 26.52it/s]

Batches:  13%|█▎        | 776/5913 [00:29<03:15, 26.27it/s]

Batches:  13%|█▎        | 779/5913 [00:29<03:14, 26.35it/s]

Batches:  13%|█▎        | 782/5913 [00:29<03:14, 26.38it/s]

Batches:  13%|█▎        | 785/5913 [00:30<03:15, 26.28it/s]

Batches:  13%|█▎        | 788/5913 [00:30<03:13, 26.51it/s]

Batches:  13%|█▎        | 791/5913 [00:30<03:14, 26.37it/s]

Batches:  13%|█▎        | 794/5913 [00:30<03:13, 26.43it/s]

Batches:  13%|█▎        | 797/5913 [00:30<03:12, 26.57it/s]

Batches:  14%|█▎        | 800/5913 [00:30<03:13, 26.48it/s]

Batches:  14%|█▎        | 803/5913 [00:30<03:13, 26.47it/s]

Batches:  14%|█▎        | 806/5913 [00:30<03:11, 26.73it/s]

Batches:  14%|█▎        | 809/5913 [00:30<03:10, 26.80it/s]

Batches:  14%|█▎        | 812/5913 [00:31<03:11, 26.65it/s]

Batches:  14%|█▍        | 815/5913 [00:31<03:09, 26.89it/s]

Batches:  14%|█▍        | 818/5913 [00:31<03:10, 26.74it/s]

Batches:  14%|█▍        | 821/5913 [00:31<03:13, 26.37it/s]

Batches:  14%|█▍        | 824/5913 [00:31<03:12, 26.44it/s]

Batches:  14%|█▍        | 827/5913 [00:31<03:13, 26.35it/s]

Batches:  14%|█▍        | 830/5913 [00:31<03:11, 26.48it/s]

Batches:  14%|█▍        | 833/5913 [00:31<03:13, 26.32it/s]

Batches:  14%|█▍        | 836/5913 [00:32<03:13, 26.25it/s]

Batches:  14%|█▍        | 839/5913 [00:32<03:11, 26.47it/s]

Batches:  14%|█▍        | 842/5913 [00:32<03:11, 26.45it/s]

Batches:  14%|█▍        | 845/5913 [00:32<03:11, 26.43it/s]

Batches:  14%|█▍        | 848/5913 [00:32<03:10, 26.63it/s]

Batches:  14%|█▍        | 851/5913 [00:32<03:10, 26.53it/s]

Batches:  14%|█▍        | 854/5913 [00:32<03:11, 26.48it/s]

Batches:  14%|█▍        | 857/5913 [00:32<03:09, 26.66it/s]

Batches:  15%|█▍        | 860/5913 [00:32<03:08, 26.87it/s]

Batches:  15%|█▍        | 863/5913 [00:33<03:09, 26.61it/s]

Batches:  15%|█▍        | 866/5913 [00:33<03:09, 26.60it/s]

Batches:  15%|█▍        | 869/5913 [00:33<03:10, 26.47it/s]

Batches:  15%|█▍        | 872/5913 [00:33<03:10, 26.45it/s]

Batches:  15%|█▍        | 875/5913 [00:33<03:10, 26.41it/s]

Batches:  15%|█▍        | 878/5913 [00:33<03:10, 26.36it/s]

Batches:  15%|█▍        | 881/5913 [00:33<03:09, 26.54it/s]

Batches:  15%|█▍        | 884/5913 [00:33<03:09, 26.50it/s]

Batches:  15%|█▌        | 887/5913 [00:33<03:09, 26.48it/s]

Batches:  15%|█▌        | 890/5913 [00:34<03:08, 26.60it/s]

Batches:  15%|█▌        | 893/5913 [00:34<03:08, 26.62it/s]

Batches:  15%|█▌        | 896/5913 [00:34<03:08, 26.62it/s]

Batches:  15%|█▌        | 899/5913 [00:34<03:07, 26.75it/s]

Batches:  15%|█▌        | 902/5913 [00:34<03:07, 26.69it/s]

Batches:  15%|█▌        | 905/5913 [00:34<03:09, 26.40it/s]

Batches:  15%|█▌        | 908/5913 [00:34<03:09, 26.38it/s]

Batches:  15%|█▌        | 911/5913 [00:34<03:08, 26.58it/s]

Batches:  15%|█▌        | 914/5913 [00:34<03:06, 26.81it/s]

Batches:  16%|█▌        | 917/5913 [00:35<03:08, 26.54it/s]

Batches:  16%|█▌        | 920/5913 [00:35<03:07, 26.69it/s]

Batches:  16%|█▌        | 923/5913 [00:35<03:07, 26.55it/s]

Batches:  16%|█▌        | 926/5913 [00:35<03:07, 26.58it/s]

Batches:  16%|█▌        | 929/5913 [00:35<03:06, 26.74it/s]

Batches:  16%|█▌        | 932/5913 [00:35<03:06, 26.72it/s]

Batches:  16%|█▌        | 935/5913 [00:35<03:06, 26.68it/s]

Batches:  16%|█▌        | 938/5913 [00:35<03:06, 26.67it/s]

Batches:  16%|█▌        | 941/5913 [00:35<03:07, 26.51it/s]

Batches:  16%|█▌        | 944/5913 [00:36<03:08, 26.35it/s]

Batches:  16%|█▌        | 947/5913 [00:36<03:08, 26.33it/s]

Batches:  16%|█▌        | 950/5913 [00:36<03:08, 26.36it/s]

Batches:  16%|█▌        | 953/5913 [00:36<03:07, 26.52it/s]

Batches:  16%|█▌        | 956/5913 [00:36<03:05, 26.65it/s]

Batches:  16%|█▌        | 959/5913 [00:36<03:07, 26.48it/s]

Batches:  16%|█▋        | 962/5913 [00:36<03:05, 26.63it/s]

Batches:  16%|█▋        | 965/5913 [00:36<03:04, 26.82it/s]

Batches:  16%|█▋        | 968/5913 [00:36<03:03, 26.94it/s]

Batches:  16%|█▋        | 971/5913 [00:37<03:04, 26.76it/s]

Batches:  16%|█▋        | 974/5913 [00:37<03:03, 26.89it/s]

Batches:  17%|█▋        | 977/5913 [00:37<03:04, 26.71it/s]

Batches:  17%|█▋        | 980/5913 [00:37<03:05, 26.57it/s]

Batches:  17%|█▋        | 983/5913 [00:37<03:04, 26.75it/s]

Batches:  17%|█▋        | 986/5913 [00:37<03:05, 26.55it/s]

Batches:  17%|█▋        | 989/5913 [00:37<03:05, 26.55it/s]

Batches:  17%|█▋        | 992/5913 [00:37<03:03, 26.84it/s]

Batches:  17%|█▋        | 995/5913 [00:37<03:03, 26.73it/s]

Batches:  17%|█▋        | 998/5913 [00:38<03:04, 26.62it/s]

Batches:  17%|█▋        | 1001/5913 [00:38<03:05, 26.52it/s]

Batches:  17%|█▋        | 1004/5913 [00:38<03:05, 26.52it/s]

Batches:  17%|█▋        | 1007/5913 [00:38<03:04, 26.60it/s]

Batches:  17%|█▋        | 1010/5913 [00:38<03:03, 26.67it/s]

Batches:  17%|█▋        | 1013/5913 [00:38<03:04, 26.54it/s]

Batches:  17%|█▋        | 1016/5913 [00:38<03:04, 26.59it/s]

Batches:  17%|█▋        | 1019/5913 [00:38<03:02, 26.80it/s]

Batches:  17%|█▋        | 1022/5913 [00:38<03:03, 26.69it/s]

Batches:  17%|█▋        | 1025/5913 [00:39<03:03, 26.69it/s]

Batches:  17%|█▋        | 1028/5913 [00:39<03:05, 26.28it/s]

Batches:  17%|█▋        | 1031/5913 [00:39<03:05, 26.30it/s]

Batches:  17%|█▋        | 1034/5913 [00:39<03:04, 26.42it/s]

Batches:  18%|█▊        | 1037/5913 [00:39<03:04, 26.46it/s]

Batches:  18%|█▊        | 1040/5913 [00:39<03:04, 26.47it/s]

Batches:  18%|█▊        | 1043/5913 [00:39<03:03, 26.56it/s]

Batches:  18%|█▊        | 1046/5913 [00:39<03:01, 26.79it/s]

Batches:  18%|█▊        | 1049/5913 [00:40<03:02, 26.72it/s]

Batches:  18%|█▊        | 1052/5913 [00:40<03:02, 26.66it/s]

Batches:  18%|█▊        | 1055/5913 [00:40<02:59, 27.01it/s]

Batches:  18%|█▊        | 1058/5913 [00:40<03:00, 26.96it/s]

Batches:  18%|█▊        | 1061/5913 [00:40<03:01, 26.77it/s]

Batches:  18%|█▊        | 1064/5913 [00:40<03:00, 26.81it/s]

Batches:  18%|█▊        | 1067/5913 [00:40<03:02, 26.60it/s]

Batches:  18%|█▊        | 1070/5913 [00:40<03:04, 26.31it/s]

Batches:  18%|█▊        | 1073/5913 [00:40<03:02, 26.52it/s]

Batches:  18%|█▊        | 1076/5913 [00:41<03:01, 26.62it/s]

Batches:  18%|█▊        | 1079/5913 [00:41<03:01, 26.60it/s]

Batches:  18%|█▊        | 1082/5913 [00:41<02:59, 26.84it/s]

Batches:  18%|█▊        | 1085/5913 [00:41<03:00, 26.81it/s]

Batches:  18%|█▊        | 1088/5913 [00:41<03:01, 26.66it/s]

Batches:  18%|█▊        | 1091/5913 [00:41<02:59, 26.81it/s]

Batches:  19%|█▊        | 1094/5913 [00:41<02:59, 26.78it/s]

Batches:  19%|█▊        | 1097/5913 [00:41<02:59, 26.78it/s]

Batches:  19%|█▊        | 1100/5913 [00:41<03:00, 26.63it/s]

Batches:  19%|█▊        | 1103/5913 [00:42<03:01, 26.52it/s]

Batches:  19%|█▊        | 1106/5913 [00:42<03:01, 26.46it/s]

Batches:  19%|█▉        | 1109/5913 [00:42<03:01, 26.52it/s]

Batches:  19%|█▉        | 1112/5913 [00:42<03:03, 26.18it/s]

Batches:  19%|█▉        | 1115/5913 [00:42<03:02, 26.33it/s]

Batches:  19%|█▉        | 1118/5913 [00:42<03:01, 26.38it/s]

Batches:  19%|█▉        | 1121/5913 [00:42<03:01, 26.40it/s]

Batches:  19%|█▉        | 1124/5913 [00:42<03:01, 26.41it/s]

Batches:  19%|█▉        | 1127/5913 [00:42<02:58, 26.74it/s]

Batches:  19%|█▉        | 1130/5913 [00:43<02:58, 26.75it/s]

Batches:  19%|█▉        | 1133/5913 [00:43<02:59, 26.62it/s]

Batches:  19%|█▉        | 1136/5913 [00:43<02:59, 26.62it/s]

Batches:  19%|█▉        | 1139/5913 [00:43<02:59, 26.66it/s]

Batches:  19%|█▉        | 1142/5913 [00:43<02:57, 26.82it/s]

Batches:  19%|█▉        | 1145/5913 [00:43<02:57, 26.89it/s]

Batches:  19%|█▉        | 1148/5913 [00:43<02:58, 26.71it/s]

Batches:  19%|█▉        | 1151/5913 [00:43<02:59, 26.59it/s]

Batches:  20%|█▉        | 1154/5913 [00:43<03:01, 26.28it/s]

Batches:  20%|█▉        | 1157/5913 [00:44<03:00, 26.31it/s]

Batches:  20%|█▉        | 1160/5913 [00:44<02:59, 26.47it/s]

Batches:  20%|█▉        | 1163/5913 [00:44<03:00, 26.38it/s]

Batches:  20%|█▉        | 1166/5913 [00:44<03:00, 26.37it/s]

Batches:  20%|█▉        | 1169/5913 [00:44<02:58, 26.55it/s]

Batches:  20%|█▉        | 1172/5913 [00:44<02:58, 26.55it/s]

Batches:  20%|█▉        | 1175/5913 [00:44<02:59, 26.43it/s]

Batches:  20%|█▉        | 1178/5913 [00:44<02:56, 26.81it/s]

Batches:  20%|█▉        | 1181/5913 [00:44<02:55, 26.94it/s]

Batches:  20%|██        | 1184/5913 [00:45<02:56, 26.78it/s]

Batches:  20%|██        | 1187/5913 [00:45<02:55, 26.96it/s]

Batches:  20%|██        | 1190/5913 [00:45<02:54, 27.01it/s]

Batches:  20%|██        | 1193/5913 [00:45<02:57, 26.62it/s]

Batches:  20%|██        | 1196/5913 [00:45<02:59, 26.33it/s]

Batches:  20%|██        | 1199/5913 [00:45<02:59, 26.28it/s]

Batches:  20%|██        | 1202/5913 [00:45<02:58, 26.39it/s]

Batches:  20%|██        | 1205/5913 [00:45<02:57, 26.47it/s]

Batches:  20%|██        | 1208/5913 [00:45<02:57, 26.45it/s]

Batches:  20%|██        | 1211/5913 [00:46<02:56, 26.62it/s]

Batches:  21%|██        | 1214/5913 [00:46<02:56, 26.55it/s]

Batches:  21%|██        | 1217/5913 [00:46<02:58, 26.36it/s]

Batches:  21%|██        | 1220/5913 [00:46<02:56, 26.52it/s]

Batches:  21%|██        | 1223/5913 [00:46<02:57, 26.39it/s]

Batches:  21%|██        | 1226/5913 [00:46<02:58, 26.29it/s]

Batches:  21%|██        | 1229/5913 [00:46<02:58, 26.25it/s]

Batches:  21%|██        | 1232/5913 [00:46<02:56, 26.45it/s]

Batches:  21%|██        | 1235/5913 [00:47<02:58, 26.26it/s]

Batches:  21%|██        | 1238/5913 [00:47<03:00, 25.92it/s]

Batches:  21%|██        | 1241/5913 [00:47<02:58, 26.11it/s]

Batches:  21%|██        | 1244/5913 [00:47<02:57, 26.36it/s]

Batches:  21%|██        | 1247/5913 [00:47<02:57, 26.30it/s]

Batches:  21%|██        | 1250/5913 [00:47<02:57, 26.31it/s]

Batches:  21%|██        | 1253/5913 [00:47<02:56, 26.33it/s]

Batches:  21%|██        | 1256/5913 [00:47<02:56, 26.43it/s]

Batches:  21%|██▏       | 1259/5913 [00:47<02:55, 26.50it/s]

Batches:  21%|██▏       | 1262/5913 [00:48<02:55, 26.55it/s]

Batches:  21%|██▏       | 1265/5913 [00:48<02:57, 26.24it/s]

Batches:  21%|██▏       | 1268/5913 [00:48<02:57, 26.23it/s]

Batches:  21%|██▏       | 1271/5913 [00:48<02:56, 26.36it/s]

Batches:  22%|██▏       | 1274/5913 [00:48<02:55, 26.44it/s]

Batches:  22%|██▏       | 1277/5913 [00:48<02:54, 26.55it/s]

Batches:  22%|██▏       | 1280/5913 [00:48<02:55, 26.40it/s]

Batches:  22%|██▏       | 1283/5913 [00:48<02:55, 26.40it/s]

Batches:  22%|██▏       | 1286/5913 [00:48<02:53, 26.69it/s]

Batches:  22%|██▏       | 1289/5913 [00:49<02:53, 26.67it/s]

Batches:  22%|██▏       | 1292/5913 [00:49<02:54, 26.47it/s]

Batches:  22%|██▏       | 1295/5913 [00:49<02:55, 26.26it/s]

Batches:  22%|██▏       | 1298/5913 [00:49<02:57, 25.97it/s]

Batches:  22%|██▏       | 1301/5913 [00:49<02:56, 26.11it/s]

Batches:  22%|██▏       | 1304/5913 [00:49<02:57, 25.99it/s]

Batches:  22%|██▏       | 1307/5913 [00:49<02:55, 26.20it/s]

Batches:  22%|██▏       | 1310/5913 [00:49<02:55, 26.18it/s]

Batches:  22%|██▏       | 1313/5913 [00:49<02:57, 25.95it/s]

Batches:  22%|██▏       | 1316/5913 [00:50<02:55, 26.23it/s]

Batches:  22%|██▏       | 1319/5913 [00:50<02:56, 25.99it/s]

Batches:  22%|██▏       | 1322/5913 [00:50<02:56, 26.02it/s]

Batches:  22%|██▏       | 1325/5913 [00:50<02:56, 26.00it/s]

Batches:  22%|██▏       | 1328/5913 [00:50<02:55, 26.06it/s]

Batches:  23%|██▎       | 1331/5913 [00:50<02:53, 26.37it/s]

Batches:  23%|██▎       | 1334/5913 [00:50<02:54, 26.25it/s]

Batches:  23%|██▎       | 1337/5913 [00:50<02:53, 26.32it/s]

Batches:  23%|██▎       | 1340/5913 [00:51<02:53, 26.32it/s]

Batches:  23%|██▎       | 1343/5913 [00:51<02:54, 26.20it/s]

Batches:  23%|██▎       | 1346/5913 [00:51<02:54, 26.17it/s]

Batches:  23%|██▎       | 1349/5913 [00:51<02:54, 26.12it/s]

Batches:  23%|██▎       | 1352/5913 [00:51<02:53, 26.28it/s]

Batches:  23%|██▎       | 1355/5913 [00:51<02:54, 26.05it/s]

Batches:  23%|██▎       | 1358/5913 [00:51<02:55, 26.00it/s]

Batches:  23%|██▎       | 1361/5913 [00:51<02:55, 25.97it/s]

Batches:  23%|██▎       | 1364/5913 [00:51<02:55, 25.95it/s]

Batches:  23%|██▎       | 1367/5913 [00:52<02:55, 25.96it/s]

Batches:  23%|██▎       | 1370/5913 [00:52<02:55, 25.81it/s]

Batches:  23%|██▎       | 1373/5913 [00:52<02:54, 25.97it/s]

Batches:  23%|██▎       | 1376/5913 [00:52<02:54, 26.06it/s]

Batches:  23%|██▎       | 1379/5913 [00:52<02:54, 25.98it/s]

Batches:  23%|██▎       | 1382/5913 [00:52<02:54, 25.95it/s]

Batches:  23%|██▎       | 1385/5913 [00:52<02:54, 25.90it/s]

Batches:  23%|██▎       | 1388/5913 [00:52<02:53, 26.11it/s]

Batches:  24%|██▎       | 1391/5913 [00:52<02:52, 26.20it/s]

Batches:  24%|██▎       | 1394/5913 [00:53<02:53, 26.09it/s]

Batches:  24%|██▎       | 1397/5913 [00:53<02:53, 26.03it/s]

Batches:  24%|██▎       | 1400/5913 [00:53<02:55, 25.70it/s]

Batches:  24%|██▎       | 1403/5913 [00:53<02:53, 25.95it/s]

Batches:  24%|██▍       | 1406/5913 [00:53<02:54, 25.80it/s]

Batches:  24%|██▍       | 1409/5913 [00:53<02:54, 25.85it/s]

Batches:  24%|██▍       | 1412/5913 [00:53<02:54, 25.75it/s]

Batches:  24%|██▍       | 1415/5913 [00:53<02:54, 25.84it/s]

Batches:  24%|██▍       | 1418/5913 [00:54<02:54, 25.79it/s]

Batches:  24%|██▍       | 1421/5913 [00:54<02:53, 25.94it/s]

Batches:  24%|██▍       | 1424/5913 [00:54<02:52, 26.04it/s]

Batches:  24%|██▍       | 1427/5913 [00:54<02:52, 26.04it/s]

Batches:  24%|██▍       | 1430/5913 [00:54<02:51, 26.12it/s]

Batches:  24%|██▍       | 1433/5913 [00:54<02:51, 26.07it/s]

Batches:  24%|██▍       | 1436/5913 [00:54<02:51, 26.12it/s]

Batches:  24%|██▍       | 1439/5913 [00:54<02:50, 26.22it/s]

Batches:  24%|██▍       | 1442/5913 [00:54<02:50, 26.24it/s]

Batches:  24%|██▍       | 1445/5913 [00:55<02:50, 26.28it/s]

Batches:  24%|██▍       | 1448/5913 [00:55<02:50, 26.19it/s]

Batches:  25%|██▍       | 1451/5913 [00:55<02:51, 26.03it/s]

Batches:  25%|██▍       | 1454/5913 [00:55<02:51, 25.95it/s]

Batches:  25%|██▍       | 1457/5913 [00:55<02:51, 26.01it/s]

Batches:  25%|██▍       | 1460/5913 [00:55<02:51, 26.01it/s]

Batches:  25%|██▍       | 1463/5913 [00:55<02:52, 25.82it/s]

Batches:  25%|██▍       | 1466/5913 [00:55<02:51, 25.92it/s]

Batches:  25%|██▍       | 1469/5913 [00:55<02:51, 25.92it/s]

Batches:  25%|██▍       | 1472/5913 [00:56<02:52, 25.81it/s]

Batches:  25%|██▍       | 1475/5913 [00:56<02:51, 25.91it/s]

Batches:  25%|██▍       | 1478/5913 [00:56<02:51, 25.85it/s]

Batches:  25%|██▌       | 1481/5913 [00:56<02:51, 25.87it/s]

Batches:  25%|██▌       | 1484/5913 [00:56<02:51, 25.82it/s]

Batches:  25%|██▌       | 1487/5913 [00:56<02:50, 25.96it/s]

Batches:  25%|██▌       | 1490/5913 [00:56<02:50, 25.94it/s]

Batches:  25%|██▌       | 1493/5913 [00:56<02:49, 26.15it/s]

Batches:  25%|██▌       | 1496/5913 [00:57<02:47, 26.33it/s]

Batches:  25%|██▌       | 1499/5913 [00:57<02:48, 26.12it/s]

Batches:  25%|██▌       | 1502/5913 [00:57<02:48, 26.15it/s]

Batches:  25%|██▌       | 1505/5913 [00:57<02:49, 26.03it/s]

Batches:  26%|██▌       | 1508/5913 [00:57<02:49, 26.03it/s]

Batches:  26%|██▌       | 1511/5913 [00:57<02:47, 26.23it/s]

Batches:  26%|██▌       | 1514/5913 [00:57<02:48, 26.18it/s]

Batches:  26%|██▌       | 1517/5913 [00:57<02:47, 26.21it/s]

Batches:  26%|██▌       | 1520/5913 [00:57<02:48, 26.11it/s]

Batches:  26%|██▌       | 1523/5913 [00:58<02:49, 25.89it/s]

Batches:  26%|██▌       | 1526/5913 [00:58<02:48, 26.01it/s]

Batches:  26%|██▌       | 1529/5913 [00:58<02:49, 25.92it/s]

Batches:  26%|██▌       | 1532/5913 [00:58<02:48, 25.99it/s]

Batches:  26%|██▌       | 1535/5913 [00:58<02:49, 25.89it/s]

Batches:  26%|██▌       | 1538/5913 [00:58<02:48, 26.03it/s]

Batches:  26%|██▌       | 1541/5913 [00:58<02:48, 25.96it/s]

Batches:  26%|██▌       | 1544/5913 [00:58<02:48, 26.00it/s]

Batches:  26%|██▌       | 1547/5913 [00:58<02:46, 26.21it/s]

Batches:  26%|██▌       | 1550/5913 [00:59<02:46, 26.16it/s]

Batches:  26%|██▋       | 1553/5913 [00:59<02:46, 26.15it/s]

Batches:  26%|██▋       | 1556/5913 [00:59<02:47, 26.06it/s]

Batches:  26%|██▋       | 1559/5913 [00:59<02:47, 25.97it/s]

Batches:  26%|██▋       | 1562/5913 [00:59<02:47, 26.00it/s]

Batches:  26%|██▋       | 1565/5913 [00:59<02:48, 25.80it/s]

Batches:  27%|██▋       | 1568/5913 [00:59<02:47, 25.97it/s]

Batches:  27%|██▋       | 1571/5913 [00:59<02:47, 25.95it/s]

Batches:  27%|██▋       | 1574/5913 [01:00<02:46, 26.05it/s]

Batches:  27%|██▋       | 1577/5913 [01:00<02:45, 26.13it/s]

Batches:  27%|██▋       | 1580/5913 [01:00<02:46, 26.05it/s]

Batches:  27%|██▋       | 1583/5913 [01:00<02:45, 26.20it/s]

Batches:  27%|██▋       | 1586/5913 [01:00<02:46, 25.98it/s]

Batches:  27%|██▋       | 1589/5913 [01:00<02:45, 26.07it/s]

Batches:  27%|██▋       | 1592/5913 [01:00<02:46, 26.01it/s]

Batches:  27%|██▋       | 1595/5913 [01:00<02:46, 25.99it/s]

Batches:  27%|██▋       | 1598/5913 [01:00<02:44, 26.26it/s]

Batches:  27%|██▋       | 1601/5913 [01:01<02:47, 25.71it/s]

Batches:  27%|██▋       | 1604/5913 [01:01<02:50, 25.27it/s]

Batches:  27%|██▋       | 1607/5913 [01:01<02:51, 25.17it/s]

Batches:  27%|██▋       | 1610/5913 [01:01<02:50, 25.25it/s]

Batches:  27%|██▋       | 1613/5913 [01:01<02:49, 25.42it/s]

Batches:  27%|██▋       | 1616/5913 [01:01<02:48, 25.56it/s]

Batches:  27%|██▋       | 1619/5913 [01:01<02:47, 25.65it/s]

Batches:  27%|██▋       | 1622/5913 [01:01<02:46, 25.78it/s]

Batches:  27%|██▋       | 1625/5913 [01:01<02:46, 25.74it/s]

Batches:  28%|██▊       | 1628/5913 [01:02<02:45, 25.83it/s]

Batches:  28%|██▊       | 1631/5913 [01:02<02:46, 25.79it/s]

Batches:  28%|██▊       | 1634/5913 [01:02<02:45, 25.83it/s]

Batches:  28%|██▊       | 1637/5913 [01:02<02:45, 25.90it/s]

Batches:  28%|██▊       | 1640/5913 [01:02<02:45, 25.85it/s]

Batches:  28%|██▊       | 1643/5913 [01:02<02:44, 25.89it/s]

Batches:  28%|██▊       | 1646/5913 [01:02<02:46, 25.68it/s]

Batches:  28%|██▊       | 1649/5913 [01:02<02:43, 26.05it/s]

Batches:  28%|██▊       | 1652/5913 [01:03<02:44, 25.93it/s]

Batches:  28%|██▊       | 1655/5913 [01:03<02:44, 25.95it/s]

Batches:  28%|██▊       | 1658/5913 [01:03<02:43, 25.98it/s]

Batches:  28%|██▊       | 1661/5913 [01:03<02:43, 25.93it/s]

Batches:  28%|██▊       | 1664/5913 [01:03<02:43, 25.99it/s]

Batches:  28%|██▊       | 1667/5913 [01:03<02:43, 25.93it/s]

Batches:  28%|██▊       | 1670/5913 [01:03<02:43, 26.01it/s]

Batches:  28%|██▊       | 1673/5913 [01:03<02:43, 25.98it/s]

Batches:  28%|██▊       | 1676/5913 [01:03<02:42, 26.07it/s]

Batches:  28%|██▊       | 1679/5913 [01:04<02:41, 26.15it/s]

Batches:  28%|██▊       | 1682/5913 [01:04<02:42, 26.01it/s]

Batches:  28%|██▊       | 1685/5913 [01:04<02:44, 25.76it/s]

Batches:  29%|██▊       | 1688/5913 [01:04<02:43, 25.86it/s]

Batches:  29%|██▊       | 1691/5913 [01:04<02:43, 25.88it/s]

Batches:  29%|██▊       | 1694/5913 [01:04<02:41, 26.14it/s]

Batches:  29%|██▊       | 1697/5913 [01:04<02:41, 26.08it/s]

Batches:  29%|██▉       | 1700/5913 [01:04<02:41, 26.08it/s]

Batches:  29%|██▉       | 1703/5913 [01:04<02:41, 26.14it/s]

Batches:  29%|██▉       | 1706/5913 [01:05<02:41, 26.01it/s]

Batches:  29%|██▉       | 1709/5913 [01:05<02:40, 26.18it/s]

Batches:  29%|██▉       | 1712/5913 [01:05<02:41, 26.04it/s]

Batches:  29%|██▉       | 1715/5913 [01:05<02:40, 26.22it/s]

Batches:  29%|██▉       | 1718/5913 [01:05<02:40, 26.09it/s]

Batches:  29%|██▉       | 1721/5913 [01:05<02:40, 26.08it/s]

Batches:  29%|██▉       | 1724/5913 [01:05<02:39, 26.20it/s]

Batches:  29%|██▉       | 1727/5913 [01:05<02:41, 25.97it/s]

Batches:  29%|██▉       | 1730/5913 [01:06<02:39, 26.17it/s]

Batches:  29%|██▉       | 1733/5913 [01:06<02:40, 26.02it/s]

Batches:  29%|██▉       | 1736/5913 [01:06<02:40, 25.99it/s]

Batches:  29%|██▉       | 1739/5913 [01:06<02:40, 25.96it/s]

Batches:  29%|██▉       | 1742/5913 [01:06<02:40, 25.96it/s]

Batches:  30%|██▉       | 1745/5913 [01:06<02:40, 25.98it/s]

Batches:  30%|██▉       | 1748/5913 [01:06<02:40, 25.98it/s]

Batches:  30%|██▉       | 1751/5913 [01:06<02:39, 26.09it/s]

Batches:  30%|██▉       | 1754/5913 [01:06<02:37, 26.34it/s]

Batches:  30%|██▉       | 1757/5913 [01:07<02:38, 26.20it/s]

Batches:  30%|██▉       | 1760/5913 [01:07<02:38, 26.28it/s]

Batches:  30%|██▉       | 1763/5913 [01:07<02:38, 26.13it/s]

Batches:  30%|██▉       | 1766/5913 [01:07<02:40, 25.81it/s]

Batches:  30%|██▉       | 1769/5913 [01:07<02:40, 25.90it/s]

Batches:  30%|██▉       | 1772/5913 [01:07<02:39, 25.98it/s]

Batches:  30%|███       | 1775/5913 [01:07<02:38, 26.04it/s]

Batches:  30%|███       | 1778/5913 [01:07<02:39, 25.99it/s]

Batches:  30%|███       | 1781/5913 [01:07<02:38, 26.05it/s]

Batches:  30%|███       | 1784/5913 [01:08<02:38, 26.02it/s]

Batches:  30%|███       | 1787/5913 [01:08<02:37, 26.18it/s]

Batches:  30%|███       | 1790/5913 [01:08<02:37, 26.16it/s]

Batches:  30%|███       | 1793/5913 [01:08<02:37, 26.16it/s]

Batches:  30%|███       | 1796/5913 [01:08<02:37, 26.21it/s]

Batches:  30%|███       | 1799/5913 [01:08<02:37, 26.14it/s]

Batches:  30%|███       | 1802/5913 [01:08<02:37, 26.13it/s]

Batches:  31%|███       | 1805/5913 [01:08<02:35, 26.44it/s]

Batches:  31%|███       | 1808/5913 [01:09<02:37, 26.14it/s]

Batches:  31%|███       | 1811/5913 [01:09<02:37, 26.11it/s]

Batches:  31%|███       | 1814/5913 [01:09<02:37, 25.98it/s]

Batches:  31%|███       | 1817/5913 [01:09<02:38, 25.91it/s]

Batches:  31%|███       | 1820/5913 [01:09<02:38, 25.88it/s]

Batches:  31%|███       | 1823/5913 [01:09<02:36, 26.07it/s]

Batches:  31%|███       | 1826/5913 [01:09<02:37, 26.00it/s]

Batches:  31%|███       | 1829/5913 [01:09<02:37, 25.90it/s]

Batches:  31%|███       | 1832/5913 [01:09<02:36, 26.13it/s]

Batches:  31%|███       | 1835/5913 [01:10<02:36, 26.07it/s]

Batches:  31%|███       | 1838/5913 [01:10<02:36, 26.11it/s]

Batches:  31%|███       | 1841/5913 [01:10<02:36, 26.10it/s]

Batches:  31%|███       | 1844/5913 [01:10<02:36, 26.05it/s]

Batches:  31%|███       | 1847/5913 [01:10<02:35, 26.15it/s]

Batches:  31%|███▏      | 1850/5913 [01:10<02:37, 25.81it/s]

Batches:  31%|███▏      | 1853/5913 [01:10<02:35, 26.12it/s]

Batches:  31%|███▏      | 1856/5913 [01:10<02:34, 26.29it/s]

Batches:  31%|███▏      | 1859/5913 [01:10<02:32, 26.52it/s]

Batches:  31%|███▏      | 1862/5913 [01:11<02:33, 26.33it/s]

Batches:  32%|███▏      | 1865/5913 [01:11<02:34, 26.14it/s]

Batches:  32%|███▏      | 1868/5913 [01:11<02:34, 26.12it/s]

Batches:  32%|███▏      | 1871/5913 [01:11<02:35, 25.98it/s]

Batches:  32%|███▏      | 1874/5913 [01:11<02:34, 26.13it/s]

Batches:  32%|███▏      | 1877/5913 [01:11<02:33, 26.23it/s]

Batches:  32%|███▏      | 1880/5913 [01:11<02:34, 26.14it/s]

Batches:  32%|███▏      | 1883/5913 [01:11<02:33, 26.25it/s]

Batches:  32%|███▏      | 1886/5913 [01:12<02:34, 26.11it/s]

Batches:  32%|███▏      | 1889/5913 [01:12<02:36, 25.78it/s]

Batches:  32%|███▏      | 1892/5913 [01:12<02:36, 25.75it/s]

Batches:  32%|███▏      | 1895/5913 [01:12<02:35, 25.88it/s]

Batches:  32%|███▏      | 1898/5913 [01:12<02:34, 25.94it/s]

Batches:  32%|███▏      | 1901/5913 [01:12<02:34, 25.92it/s]

Batches:  32%|███▏      | 1904/5913 [01:12<02:33, 26.08it/s]

Batches:  32%|███▏      | 1907/5913 [01:12<02:33, 26.04it/s]

Batches:  32%|███▏      | 1910/5913 [01:12<02:32, 26.31it/s]

Batches:  32%|███▏      | 1913/5913 [01:13<02:31, 26.33it/s]

Batches:  32%|███▏      | 1916/5913 [01:13<02:30, 26.48it/s]

Batches:  32%|███▏      | 1919/5913 [01:13<02:29, 26.78it/s]

Batches:  33%|███▎      | 1922/5913 [01:13<02:28, 26.95it/s]

Batches:  33%|███▎      | 1925/5913 [01:13<02:27, 27.04it/s]

Batches:  33%|███▎      | 1928/5913 [01:13<02:27, 27.10it/s]

Batches:  33%|███▎      | 1931/5913 [01:13<02:27, 26.92it/s]

Batches:  33%|███▎      | 1934/5913 [01:13<02:27, 27.01it/s]

Batches:  33%|███▎      | 1937/5913 [01:13<02:26, 27.12it/s]

Batches:  33%|███▎      | 1940/5913 [01:14<02:25, 27.26it/s]

Batches:  33%|███▎      | 1943/5913 [01:14<02:25, 27.20it/s]

Batches:  33%|███▎      | 1946/5913 [01:14<02:25, 27.25it/s]

Batches:  33%|███▎      | 1949/5913 [01:14<02:25, 27.19it/s]

Batches:  33%|███▎      | 1952/5913 [01:14<02:25, 27.20it/s]

Batches:  33%|███▎      | 1955/5913 [01:14<02:25, 27.27it/s]

Batches:  33%|███▎      | 1958/5913 [01:14<02:25, 27.27it/s]

Batches:  33%|███▎      | 1961/5913 [01:14<02:24, 27.30it/s]

Batches:  33%|███▎      | 1964/5913 [01:14<02:24, 27.30it/s]

Batches:  33%|███▎      | 1967/5913 [01:15<02:24, 27.32it/s]

Batches:  33%|███▎      | 1970/5913 [01:15<02:24, 27.23it/s]

Batches:  33%|███▎      | 1973/5913 [01:15<02:26, 26.97it/s]

Batches:  33%|███▎      | 1976/5913 [01:15<02:25, 27.05it/s]

Batches:  33%|███▎      | 1979/5913 [01:15<02:24, 27.15it/s]

Batches:  34%|███▎      | 1982/5913 [01:15<02:24, 27.25it/s]

Batches:  34%|███▎      | 1985/5913 [01:15<02:23, 27.34it/s]

Batches:  34%|███▎      | 1988/5913 [01:15<02:23, 27.41it/s]

Batches:  34%|███▎      | 1991/5913 [01:15<02:22, 27.44it/s]

Batches:  34%|███▎      | 1994/5913 [01:16<02:23, 27.40it/s]

Batches:  34%|███▍      | 1997/5913 [01:16<02:23, 27.27it/s]

Batches:  34%|███▍      | 2000/5913 [01:16<02:23, 27.22it/s]

Batches:  34%|███▍      | 2003/5913 [01:16<02:23, 27.27it/s]

Batches:  34%|███▍      | 2006/5913 [01:16<02:22, 27.33it/s]

Batches:  34%|███▍      | 2009/5913 [01:16<02:22, 27.30it/s]

Batches:  34%|███▍      | 2012/5913 [01:16<02:23, 27.24it/s]

Batches:  34%|███▍      | 2015/5913 [01:16<02:23, 27.14it/s]

Batches:  34%|███▍      | 2018/5913 [01:16<02:23, 27.05it/s]

Batches:  34%|███▍      | 2021/5913 [01:17<02:23, 27.12it/s]

Batches:  34%|███▍      | 2024/5913 [01:17<02:23, 27.17it/s]

Batches:  34%|███▍      | 2027/5913 [01:17<02:22, 27.27it/s]

Batches:  34%|███▍      | 2030/5913 [01:17<02:22, 27.30it/s]

Batches:  34%|███▍      | 2033/5913 [01:17<02:22, 27.24it/s]

Batches:  34%|███▍      | 2036/5913 [01:17<02:21, 27.31it/s]

Batches:  34%|███▍      | 2039/5913 [01:17<02:22, 27.19it/s]

Batches:  35%|███▍      | 2042/5913 [01:17<02:21, 27.27it/s]

Batches:  35%|███▍      | 2045/5913 [01:17<02:22, 27.24it/s]

Batches:  35%|███▍      | 2048/5913 [01:18<02:21, 27.26it/s]

Batches:  35%|███▍      | 2051/5913 [01:18<02:21, 27.23it/s]

Batches:  35%|███▍      | 2054/5913 [01:18<02:21, 27.31it/s]

Batches:  35%|███▍      | 2057/5913 [01:18<02:20, 27.38it/s]

Batches:  35%|███▍      | 2060/5913 [01:18<02:21, 27.18it/s]

Batches:  35%|███▍      | 2063/5913 [01:18<02:21, 27.24it/s]

Batches:  35%|███▍      | 2066/5913 [01:18<02:20, 27.32it/s]

Batches:  35%|███▍      | 2069/5913 [01:18<02:20, 27.28it/s]

Batches:  35%|███▌      | 2072/5913 [01:18<02:20, 27.28it/s]

Batches:  35%|███▌      | 2075/5913 [01:18<02:20, 27.27it/s]

Batches:  35%|███▌      | 2078/5913 [01:19<02:20, 27.23it/s]

Batches:  35%|███▌      | 2081/5913 [01:19<02:20, 27.20it/s]

Batches:  35%|███▌      | 2084/5913 [01:19<02:20, 27.24it/s]

Batches:  35%|███▌      | 2087/5913 [01:19<02:20, 27.29it/s]

Batches:  35%|███▌      | 2090/5913 [01:19<02:20, 27.30it/s]

Batches:  35%|███▌      | 2093/5913 [01:19<02:19, 27.40it/s]

Batches:  35%|███▌      | 2096/5913 [01:19<02:19, 27.43it/s]

Batches:  35%|███▌      | 2099/5913 [01:19<02:18, 27.53it/s]

Batches:  36%|███▌      | 2102/5913 [01:19<02:19, 27.32it/s]

Batches:  36%|███▌      | 2105/5913 [01:20<02:19, 27.27it/s]

Batches:  36%|███▌      | 2108/5913 [01:20<02:19, 27.20it/s]

Batches:  36%|███▌      | 2111/5913 [01:20<02:19, 27.26it/s]

Batches:  36%|███▌      | 2114/5913 [01:20<02:18, 27.37it/s]

Batches:  36%|███▌      | 2117/5913 [01:20<02:18, 27.34it/s]

Batches:  36%|███▌      | 2120/5913 [01:20<02:18, 27.42it/s]

Batches:  36%|███▌      | 2123/5913 [01:20<02:18, 27.30it/s]

Batches:  36%|███▌      | 2126/5913 [01:20<02:18, 27.31it/s]

Batches:  36%|███▌      | 2129/5913 [01:20<02:18, 27.30it/s]

Batches:  36%|███▌      | 2132/5913 [01:21<02:17, 27.42it/s]

Batches:  36%|███▌      | 2135/5913 [01:21<02:18, 27.34it/s]

Batches:  36%|███▌      | 2138/5913 [01:21<02:17, 27.41it/s]

Batches:  36%|███▌      | 2141/5913 [01:21<02:17, 27.46it/s]

Batches:  36%|███▋      | 2144/5913 [01:21<02:18, 27.24it/s]

Batches:  36%|███▋      | 2147/5913 [01:21<02:18, 27.29it/s]

Batches:  36%|███▋      | 2150/5913 [01:21<02:17, 27.43it/s]

Batches:  36%|███▋      | 2153/5913 [01:21<02:16, 27.48it/s]

Batches:  36%|███▋      | 2156/5913 [01:21<02:16, 27.54it/s]

Batches:  37%|███▋      | 2159/5913 [01:22<02:16, 27.54it/s]

Batches:  37%|███▋      | 2162/5913 [01:22<02:16, 27.53it/s]

Batches:  37%|███▋      | 2165/5913 [01:22<02:16, 27.40it/s]

Batches:  37%|███▋      | 2168/5913 [01:22<02:16, 27.40it/s]

Batches:  37%|███▋      | 2171/5913 [01:22<02:16, 27.42it/s]

Batches:  37%|███▋      | 2174/5913 [01:22<02:16, 27.48it/s]

Batches:  37%|███▋      | 2177/5913 [01:22<02:15, 27.51it/s]

Batches:  37%|███▋      | 2180/5913 [01:22<02:15, 27.54it/s]

Batches:  37%|███▋      | 2183/5913 [01:22<02:15, 27.48it/s]

Batches:  37%|███▋      | 2186/5913 [01:23<02:15, 27.52it/s]

Batches:  37%|███▋      | 2189/5913 [01:23<02:16, 27.32it/s]

Batches:  37%|███▋      | 2192/5913 [01:23<02:16, 27.35it/s]

Batches:  37%|███▋      | 2195/5913 [01:23<02:15, 27.39it/s]

Batches:  37%|███▋      | 2198/5913 [01:23<02:15, 27.48it/s]

Batches:  37%|███▋      | 2201/5913 [01:23<02:15, 27.49it/s]

Batches:  37%|███▋      | 2204/5913 [01:23<02:15, 27.33it/s]

Batches:  37%|███▋      | 2207/5913 [01:23<02:15, 27.34it/s]

Batches:  37%|███▋      | 2210/5913 [01:23<02:15, 27.36it/s]

Batches:  37%|███▋      | 2213/5913 [01:24<02:14, 27.46it/s]

Batches:  37%|███▋      | 2216/5913 [01:24<02:14, 27.52it/s]

Batches:  38%|███▊      | 2219/5913 [01:24<02:14, 27.52it/s]

Batches:  38%|███▊      | 2222/5913 [01:24<02:14, 27.49it/s]

Batches:  38%|███▊      | 2225/5913 [01:24<02:14, 27.42it/s]

Batches:  38%|███▊      | 2228/5913 [01:24<02:13, 27.50it/s]

Batches:  38%|███▊      | 2231/5913 [01:24<02:14, 27.35it/s]

Batches:  38%|███▊      | 2234/5913 [01:24<02:14, 27.38it/s]

Batches:  38%|███▊      | 2237/5913 [01:24<02:13, 27.54it/s]

Batches:  38%|███▊      | 2240/5913 [01:25<02:13, 27.59it/s]

Batches:  38%|███▊      | 2243/5913 [01:25<02:12, 27.64it/s]

Batches:  38%|███▊      | 2246/5913 [01:25<02:13, 27.55it/s]

Batches:  38%|███▊      | 2249/5913 [01:25<02:13, 27.41it/s]

Batches:  38%|███▊      | 2252/5913 [01:25<02:13, 27.36it/s]

Batches:  38%|███▊      | 2255/5913 [01:25<02:13, 27.34it/s]

Batches:  38%|███▊      | 2258/5913 [01:25<02:13, 27.45it/s]

Batches:  38%|███▊      | 2261/5913 [01:25<02:12, 27.59it/s]

Batches:  38%|███▊      | 2264/5913 [01:25<02:11, 27.71it/s]

Batches:  38%|███▊      | 2267/5913 [01:25<02:11, 27.69it/s]

Batches:  38%|███▊      | 2270/5913 [01:26<02:11, 27.79it/s]

Batches:  38%|███▊      | 2273/5913 [01:26<02:12, 27.43it/s]

Batches:  38%|███▊      | 2276/5913 [01:26<02:12, 27.44it/s]

Batches:  39%|███▊      | 2279/5913 [01:26<02:12, 27.52it/s]

Batches:  39%|███▊      | 2282/5913 [01:26<02:11, 27.56it/s]

Batches:  39%|███▊      | 2285/5913 [01:26<02:10, 27.78it/s]

Batches:  39%|███▊      | 2288/5913 [01:26<02:10, 27.76it/s]

Batches:  39%|███▊      | 2291/5913 [01:26<02:11, 27.62it/s]

Batches:  39%|███▉      | 2294/5913 [01:26<02:11, 27.61it/s]

Batches:  39%|███▉      | 2297/5913 [01:27<02:10, 27.65it/s]

Batches:  39%|███▉      | 2300/5913 [01:27<02:10, 27.74it/s]

Batches:  39%|███▉      | 2303/5913 [01:27<02:10, 27.66it/s]

Batches:  39%|███▉      | 2306/5913 [01:27<02:10, 27.66it/s]

Batches:  39%|███▉      | 2309/5913 [01:27<02:09, 27.78it/s]

Batches:  39%|███▉      | 2312/5913 [01:27<02:07, 28.19it/s]

Batches:  39%|███▉      | 2315/5913 [01:27<02:08, 28.04it/s]

Batches:  39%|███▉      | 2318/5913 [01:27<02:09, 27.82it/s]

Batches:  39%|███▉      | 2321/5913 [01:27<02:09, 27.83it/s]

Batches:  39%|███▉      | 2324/5913 [01:28<02:08, 27.83it/s]

Batches:  39%|███▉      | 2327/5913 [01:28<02:08, 27.89it/s]

Batches:  39%|███▉      | 2330/5913 [01:28<02:09, 27.76it/s]

Batches:  39%|███▉      | 2333/5913 [01:28<02:09, 27.67it/s]

Batches:  40%|███▉      | 2336/5913 [01:28<02:08, 27.84it/s]

Batches:  40%|███▉      | 2339/5913 [01:28<02:08, 27.76it/s]

Batches:  40%|███▉      | 2342/5913 [01:28<02:08, 27.76it/s]

Batches:  40%|███▉      | 2345/5913 [01:28<02:08, 27.85it/s]

Batches:  40%|███▉      | 2348/5913 [01:28<02:07, 28.01it/s]

Batches:  40%|███▉      | 2351/5913 [01:29<02:07, 27.93it/s]

Batches:  40%|███▉      | 2354/5913 [01:29<02:08, 27.78it/s]

Batches:  40%|███▉      | 2357/5913 [01:29<02:08, 27.74it/s]

Batches:  40%|███▉      | 2360/5913 [01:29<02:09, 27.49it/s]

Batches:  40%|███▉      | 2363/5913 [01:29<02:08, 27.53it/s]

Batches:  40%|████      | 2366/5913 [01:29<02:08, 27.55it/s]

Batches:  40%|████      | 2369/5913 [01:29<02:07, 27.77it/s]

Batches:  40%|████      | 2372/5913 [01:29<02:07, 27.82it/s]

Batches:  40%|████      | 2375/5913 [01:29<02:07, 27.73it/s]

Batches:  40%|████      | 2378/5913 [01:29<02:07, 27.75it/s]

Batches:  40%|████      | 2381/5913 [01:30<02:06, 27.90it/s]

Batches:  40%|████      | 2384/5913 [01:30<02:06, 27.96it/s]

Batches:  40%|████      | 2387/5913 [01:30<02:05, 28.06it/s]

Batches:  40%|████      | 2390/5913 [01:30<02:04, 28.20it/s]

Batches:  40%|████      | 2393/5913 [01:30<02:04, 28.17it/s]

Batches:  41%|████      | 2396/5913 [01:30<02:04, 28.24it/s]

Batches:  41%|████      | 2399/5913 [01:30<02:04, 28.17it/s]

Batches:  41%|████      | 2402/5913 [01:30<02:04, 28.15it/s]

Batches:  41%|████      | 2406/5913 [01:30<02:02, 28.59it/s]

Batches:  41%|████      | 2409/5913 [01:31<02:03, 28.31it/s]

Batches:  41%|████      | 2412/5913 [01:31<02:04, 28.14it/s]

Batches:  41%|████      | 2415/5913 [01:31<02:04, 28.01it/s]

Batches:  41%|████      | 2418/5913 [01:31<02:03, 28.39it/s]

Batches:  41%|████      | 2421/5913 [01:31<02:02, 28.43it/s]

Batches:  41%|████      | 2424/5913 [01:31<02:03, 28.31it/s]

Batches:  41%|████      | 2427/5913 [01:31<02:02, 28.43it/s]

Batches:  41%|████      | 2430/5913 [01:31<02:02, 28.35it/s]

Batches:  41%|████      | 2433/5913 [01:31<02:03, 28.27it/s]

Batches:  41%|████      | 2436/5913 [01:32<02:02, 28.36it/s]

Batches:  41%|████      | 2439/5913 [01:32<02:03, 28.18it/s]

Batches:  41%|████▏     | 2442/5913 [01:32<02:03, 28.06it/s]

Batches:  41%|████▏     | 2445/5913 [01:32<02:03, 28.02it/s]

Batches:  41%|████▏     | 2448/5913 [01:32<02:04, 27.79it/s]

Batches:  41%|████▏     | 2451/5913 [01:32<02:04, 27.90it/s]

Batches:  42%|████▏     | 2454/5913 [01:32<02:03, 28.07it/s]

Batches:  42%|████▏     | 2457/5913 [01:32<02:02, 28.12it/s]

Batches:  42%|████▏     | 2460/5913 [01:32<02:02, 28.15it/s]

Batches:  42%|████▏     | 2463/5913 [01:33<02:02, 28.23it/s]

Batches:  42%|████▏     | 2466/5913 [01:33<02:00, 28.60it/s]

Batches:  42%|████▏     | 2469/5913 [01:33<02:00, 28.52it/s]

Batches:  42%|████▏     | 2472/5913 [01:33<02:00, 28.55it/s]

Batches:  42%|████▏     | 2475/5913 [01:33<02:01, 28.24it/s]

Batches:  42%|████▏     | 2478/5913 [01:33<02:00, 28.53it/s]

Batches:  42%|████▏     | 2481/5913 [01:33<02:01, 28.36it/s]

Batches:  42%|████▏     | 2484/5913 [01:33<02:01, 28.30it/s]

Batches:  42%|████▏     | 2488/5913 [01:33<01:56, 29.32it/s]

Batches:  42%|████▏     | 2491/5913 [01:33<01:57, 29.15it/s]

Batches:  42%|████▏     | 2494/5913 [01:34<01:59, 28.61it/s]

Batches:  42%|████▏     | 2497/5913 [01:34<02:00, 28.46it/s]

Batches:  42%|████▏     | 2500/5913 [01:34<01:59, 28.50it/s]

Batches:  42%|████▏     | 2504/5913 [01:34<01:55, 29.41it/s]

Batches:  42%|████▏     | 2507/5913 [01:34<01:55, 29.38it/s]

Batches:  42%|████▏     | 2510/5913 [01:34<01:57, 29.05it/s]

Batches:  42%|████▏     | 2513/5913 [01:34<01:57, 28.82it/s]

Batches:  43%|████▎     | 2516/5913 [01:34<01:57, 28.90it/s]

Batches:  43%|████▎     | 2519/5913 [01:34<01:58, 28.66it/s]

Batches:  43%|████▎     | 2522/5913 [01:35<01:58, 28.50it/s]

Batches:  43%|████▎     | 2525/5913 [01:35<01:58, 28.51it/s]

Batches:  43%|████▎     | 2528/5913 [01:35<01:58, 28.55it/s]

Batches:  43%|████▎     | 2532/5913 [01:35<01:55, 29.21it/s]

Batches:  43%|████▎     | 2535/5913 [01:35<01:55, 29.29it/s]

Batches:  43%|████▎     | 2538/5913 [01:35<01:57, 28.76it/s]

Batches:  43%|████▎     | 2541/5913 [01:35<01:57, 28.78it/s]

Batches:  43%|████▎     | 2544/5913 [01:35<01:58, 28.41it/s]

Batches:  43%|████▎     | 2547/5913 [01:35<01:59, 28.20it/s]

Batches:  43%|████▎     | 2550/5913 [01:36<01:58, 28.41it/s]

Batches:  43%|████▎     | 2554/5913 [01:36<01:55, 29.02it/s]

Batches:  43%|████▎     | 2557/5913 [01:36<01:56, 28.91it/s]

Batches:  43%|████▎     | 2561/5913 [01:36<01:54, 29.26it/s]

Batches:  43%|████▎     | 2564/5913 [01:36<01:55, 28.89it/s]

Batches:  43%|████▎     | 2567/5913 [01:36<01:56, 28.68it/s]

Batches:  43%|████▎     | 2570/5913 [01:36<01:56, 28.75it/s]

Batches:  44%|████▎     | 2573/5913 [01:36<01:56, 28.56it/s]

Batches:  44%|████▎     | 2576/5913 [01:36<01:57, 28.50it/s]

Batches:  44%|████▎     | 2580/5913 [01:37<01:54, 29.08it/s]

Batches:  44%|████▎     | 2583/5913 [01:37<01:55, 28.93it/s]

Batches:  44%|████▍     | 2587/5913 [01:37<01:52, 29.63it/s]

Batches:  44%|████▍     | 2590/5913 [01:37<01:52, 29.58it/s]

Batches:  44%|████▍     | 2594/5913 [01:37<01:50, 29.91it/s]

Batches:  44%|████▍     | 2598/5913 [01:37<01:50, 30.11it/s]

Batches:  44%|████▍     | 2602/5913 [01:37<01:51, 29.77it/s]

Batches:  44%|████▍     | 2605/5913 [01:37<01:52, 29.39it/s]

Batches:  44%|████▍     | 2609/5913 [01:38<01:46, 31.03it/s]

Batches:  44%|████▍     | 2613/5913 [01:38<01:44, 31.66it/s]

Batches:  44%|████▍     | 2617/5913 [01:38<01:47, 30.56it/s]

Batches:  44%|████▍     | 2621/5913 [01:38<01:51, 29.59it/s]

Batches:  44%|████▍     | 2625/5913 [01:38<01:47, 30.55it/s]

Batches:  44%|████▍     | 2629/5913 [01:38<01:49, 30.01it/s]

Batches:  45%|████▍     | 2633/5913 [01:38<01:45, 31.00it/s]

Batches:  45%|████▍     | 2637/5913 [01:38<01:47, 30.38it/s]

Batches:  45%|████▍     | 2641/5913 [01:39<01:43, 31.47it/s]

Batches:  45%|████▍     | 2645/5913 [01:39<01:40, 32.63it/s]

Batches:  45%|████▍     | 2649/5913 [01:39<01:39, 32.84it/s]

Batches:  45%|████▍     | 2653/5913 [01:39<01:42, 31.81it/s]

Batches:  45%|████▍     | 2657/5913 [01:39<01:44, 31.19it/s]

Batches:  45%|████▌     | 2661/5913 [01:39<01:42, 31.70it/s]

Batches:  45%|████▌     | 2665/5913 [01:39<01:43, 31.36it/s]

Batches:  45%|████▌     | 2669/5913 [01:39<01:42, 31.51it/s]

Batches:  45%|████▌     | 2673/5913 [01:40<01:43, 31.26it/s]

Batches:  45%|████▌     | 2677/5913 [01:40<01:40, 32.07it/s]

Batches:  45%|████▌     | 2681/5913 [01:40<01:39, 32.39it/s]

Batches:  45%|████▌     | 2685/5913 [01:40<01:43, 31.30it/s]

Batches:  45%|████▌     | 2689/5913 [01:40<01:41, 31.90it/s]

Batches:  46%|████▌     | 2693/5913 [01:40<01:41, 31.66it/s]

Batches:  46%|████▌     | 2697/5913 [01:40<01:37, 32.94it/s]

Batches:  46%|████▌     | 2701/5913 [01:40<01:34, 33.90it/s]

Batches:  46%|████▌     | 2705/5913 [01:41<01:32, 34.67it/s]

Batches:  46%|████▌     | 2709/5913 [01:41<01:36, 33.21it/s]

Batches:  46%|████▌     | 2713/5913 [01:41<01:40, 31.87it/s]

Batches:  46%|████▌     | 2717/5913 [01:41<01:41, 31.50it/s]

Batches:  46%|████▌     | 2721/5913 [01:41<01:41, 31.44it/s]

Batches:  46%|████▌     | 2725/5913 [01:41<01:40, 31.79it/s]

Batches:  46%|████▌     | 2729/5913 [01:41<01:40, 31.62it/s]

Batches:  46%|████▌     | 2733/5913 [01:41<01:38, 32.36it/s]

Batches:  46%|████▋     | 2737/5913 [01:42<01:39, 31.92it/s]

Batches:  46%|████▋     | 2741/5913 [01:42<01:36, 33.02it/s]

Batches:  46%|████▋     | 2745/5913 [01:42<01:33, 33.88it/s]

Batches:  46%|████▋     | 2749/5913 [01:42<01:36, 32.81it/s]

Batches:  47%|████▋     | 2753/5913 [01:42<01:35, 33.01it/s]

Batches:  47%|████▋     | 2757/5913 [01:42<01:36, 32.75it/s]

Batches:  47%|████▋     | 2761/5913 [01:42<01:35, 33.17it/s]

Batches:  47%|████▋     | 2765/5913 [01:42<01:36, 32.51it/s]

Batches:  47%|████▋     | 2769/5913 [01:43<01:36, 32.67it/s]

Batches:  47%|████▋     | 2773/5913 [01:43<01:35, 32.89it/s]

Batches:  47%|████▋     | 2777/5913 [01:43<01:32, 33.76it/s]

Batches:  47%|████▋     | 2781/5913 [01:43<01:28, 35.27it/s]

Batches:  47%|████▋     | 2785/5913 [01:43<01:31, 34.21it/s]

Batches:  47%|████▋     | 2789/5913 [01:43<01:32, 33.82it/s]

Batches:  47%|████▋     | 2793/5913 [01:43<01:32, 33.77it/s]

Batches:  47%|████▋     | 2797/5913 [01:43<01:30, 34.61it/s]

Batches:  47%|████▋     | 2801/5913 [01:43<01:28, 35.14it/s]

Batches:  47%|████▋     | 2805/5913 [01:44<01:29, 34.84it/s]

Batches:  48%|████▊     | 2809/5913 [01:44<01:26, 35.94it/s]

Batches:  48%|████▊     | 2813/5913 [01:44<01:28, 34.97it/s]

Batches:  48%|████▊     | 2817/5913 [01:44<01:30, 34.25it/s]

Batches:  48%|████▊     | 2821/5913 [01:44<01:28, 34.85it/s]

Batches:  48%|████▊     | 2825/5913 [01:44<01:29, 34.58it/s]

Batches:  48%|████▊     | 2829/5913 [01:44<01:30, 34.15it/s]

Batches:  48%|████▊     | 2833/5913 [01:44<01:30, 34.12it/s]

Batches:  48%|████▊     | 2837/5913 [01:44<01:28, 34.77it/s]

Batches:  48%|████▊     | 2841/5913 [01:45<01:25, 35.82it/s]

Batches:  48%|████▊     | 2845/5913 [01:45<01:25, 36.03it/s]

Batches:  48%|████▊     | 2849/5913 [01:45<01:26, 35.63it/s]

Batches:  48%|████▊     | 2854/5913 [01:45<01:24, 36.25it/s]

Batches:  48%|████▊     | 2858/5913 [01:45<01:28, 34.47it/s]

Batches:  48%|████▊     | 2863/5913 [01:45<01:23, 36.34it/s]

Batches:  48%|████▊     | 2867/5913 [01:45<01:25, 35.43it/s]

Batches:  49%|████▊     | 2871/5913 [01:45<01:23, 36.57it/s]

Batches:  49%|████▊     | 2875/5913 [01:46<01:22, 36.81it/s]

Batches:  49%|████▊     | 2879/5913 [01:46<01:22, 36.96it/s]

Batches:  49%|████▉     | 2883/5913 [01:46<01:21, 37.06it/s]

Batches:  49%|████▉     | 2887/5913 [01:46<01:21, 36.94it/s]

Batches:  49%|████▉     | 2891/5913 [01:46<01:21, 36.98it/s]

Batches:  49%|████▉     | 2895/5913 [01:46<01:22, 36.74it/s]

Batches:  49%|████▉     | 2900/5913 [01:46<01:19, 37.99it/s]

Batches:  49%|████▉     | 2904/5913 [01:46<01:19, 37.95it/s]

Batches:  49%|████▉     | 2908/5913 [01:46<01:19, 37.94it/s]

Batches:  49%|████▉     | 2912/5913 [01:46<01:19, 37.94it/s]

Batches:  49%|████▉     | 2916/5913 [01:47<01:22, 36.40it/s]

Batches:  49%|████▉     | 2920/5913 [01:47<01:21, 36.80it/s]

Batches:  49%|████▉     | 2925/5913 [01:47<01:18, 38.05it/s]

Batches:  50%|████▉     | 2929/5913 [01:47<01:18, 38.15it/s]

Batches:  50%|████▉     | 2934/5913 [01:47<01:18, 37.86it/s]

Batches:  50%|████▉     | 2938/5913 [01:47<01:19, 37.23it/s]

Batches:  50%|████▉     | 2942/5913 [01:47<01:18, 37.69it/s]

Batches:  50%|████▉     | 2946/5913 [01:47<01:19, 37.55it/s]

Batches:  50%|████▉     | 2950/5913 [01:48<01:22, 36.10it/s]

Batches:  50%|████▉     | 2954/5913 [01:48<01:24, 35.08it/s]

Batches:  50%|█████     | 2958/5913 [01:48<01:22, 35.83it/s]

Batches:  50%|█████     | 2962/5913 [01:48<01:20, 36.44it/s]

Batches:  50%|█████     | 2967/5913 [01:48<01:18, 37.63it/s]

Batches:  50%|█████     | 2971/5913 [01:48<01:18, 37.57it/s]

Batches:  50%|█████     | 2976/5913 [01:48<01:15, 39.02it/s]

Batches:  50%|█████     | 2981/5913 [01:48<01:13, 39.63it/s]

Batches:  50%|█████     | 2985/5913 [01:48<01:15, 38.82it/s]

Batches:  51%|█████     | 2990/5913 [01:49<01:13, 39.57it/s]

Batches:  51%|█████     | 2994/5913 [01:49<01:14, 39.02it/s]

Batches:  51%|█████     | 2999/5913 [01:49<01:13, 39.60it/s]

Batches:  51%|█████     | 3003/5913 [01:49<01:16, 37.82it/s]

Batches:  51%|█████     | 3007/5913 [01:49<01:20, 36.25it/s]

Batches:  51%|█████     | 3012/5913 [01:49<01:15, 38.35it/s]

Batches:  51%|█████     | 3016/5913 [01:49<01:16, 37.93it/s]

Batches:  51%|█████     | 3020/5913 [01:49<01:15, 38.08it/s]

Batches:  51%|█████     | 3025/5913 [01:49<01:13, 39.35it/s]

Batches:  51%|█████     | 3029/5913 [01:50<01:14, 38.85it/s]

Batches:  51%|█████▏    | 3033/5913 [01:50<01:14, 38.75it/s]

Batches:  51%|█████▏    | 3038/5913 [01:50<01:12, 39.73it/s]

Batches:  51%|█████▏    | 3043/5913 [01:50<01:11, 40.11it/s]

Batches:  52%|█████▏    | 3048/5913 [01:50<01:09, 41.20it/s]

Batches:  52%|█████▏    | 3053/5913 [01:50<01:08, 41.70it/s]

Batches:  52%|█████▏    | 3058/5913 [01:50<01:08, 41.54it/s]

Batches:  52%|█████▏    | 3063/5913 [01:50<01:08, 41.89it/s]

Batches:  52%|█████▏    | 3068/5913 [01:51<01:07, 42.21it/s]

Batches:  52%|█████▏    | 3073/5913 [01:51<01:07, 42.18it/s]

Batches:  52%|█████▏    | 3078/5913 [01:51<01:08, 41.61it/s]

Batches:  52%|█████▏    | 3083/5913 [01:51<01:07, 41.76it/s]

Batches:  52%|█████▏    | 3088/5913 [01:51<01:08, 41.30it/s]

Batches:  52%|█████▏    | 3093/5913 [01:51<01:07, 41.94it/s]

Batches:  52%|█████▏    | 3098/5913 [01:51<01:07, 41.46it/s]

Batches:  52%|█████▏    | 3103/5913 [01:51<01:06, 42.10it/s]

Batches:  53%|█████▎    | 3108/5913 [01:51<01:06, 42.02it/s]

Batches:  53%|█████▎    | 3113/5913 [01:52<01:06, 42.39it/s]

Batches:  53%|█████▎    | 3118/5913 [01:52<01:06, 42.29it/s]

Batches:  53%|█████▎    | 3123/5913 [01:52<01:05, 42.84it/s]

Batches:  53%|█████▎    | 3128/5913 [01:52<01:04, 43.11it/s]

Batches:  53%|█████▎    | 3133/5913 [01:52<01:04, 43.38it/s]

Batches:  53%|█████▎    | 3138/5913 [01:52<01:05, 42.54it/s]

Batches:  53%|█████▎    | 3143/5913 [01:52<01:06, 41.57it/s]

Batches:  53%|█████▎    | 3148/5913 [01:52<01:06, 41.38it/s]

Batches:  53%|█████▎    | 3153/5913 [01:53<01:05, 42.09it/s]

Batches:  53%|█████▎    | 3158/5913 [01:53<01:04, 42.94it/s]

Batches:  53%|█████▎    | 3163/5913 [01:53<01:05, 42.28it/s]

Batches:  54%|█████▎    | 3168/5913 [01:53<01:06, 41.31it/s]

Batches:  54%|█████▎    | 3173/5913 [01:53<01:04, 42.57it/s]

Batches:  54%|█████▎    | 3178/5913 [01:53<01:02, 43.57it/s]

Batches:  54%|█████▍    | 3183/5913 [01:53<01:02, 43.77it/s]

Batches:  54%|█████▍    | 3188/5913 [01:53<01:02, 43.51it/s]

Batches:  54%|█████▍    | 3193/5913 [01:53<01:02, 43.18it/s]

Batches:  54%|█████▍    | 3198/5913 [01:54<01:02, 43.63it/s]

Batches:  54%|█████▍    | 3203/5913 [01:54<01:01, 43.85it/s]

Batches:  54%|█████▍    | 3208/5913 [01:54<01:01, 43.83it/s]

Batches:  54%|█████▍    | 3213/5913 [01:54<01:02, 43.22it/s]

Batches:  54%|█████▍    | 3218/5913 [01:54<01:03, 42.22it/s]

Batches:  55%|█████▍    | 3223/5913 [01:54<01:02, 42.79it/s]

Batches:  55%|█████▍    | 3228/5913 [01:54<01:02, 42.78it/s]

Batches:  55%|█████▍    | 3233/5913 [01:54<01:03, 42.05it/s]

Batches:  55%|█████▍    | 3238/5913 [01:55<01:02, 42.68it/s]

Batches:  55%|█████▍    | 3243/5913 [01:55<01:01, 43.54it/s]

Batches:  55%|█████▍    | 3248/5913 [01:55<01:00, 43.70it/s]

Batches:  55%|█████▌    | 3253/5913 [01:55<01:00, 44.19it/s]

Batches:  55%|█████▌    | 3258/5913 [01:55<01:00, 43.83it/s]

Batches:  55%|█████▌    | 3263/5913 [01:55<00:59, 44.28it/s]

Batches:  55%|█████▌    | 3268/5913 [01:55<00:58, 44.84it/s]

Batches:  55%|█████▌    | 3273/5913 [01:55<00:59, 44.45it/s]

Batches:  55%|█████▌    | 3278/5913 [01:55<00:59, 44.39it/s]

Batches:  56%|█████▌    | 3283/5913 [01:56<00:58, 44.80it/s]

Batches:  56%|█████▌    | 3288/5913 [01:56<00:59, 44.12it/s]

Batches:  56%|█████▌    | 3293/5913 [01:56<00:59, 44.25it/s]

Batches:  56%|█████▌    | 3298/5913 [01:56<00:58, 44.46it/s]

Batches:  56%|█████▌    | 3303/5913 [01:56<00:57, 45.43it/s]

Batches:  56%|█████▌    | 3308/5913 [01:56<00:56, 46.16it/s]

Batches:  56%|█████▌    | 3313/5913 [01:56<00:57, 45.07it/s]

Batches:  56%|█████▌    | 3318/5913 [01:56<00:57, 45.48it/s]

Batches:  56%|█████▌    | 3323/5913 [01:56<00:56, 45.51it/s]

Batches:  56%|█████▋    | 3328/5913 [01:57<00:56, 45.97it/s]

Batches:  56%|█████▋    | 3333/5913 [01:57<00:58, 43.74it/s]

Batches:  56%|█████▋    | 3338/5913 [01:57<00:58, 44.38it/s]

Batches:  57%|█████▋    | 3343/5913 [01:57<00:57, 44.88it/s]

Batches:  57%|█████▋    | 3348/5913 [01:57<00:58, 43.60it/s]

Batches:  57%|█████▋    | 3353/5913 [01:57<00:58, 43.88it/s]

Batches:  57%|█████▋    | 3358/5913 [01:57<00:56, 45.11it/s]

Batches:  57%|█████▋    | 3363/5913 [01:57<00:55, 45.67it/s]

Batches:  57%|█████▋    | 3368/5913 [01:57<00:55, 45.65it/s]

Batches:  57%|█████▋    | 3373/5913 [01:58<00:55, 45.80it/s]

Batches:  57%|█████▋    | 3378/5913 [01:58<00:54, 46.58it/s]

Batches:  57%|█████▋    | 3383/5913 [01:58<00:55, 45.54it/s]

Batches:  57%|█████▋    | 3388/5913 [01:58<00:55, 45.22it/s]

Batches:  57%|█████▋    | 3393/5913 [01:58<00:54, 46.25it/s]

Batches:  57%|█████▋    | 3398/5913 [01:58<00:54, 46.54it/s]

Batches:  58%|█████▊    | 3403/5913 [01:58<00:53, 46.78it/s]

Batches:  58%|█████▊    | 3408/5913 [01:58<00:52, 47.68it/s]

Batches:  58%|█████▊    | 3413/5913 [01:58<00:51, 48.13it/s]

Batches:  58%|█████▊    | 3418/5913 [01:58<00:52, 47.65it/s]

Batches:  58%|█████▊    | 3423/5913 [01:59<00:52, 47.18it/s]

Batches:  58%|█████▊    | 3428/5913 [01:59<00:53, 46.54it/s]

Batches:  58%|█████▊    | 3433/5913 [01:59<00:52, 46.97it/s]

Batches:  58%|█████▊    | 3438/5913 [01:59<00:51, 47.80it/s]

Batches:  58%|█████▊    | 3443/5913 [01:59<00:51, 48.37it/s]

Batches:  58%|█████▊    | 3448/5913 [01:59<00:51, 48.33it/s]

Batches:  58%|█████▊    | 3453/5913 [01:59<00:50, 48.40it/s]

Batches:  58%|█████▊    | 3459/5913 [01:59<00:50, 48.72it/s]

Batches:  59%|█████▊    | 3464/5913 [01:59<00:50, 48.49it/s]

Batches:  59%|█████▊    | 3469/5913 [02:00<00:50, 48.14it/s]

Batches:  59%|█████▉    | 3475/5913 [02:00<00:49, 49.05it/s]

Batches:  59%|█████▉    | 3480/5913 [02:00<00:50, 48.58it/s]

Batches:  59%|█████▉    | 3485/5913 [02:00<00:50, 48.06it/s]

Batches:  59%|█████▉    | 3491/5913 [02:00<00:49, 48.91it/s]

Batches:  59%|█████▉    | 3496/5913 [02:00<00:49, 48.96it/s]

Batches:  59%|█████▉    | 3501/5913 [02:00<00:51, 47.27it/s]

Batches:  59%|█████▉    | 3506/5913 [02:00<00:50, 47.81it/s]

Batches:  59%|█████▉    | 3511/5913 [02:00<00:49, 48.08it/s]

Batches:  59%|█████▉    | 3517/5913 [02:01<00:48, 49.37it/s]

Batches:  60%|█████▉    | 3523/5913 [02:01<00:47, 50.26it/s]

Batches:  60%|█████▉    | 3529/5913 [02:01<00:47, 50.20it/s]

Batches:  60%|█████▉    | 3535/5913 [02:01<00:47, 49.87it/s]

Batches:  60%|█████▉    | 3540/5913 [02:01<00:47, 49.66it/s]

Batches:  60%|█████▉    | 3546/5913 [02:01<00:47, 50.28it/s]

Batches:  60%|██████    | 3552/5913 [02:01<00:46, 51.03it/s]

Batches:  60%|██████    | 3558/5913 [02:01<00:46, 50.60it/s]

Batches:  60%|██████    | 3564/5913 [02:01<00:46, 50.54it/s]

Batches:  60%|██████    | 3570/5913 [02:02<00:46, 50.03it/s]

Batches:  60%|██████    | 3576/5913 [02:02<00:46, 50.67it/s]

Batches:  61%|██████    | 3582/5913 [02:02<00:46, 50.47it/s]

Batches:  61%|██████    | 3588/5913 [02:02<00:46, 50.37it/s]

Batches:  61%|██████    | 3594/5913 [02:02<00:45, 50.63it/s]

Batches:  61%|██████    | 3600/5913 [02:02<00:45, 51.16it/s]

Batches:  61%|██████    | 3606/5913 [02:02<00:45, 51.02it/s]

Batches:  61%|██████    | 3612/5913 [02:02<00:45, 50.58it/s]

Batches:  61%|██████    | 3618/5913 [02:03<00:45, 50.52it/s]

Batches:  61%|██████▏   | 3624/5913 [02:03<00:45, 50.31it/s]

Batches:  61%|██████▏   | 3630/5913 [02:03<00:45, 50.60it/s]

Batches:  61%|██████▏   | 3636/5913 [02:03<00:44, 51.01it/s]

Batches:  62%|██████▏   | 3642/5913 [02:03<00:44, 50.79it/s]

Batches:  62%|██████▏   | 3648/5913 [02:03<00:44, 50.44it/s]

Batches:  62%|██████▏   | 3654/5913 [02:03<00:44, 50.59it/s]

Batches:  62%|██████▏   | 3660/5913 [02:03<00:44, 50.64it/s]

Batches:  62%|██████▏   | 3666/5913 [02:03<00:43, 51.39it/s]

Batches:  62%|██████▏   | 3672/5913 [02:04<00:43, 51.87it/s]

Batches:  62%|██████▏   | 3678/5913 [02:04<00:43, 51.58it/s]

Batches:  62%|██████▏   | 3684/5913 [02:04<00:42, 51.98it/s]

Batches:  62%|██████▏   | 3690/5913 [02:04<00:42, 52.60it/s]

Batches:  63%|██████▎   | 3696/5913 [02:04<00:42, 52.74it/s]

Batches:  63%|██████▎   | 3702/5913 [02:04<00:41, 53.43it/s]

Batches:  63%|██████▎   | 3708/5913 [02:04<00:40, 53.81it/s]

Batches:  63%|██████▎   | 3714/5913 [02:04<00:41, 53.58it/s]

Batches:  63%|██████▎   | 3720/5913 [02:04<00:40, 53.56it/s]

Batches:  63%|██████▎   | 3726/5913 [02:05<00:41, 52.85it/s]

Batches:  63%|██████▎   | 3732/5913 [02:05<00:41, 52.16it/s]

Batches:  63%|██████▎   | 3738/5913 [02:05<00:41, 52.22it/s]

Batches:  63%|██████▎   | 3744/5913 [02:05<00:42, 51.50it/s]

Batches:  63%|██████▎   | 3750/5913 [02:05<00:41, 51.56it/s]

Batches:  64%|██████▎   | 3756/5913 [02:05<00:42, 51.23it/s]

Batches:  64%|██████▎   | 3762/5913 [02:05<00:41, 52.02it/s]

Batches:  64%|██████▎   | 3768/5913 [02:05<00:40, 53.04it/s]

Batches:  64%|██████▍   | 3774/5913 [02:05<00:39, 53.56it/s]

Batches:  64%|██████▍   | 3780/5913 [02:06<00:39, 53.92it/s]

Batches:  64%|██████▍   | 3786/5913 [02:06<00:38, 54.72it/s]

Batches:  64%|██████▍   | 3792/5913 [02:06<00:38, 54.85it/s]

Batches:  64%|██████▍   | 3798/5913 [02:06<00:38, 54.80it/s]

Batches:  64%|██████▍   | 3804/5913 [02:06<00:38, 54.83it/s]

Batches:  64%|██████▍   | 3810/5913 [02:06<00:38, 54.98it/s]

Batches:  65%|██████▍   | 3816/5913 [02:06<00:38, 54.45it/s]

Batches:  65%|██████▍   | 3822/5913 [02:06<00:38, 54.69it/s]

Batches:  65%|██████▍   | 3828/5913 [02:06<00:38, 54.36it/s]

Batches:  65%|██████▍   | 3834/5913 [02:07<00:38, 53.89it/s]

Batches:  65%|██████▍   | 3840/5913 [02:07<00:38, 54.39it/s]

Batches:  65%|██████▌   | 3846/5913 [02:07<00:38, 54.16it/s]

Batches:  65%|██████▌   | 3852/5913 [02:07<00:37, 54.79it/s]

Batches:  65%|██████▌   | 3858/5913 [02:07<00:37, 55.22it/s]

Batches:  65%|██████▌   | 3864/5913 [02:07<00:36, 56.02it/s]

Batches:  65%|██████▌   | 3870/5913 [02:07<00:36, 55.46it/s]

Batches:  66%|██████▌   | 3876/5913 [02:07<00:36, 55.70it/s]

Batches:  66%|██████▌   | 3882/5913 [02:07<00:36, 55.65it/s]

Batches:  66%|██████▌   | 3888/5913 [02:08<00:35, 56.46it/s]

Batches:  66%|██████▌   | 3894/5913 [02:08<00:35, 56.61it/s]

Batches:  66%|██████▌   | 3900/5913 [02:08<00:35, 56.56it/s]

Batches:  66%|██████▌   | 3906/5913 [02:08<00:35, 57.00it/s]

Batches:  66%|██████▌   | 3912/5913 [02:08<00:35, 56.96it/s]

Batches:  66%|██████▋   | 3918/5913 [02:08<00:35, 56.69it/s]

Batches:  66%|██████▋   | 3925/5913 [02:08<00:34, 57.95it/s]

Batches:  66%|██████▋   | 3931/5913 [02:08<00:34, 57.96it/s]

Batches:  67%|██████▋   | 3937/5913 [02:08<00:33, 58.22it/s]

Batches:  67%|██████▋   | 3943/5913 [02:09<00:33, 58.04it/s]

Batches:  67%|██████▋   | 3949/5913 [02:09<00:33, 58.50it/s]

Batches:  67%|██████▋   | 3955/5913 [02:09<00:33, 58.30it/s]

Batches:  67%|██████▋   | 3961/5913 [02:09<00:33, 58.06it/s]

Batches:  67%|██████▋   | 3967/5913 [02:09<00:33, 57.66it/s]

Batches:  67%|██████▋   | 3973/5913 [02:09<00:33, 57.67it/s]

Batches:  67%|██████▋   | 3979/5913 [02:09<00:34, 56.52it/s]

Batches:  67%|██████▋   | 3985/5913 [02:09<00:33, 57.06it/s]

Batches:  67%|██████▋   | 3991/5913 [02:09<00:33, 57.15it/s]

Batches:  68%|██████▊   | 3998/5913 [02:09<00:33, 58.01it/s]

Batches:  68%|██████▊   | 4004/5913 [02:10<00:33, 57.19it/s]

Batches:  68%|██████▊   | 4010/5913 [02:10<00:33, 57.43it/s]

Batches:  68%|██████▊   | 4017/5913 [02:10<00:32, 58.45it/s]

Batches:  68%|██████▊   | 4023/5913 [02:10<00:32, 58.07it/s]

Batches:  68%|██████▊   | 4030/5913 [02:10<00:32, 58.78it/s]

Batches:  68%|██████▊   | 4037/5913 [02:10<00:31, 59.84it/s]

Batches:  68%|██████▊   | 4043/5913 [02:10<00:31, 59.27it/s]

Batches:  68%|██████▊   | 4050/5913 [02:10<00:30, 60.33it/s]

Batches:  69%|██████▊   | 4057/5913 [02:10<00:30, 60.61it/s]

Batches:  69%|██████▊   | 4064/5913 [02:11<00:29, 62.03it/s]

Batches:  69%|██████▉   | 4071/5913 [02:11<00:30, 61.34it/s]

Batches:  69%|██████▉   | 4078/5913 [02:11<00:30, 60.35it/s]

Batches:  69%|██████▉   | 4085/5913 [02:11<00:30, 60.84it/s]

Batches:  69%|██████▉   | 4092/5913 [02:11<00:29, 61.24it/s]

Batches:  69%|██████▉   | 4099/5913 [02:11<00:29, 60.64it/s]

Batches:  69%|██████▉   | 4106/5913 [02:11<00:29, 61.19it/s]

Batches:  70%|██████▉   | 4113/5913 [02:11<00:29, 61.08it/s]

Batches:  70%|██████▉   | 4120/5913 [02:11<00:28, 62.07it/s]

Batches:  70%|██████▉   | 4127/5913 [02:12<00:28, 63.01it/s]

Batches:  70%|██████▉   | 4134/5913 [02:12<00:27, 64.13it/s]

Batches:  70%|███████   | 4141/5913 [02:12<00:28, 62.72it/s]

Batches:  70%|███████   | 4148/5913 [02:12<00:27, 63.55it/s]

Batches:  70%|███████   | 4155/5913 [02:12<00:27, 64.54it/s]

Batches:  70%|███████   | 4162/5913 [02:12<00:27, 63.32it/s]

Batches:  71%|███████   | 4169/5913 [02:12<00:27, 63.29it/s]

Batches:  71%|███████   | 4176/5913 [02:12<00:26, 64.70it/s]

Batches:  71%|███████   | 4183/5913 [02:12<00:27, 63.82it/s]

Batches:  71%|███████   | 4191/5913 [02:13<00:26, 65.55it/s]

Batches:  71%|███████   | 4198/5913 [02:13<00:26, 65.25it/s]

Batches:  71%|███████   | 4205/5913 [02:13<00:26, 65.03it/s]

Batches:  71%|███████   | 4212/5913 [02:13<00:25, 65.76it/s]

Batches:  71%|███████▏  | 4219/5913 [02:13<00:25, 66.82it/s]

Batches:  71%|███████▏  | 4226/5913 [02:13<00:24, 67.72it/s]

Batches:  72%|███████▏  | 4234/5913 [02:13<00:24, 68.32it/s]

Batches:  72%|███████▏  | 4241/5913 [02:13<00:24, 67.37it/s]

Batches:  72%|███████▏  | 4249/5913 [02:13<00:23, 69.79it/s]

Batches:  72%|███████▏  | 4257/5913 [02:14<00:23, 71.10it/s]

Batches:  72%|███████▏  | 4265/5913 [02:14<00:23, 69.14it/s]

Batches:  72%|███████▏  | 4273/5913 [02:14<00:23, 70.26it/s]

Batches:  72%|███████▏  | 4281/5913 [02:14<00:22, 71.94it/s]

Batches:  73%|███████▎  | 4289/5913 [02:14<00:22, 72.00it/s]

Batches:  73%|███████▎  | 4297/5913 [02:14<00:22, 71.05it/s]

Batches:  73%|███████▎  | 4305/5913 [02:14<00:22, 72.25it/s]

Batches:  73%|███████▎  | 4313/5913 [02:14<00:21, 73.30it/s]

Batches:  73%|███████▎  | 4321/5913 [02:14<00:21, 73.49it/s]

Batches:  73%|███████▎  | 4329/5913 [02:15<00:21, 74.43it/s]

Batches:  73%|███████▎  | 4337/5913 [02:15<00:21, 74.32it/s]

Batches:  73%|███████▎  | 4346/5913 [02:15<00:20, 76.19it/s]

Batches:  74%|███████▎  | 4355/5913 [02:15<00:19, 77.99it/s]

Batches:  74%|███████▍  | 4363/5913 [02:15<00:20, 75.24it/s]

Batches:  74%|███████▍  | 4372/5913 [02:15<00:19, 77.78it/s]

Batches:  74%|███████▍  | 4381/5913 [02:15<00:19, 79.34it/s]

Batches:  74%|███████▍  | 4389/5913 [02:15<00:19, 77.73it/s]

Batches:  74%|███████▍  | 4398/5913 [02:15<00:19, 79.37it/s]

Batches:  75%|███████▍  | 4407/5913 [02:16<00:18, 80.09it/s]

Batches:  75%|███████▍  | 4416/5913 [02:16<00:18, 79.80it/s]

Batches:  75%|███████▍  | 4424/5913 [02:16<00:18, 79.55it/s]

Batches:  75%|███████▍  | 4433/5913 [02:16<00:18, 81.45it/s]

Batches:  75%|███████▌  | 4442/5913 [02:16<00:17, 82.25it/s]

Batches:  75%|███████▌  | 4451/5913 [02:16<00:17, 83.38it/s]

Batches:  75%|███████▌  | 4460/5913 [02:16<00:17, 83.98it/s]

Batches:  76%|███████▌  | 4470/5913 [02:16<00:16, 86.12it/s]

Batches:  76%|███████▌  | 4479/5913 [02:16<00:16, 85.39it/s]

Batches:  76%|███████▌  | 4488/5913 [02:16<00:16, 86.32it/s]

Batches:  76%|███████▌  | 4497/5913 [02:17<00:16, 86.18it/s]

Batches:  76%|███████▌  | 4507/5913 [02:17<00:16, 87.25it/s]

Batches:  76%|███████▋  | 4516/5913 [02:17<00:15, 87.54it/s]

Batches:  77%|███████▋  | 4526/5913 [02:17<00:15, 88.61it/s]

Batches:  77%|███████▋  | 4535/5913 [02:17<00:15, 88.46it/s]

Batches:  77%|███████▋  | 4544/5913 [02:17<00:15, 88.49it/s]

Batches:  77%|███████▋  | 4553/5913 [02:17<00:15, 88.00it/s]

Batches:  77%|███████▋  | 4562/5913 [02:17<00:15, 88.31it/s]

Batches:  77%|███████▋  | 4571/5913 [02:17<00:15, 88.47it/s]

Batches:  77%|███████▋  | 4580/5913 [02:18<00:15, 88.63it/s]

Batches:  78%|███████▊  | 4590/5913 [02:18<00:14, 91.21it/s]

Batches:  78%|███████▊  | 4600/5913 [02:18<00:14, 90.82it/s]

Batches:  78%|███████▊  | 4610/5913 [02:18<00:14, 91.99it/s]

Batches:  78%|███████▊  | 4620/5913 [02:18<00:13, 92.51it/s]

Batches:  78%|███████▊  | 4630/5913 [02:18<00:13, 93.69it/s]

Batches:  78%|███████▊  | 4640/5913 [02:18<00:13, 94.36it/s]

Batches:  79%|███████▊  | 4650/5913 [02:18<00:13, 94.48it/s]

Batches:  79%|███████▉  | 4660/5913 [02:18<00:13, 95.06it/s]

Batches:  79%|███████▉  | 4670/5913 [02:18<00:12, 95.83it/s]

Batches:  79%|███████▉  | 4681/5913 [02:19<00:12, 97.12it/s]

Batches:  79%|███████▉  | 4691/5913 [02:19<00:12, 96.84it/s]

Batches:  80%|███████▉  | 4702/5913 [02:19<00:12, 97.38it/s]

Batches:  80%|███████▉  | 4712/5913 [02:19<00:12, 97.37it/s]

Batches:  80%|███████▉  | 4722/5913 [02:19<00:12, 96.72it/s]

Batches:  80%|████████  | 4733/5913 [02:19<00:11, 98.81it/s]

Batches:  80%|████████  | 4744/5913 [02:19<00:11, 99.86it/s]

Batches:  80%|████████  | 4755/5913 [02:19<00:11, 102.09it/s]

Batches:  81%|████████  | 4766/5913 [02:19<00:11, 101.71it/s]

Batches:  81%|████████  | 4777/5913 [02:20<00:11, 102.78it/s]

Batches:  81%|████████  | 4789/5913 [02:20<00:10, 104.73it/s]

Batches:  81%|████████  | 4800/5913 [02:20<00:10, 104.56it/s]

Batches:  81%|████████▏ | 4811/5913 [02:20<00:10, 103.66it/s]

Batches:  82%|████████▏ | 4822/5913 [02:20<00:10, 104.16it/s]

Batches:  82%|████████▏ | 4834/5913 [02:20<00:10, 105.79it/s]

Batches:  82%|████████▏ | 4845/5913 [02:20<00:09, 106.89it/s]

Batches:  82%|████████▏ | 4856/5913 [02:20<00:09, 107.73it/s]

Batches:  82%|████████▏ | 4867/5913 [02:20<00:09, 108.31it/s]

Batches:  83%|████████▎ | 4879/5913 [02:20<00:09, 109.93it/s]

Batches:  83%|████████▎ | 4890/5913 [02:21<00:09, 109.72it/s]

Batches:  83%|████████▎ | 4902/5913 [02:21<00:09, 110.32it/s]

Batches:  83%|████████▎ | 4914/5913 [02:21<00:08, 111.52it/s]

Batches:  83%|████████▎ | 4926/5913 [02:21<00:08, 113.90it/s]

Batches:  84%|████████▎ | 4938/5913 [02:21<00:08, 114.53it/s]

Batches:  84%|████████▎ | 4951/5913 [02:21<00:08, 116.97it/s]

Batches:  84%|████████▍ | 4963/5913 [02:21<00:08, 117.29it/s]

Batches:  84%|████████▍ | 4976/5913 [02:21<00:07, 120.33it/s]

Batches:  84%|████████▍ | 4989/5913 [02:21<00:07, 120.75it/s]

Batches:  85%|████████▍ | 5003/5913 [02:21<00:07, 123.88it/s]

Batches:  85%|████████▍ | 5016/5913 [02:22<00:07, 125.39it/s]

Batches:  85%|████████▌ | 5030/5913 [02:22<00:06, 126.93it/s]

Batches:  85%|████████▌ | 5044/5913 [02:22<00:06, 127.92it/s]

Batches:  86%|████████▌ | 5058/5913 [02:22<00:06, 130.24it/s]

Batches:  86%|████████▌ | 5072/5913 [02:22<00:06, 130.87it/s]

Batches:  86%|████████▌ | 5086/5913 [02:22<00:06, 131.33it/s]

Batches:  86%|████████▋ | 5100/5913 [02:22<00:06, 132.15it/s]

Batches:  86%|████████▋ | 5114/5913 [02:22<00:05, 133.70it/s]

Batches:  87%|████████▋ | 5128/5913 [02:22<00:05, 135.18it/s]

Batches:  87%|████████▋ | 5142/5913 [02:23<00:05, 136.41it/s]

Batches:  87%|████████▋ | 5157/5913 [02:23<00:05, 137.82it/s]

Batches:  87%|████████▋ | 5172/5913 [02:23<00:05, 139.64it/s]

Batches:  88%|████████▊ | 5187/5913 [02:23<00:05, 140.98it/s]

Batches:  88%|████████▊ | 5202/5913 [02:23<00:05, 141.27it/s]

Batches:  88%|████████▊ | 5217/5913 [02:23<00:04, 140.49it/s]

Batches:  88%|████████▊ | 5232/5913 [02:23<00:04, 142.61it/s]

Batches:  89%|████████▊ | 5247/5913 [02:23<00:04, 143.48it/s]

Batches:  89%|████████▉ | 5262/5913 [02:23<00:04, 144.48it/s]

Batches:  89%|████████▉ | 5277/5913 [02:23<00:04, 144.66it/s]

Batches:  90%|████████▉ | 5293/5913 [02:24<00:04, 146.47it/s]

Batches:  90%|████████▉ | 5308/5913 [02:24<00:04, 145.87it/s]

Batches:  90%|█████████ | 5323/5913 [02:24<00:04, 146.87it/s]

Batches:  90%|█████████ | 5339/5913 [02:24<00:03, 147.75it/s]

Batches:  91%|█████████ | 5355/5913 [02:24<00:03, 148.64it/s]

Batches:  91%|█████████ | 5371/5913 [02:24<00:03, 150.88it/s]

Batches:  91%|█████████ | 5387/5913 [02:24<00:03, 151.77it/s]

Batches:  91%|█████████▏| 5403/5913 [02:24<00:03, 152.04it/s]

Batches:  92%|█████████▏| 5420/5913 [02:24<00:03, 155.45it/s]

Batches:  92%|█████████▏| 5437/5913 [02:25<00:03, 157.28it/s]

Batches:  92%|█████████▏| 5455/5913 [02:25<00:02, 161.29it/s]

Batches:  93%|█████████▎| 5472/5913 [02:25<00:02, 162.16it/s]

Batches:  93%|█████████▎| 5490/5913 [02:25<00:02, 165.84it/s]

Batches:  93%|█████████▎| 5508/5913 [02:25<00:02, 167.86it/s]

Batches:  93%|█████████▎| 5526/5913 [02:25<00:02, 169.70it/s]

Batches:  94%|█████████▍| 5544/5913 [02:25<00:02, 171.68it/s]

Batches:  94%|█████████▍| 5562/5913 [02:25<00:02, 172.25it/s]

Batches:  94%|█████████▍| 5581/5913 [02:25<00:01, 175.39it/s]

Batches:  95%|█████████▍| 5600/5913 [02:25<00:01, 178.78it/s]

Batches:  95%|█████████▌| 5619/5913 [02:26<00:01, 182.08it/s]

Batches:  95%|█████████▌| 5639/5913 [02:26<00:01, 187.28it/s]

Batches:  96%|█████████▌| 5660/5913 [02:26<00:01, 192.39it/s]

Batches:  96%|█████████▌| 5681/5913 [02:26<00:01, 196.97it/s]

Batches:  96%|█████████▋| 5703/5913 [02:26<00:01, 201.23it/s]

Batches:  97%|█████████▋| 5725/5913 [02:26<00:00, 206.33it/s]

Batches:  97%|█████████▋| 5748/5913 [02:26<00:00, 213.17it/s]

Batches:  98%|█████████▊| 5772/5913 [02:26<00:00, 220.48it/s]

Batches:  98%|█████████▊| 5796/5913 [02:26<00:00, 225.74it/s]

Batches:  98%|█████████▊| 5822/5913 [02:26<00:00, 233.74it/s]

Batches:  99%|█████████▉| 5850/5913 [02:27<00:00, 245.30it/s]

Batches:  99%|█████████▉| 5878/5913 [02:27<00:00, 254.70it/s]

Batches: 100%|█████████▉| 5906/5913 [02:27<00:00, 243.19it/s]

Batches: 100%|██████████| 5913/5913 [02:27<00:00, 40.14it/s]

Batches:   0%|          | 0/462 [00:00<?, ?it/s]

Batches:   6%|▌         | 28/462 [00:00<00:01, 277.38it/s]

Batches:  13%|█▎        | 58/462 [00:00<00:01, 288.55it/s]

Batches:  19%|█▉        | 89/462 [00:00<00:01, 295.56it/s]

Batches:  26%|██▌       | 120/462 [00:00<00:01, 298.72it/s]

Batches:  33%|███▎      | 152/462 [00:00<00:01, 303.91it/s]

Batches:  40%|███▉      | 184/462 [00:00<00:00, 308.56it/s]

Batches:  47%|████▋     | 217/462 [00:00<00:00, 314.42it/s]

Batches:  54%|█████▍    | 251/462 [00:00<00:00, 320.85it/s]

Batches:  62%|██████▏   | 285/462 [00:00<00:00, 325.56it/s]

Batches:  69%|██████▉   | 319/462 [00:01<00:00, 327.82it/s]

Batches:  76%|███████▌  | 352/462 [00:01<00:00, 328.05it/s]

Batches:  83%|████████▎ | 385/462 [00:01<00:00, 321.90it/s]

Batches:  90%|█████████ | 418/462 [00:01<00:00, 320.50it/s]

Batches:  98%|█████████▊| 451/462 [00:01<00:00, 322.36it/s]

Batches: 100%|██████████| 462/462 [00:01<00:00, 316.14it/s]

                                        Значение
Документы                          189212.000000
Тексты запросов                     14781.000000
Кодирование корпуса, с                148.580158
Кодирование запросов, с                 1.491450
Сохранение и контрольные суммы, с       0.229673
Документов/с                         1273.467484
Embeddings корпуса, МиБ               277.166016

In [30]:
# Полный расчёт на том же устройстве проверяет exact top-k без различий BLAS.
reference_scores = query_embeddings[:8] @ corpus_embeddings[:1000].T
for test_device in test_devices:
    with torch.inference_mode():
        device_scores = (torch.as_tensor(query_embeddings[:8], device=test_device)
                         @ torch.as_tensor(corpus_embeddings[:1000], device=test_device).T).cpu().numpy()
    np.testing.assert_allclose(device_scores, reference_scores, atol=2e-6, rtol=2e-6)
    reference = [np.lexsort((np.arange(len(row)), -row))[:50] for row in device_scores]
    found, _ = dense_top_k(query_embeddings[:8], corpus_embeddings[:1000], device=test_device)
    for actual, expected in zip(found, reference):
        np.testing.assert_array_equal(actual, expected)
start = perf_counter()
dense_positions, dense_ties = dense_top_k(
    query_embeddings, corpus_embeddings, batch_size=DENSE_CONFIG["search_batch_size"])
synchronize_device(DEVICE)
dense_search_seconds = perf_counter() - start
dense_predictions = {text: item_ids[positions].tolist() for text, positions in zip(val_texts, dense_positions)}
assert set(dense_predictions) == set(val_texts)
assert all(len(ids) == 50 and len(set(ids)) == 50 and set(ids) <= corpus_ids for ids in dense_predictions.values())
dense_per_query = evaluate(validation, dense_predictions)
assert dense_per_query.index.equals(per_query.index)
assert dense_per_query["Recall@50"].notna().all()
assert dense_per_query[[f"Recall@{k}" for k in RECALL_K]].diff(axis=1).iloc[:, 1:].ge(0).all().all()
dense_metrics = dense_per_query.mean()
assert dense_metrics["Recall@50"] <= ceiling + 1e-12
dense_ci = cluster_delta_interval(per_query["Recall@50"], dense_per_query["Recall@50"], validation.search_query, confidence=.95)
dense_row = {
    **experiment, "experiment": "E3", "config": json.dumps(DENSE_CONFIG, sort_keys=True),
    "token_pattern": None, "bm25s_version": None, "device": str(DEVICE),
    **{name: float(value) for name, value in dense_metrics.items()},
    "index_seconds": dense_index_seconds, "search_seconds": dense_search_seconds + dense_query_encode_seconds,
    "query_encode_seconds": dense_query_encode_seconds, "exact_search_seconds": dense_search_seconds,
    "model_load_seconds": model_load_seconds, "save_seconds": dense_save_seconds,
    "index_MiB": corpus_embeddings.nbytes / 2**20,
    "delta_Recall@50": dense_metrics["Recall@50"] - metrics["Recall@50"],
    "delta_ci_low": dense_ci[0], "delta_ci_high": dense_ci[1],
    "bootstrap_confidence": .95, "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
    "boundary_tie_queries": dense_ties, "empty_query_texts": 0,
    "sentence_transformers_version": importlib.metadata.version("sentence-transformers"),
    "transformers_version": importlib.metadata.version("transformers"),
    "rss_MiB": psutil.Process().memory_info().rss / 2**20,
    "conclusion": f"Recall@50={dense_metrics['Recall@50']:.4%}; zero-shot multilingual-e5-small",
}
experiments = pd.concat([experiments.loc[experiments.experiment.ne("E3")], pd.DataFrame([dense_row])], ignore_index=True)
assert experiments.experiment.is_unique
experiments.to_csv(EXPERIMENTS_PATH, index=False)
display(experiments[["experiment", "Recall@1", "Recall@5", "Recall@10", "Recall@20", "Recall@50", "available_Recall@50"]].round(6))
display(pd.Series({"Разница с E0, п.п.": 100 * dense_row["delta_Recall@50"],
                   "95% интервал, нижняя граница, п.п.": 100 * dense_ci[0],
                   "95% интервал, верхняя граница, п.п.": 100 * dense_ci[1],
                   "Exact search, с": dense_search_seconds,
                   "Равенства на границе top-50": dense_ties}, name="Значение").to_frame())

,experiment,Recall@1,Recall@5,Recall@10,Recall@20,Recall@50,available_Recall@50
0,E0,0.001626,0.005165,0.008089,0.012069,0.019168,0.297620
1,E1_title,0.001385,0.004453,0.006679,0.009545,0.014627,0.233371
2,E1_description,0.001275,0.004290,0.007144,0.010456,0.016294,0.253143
3,E1_title1_description1,0.001782,0.005579,0.008227,0.012068,0.018960,0.298519
4,E1_title2_description1,0.001769,0.005324,0.008113,0.011961,0.018315,0.290581
5,E1_title4_description1,0.001545,0.005050,0.007639,0.011418,0.017560,0.278194
6,E2_word,0.000755,0.002981,0.005523,0.009084,0.015504,0.239996
7,E2_char,0.000714,0.002582,0.004389,0.007419,0.013516,0.204643
8,E3,0.001363,0.004886,0.007467,0.011443,0.018395,0.287525

                                        Значение
Разница с E0, п.п.                     -0.077308
95% интервал, нижняя граница, п.п.     -0.169459
95% интервал, верхняя граница, п.п.     0.014792
Exact search, с                         0.349858
Равенства на границе top-50          1631.000000

### Дополняемость BM25 и dense

Уникальные позитивные пары при глубине 50, включая позитивы вне корпуса.
Это подсчёт пар, а не macro Recall. Примеры — первые пять различных текстов
по алфавиту в каждой категории различий; они не характеризуют частоту ошибок.

In [31]:
dense_pair_counts = {"Оба": 0, "Только BM25": 0, "Только dense": 0, "Ни один": 0}
dense_examples, seen_examples = [], {"Только BM25": set(), "Только dense": set()}
for query in validation.sort_values("search_query", kind="stable").itertuples():
    base, candidate = predictions[query.search_query], dense_predictions[query.search_query]
    base_found, dense_found = query.positives & set(base), query.positives & set(candidate)
    dense_pair_counts["Оба"] += len(base_found & dense_found)
    dense_pair_counts["Только BM25"] += len(base_found - dense_found)
    dense_pair_counts["Только dense"] += len(dense_found - base_found)
    dense_pair_counts["Ни один"] += len(query.positives - (base_found | dense_found))
    for label, changed in [("Только BM25", base_found - dense_found), ("Только dense", dense_found - base_found)]:
        if changed and len(seen_examples[label]) < 5 and query.search_query not in seen_examples[label]:
            item_id = sorted(changed)[0]
            dense_examples.append({"Случай": label, "Запрос": query.search_query, "group_id": query.Index,
                                   "item_id": item_id, "Заголовок": titles_by_id[item_id],
                                   "Ранг BM25": base.index(item_id) + 1 if item_id in base else ">50",
                                   "Ранг dense": candidate.index(item_id) + 1 if item_id in candidate else ">50"})
            seen_examples[label].add(query.search_query)
assert sum(dense_pair_counts.values()) == validation.n_positives.sum()
dense_pair_table = pd.Series(dense_pair_counts, name="Пары").to_frame()
dense_pair_table["Доля пар"] = dense_pair_table.Пары / dense_pair_table.Пары.sum()
display(dense_pair_table)
display(pd.DataFrame(dense_examples))

               Пары  Доля пар
Оба             954  0.010942
Только BM25     701  0.008040
Только dense    632  0.007249
Ни один       84900  0.973769

,Случай,Запрос,group_id,item_id,Заголовок,Ранг BM25,Ранг dense
0,Только BM25,3d печать,424,c9a823ae64fbd1eb,Профессиональная 3D печать,25,>50
1,Только dense,3d печать,412,6cb949d70341a638,3D печать,>50,16
2,Только BM25,777,888,d1f9f13c96294d41,Домашний интернет и тв в частный дом,6,>50
3,Только dense,ip видеонаблюдение,1466,960ee99868b1118f,Монтаж и обслуживание видеонаблюдения,>50,39
4,Только dense,iphone ломбард покупка,1481,cbe5f414681fd4da,Выкуп iPhone/MacBook/Samsung,>50,39
5,Только BM25,mercari выкуп,2071,fab5bf956436a174,Байер Япония (Mercari/Yahoo/Rakuten и тд),1,>50
6,Только BM25,sla печать,2512,b765441de5364699,"Художественная SLA печать,покрас 3D моделей",31,>50
7,Только BM25,smas лифтинг,2527,6fce025768d766a2,Микроигольчатый РФ лифтинг. Лицо+Шея. Ищу моделей,42,>50
8,Только dense,volkswagen polo,2835,20277fdaf89ff58f,"Volkswagen Polo 2015 Аренда авто с выкупом, лизинг",>50,14
9,Только dense,аварийное вскрытие замков двери 24/7,3190,d86a5c4ef8197e64,Аварийное вскрытие замков двери 24/7,>50,20

Dense получил **Recall@50 = 1,8395%**, BM25 — **1,9168%**.
Разница −0,0773 п.п.; 95% интервал [−0,1695; +0,0148] п.п. включает ноль.
Оснований заменять BM25 этим dense baseline нет.

Dense нашёл 632 позитивные пары вне top-50 BM25, но потерял 701 найденную BM25.
Оба метода нашли 954 пары. Знаменатель — 87 187 пар, включая недоступные в корпусе.
Дополняемость даёт основание проверить гибрид; сама по себе она не доказывает его пользу.

Для «iphone ломбард покупка» dense нашёл объявление «Выкуп iPhone/MacBook/Samsung»
на 39-м месте, BM25 — вне top-50. Для «mercari выкуп» BM25 нашёл позитив первым,
dense — вне top-50. Причины различий нельзя установить только по этим примерам.

На CUDA кодирование 189 212 объявлений заняло 148.58 с, 14 781 текста запроса — 1.49 с,
exact search — 0.35 с. Embeddings корпуса занимают 277,17 МиБ; это не полная память модели.
Время измерено для пакетной обработки и не является latency отдельного запроса.
Время CPU baseline и CUDA dense не сравнивает алгоритмы при равных ресурсах.

## 13. E4 — RRF

Гипотеза: объединение BM25 и dense улучшит состав top-50 за счёт разных находок.
Три заранее заданных варианта: `(N=100, c=60)`, `(N=200, c=60)`, `(N=200, c=20)`.
Каждый канал вносит `1 / (c + rank)`, ранг начинается с 1; отсутствующий ID даёт ноль.
Веса каналов одинаковы, равенства разрешаем по item_id. Оценки BM25 и cosine не складываем.

Полнота union до 2N кандидатов — диагностика, а не Recall@50.
Дополнительно считаем oracle@50: сколько позитивов можно было бы оставить из пула,
если бы их релевантность была известна. Для выбора используем только реальные top-50 RRF.

Для трёх сравнений с E0 — парный кластерный bootstrap, 2000 повторов,
98,33% интервалы (Бонферрони). Из вариантов с положительной нижней границей
выбираем наибольший Recall@50; при равенстве — меньшую глубину, затем c=60.
Если подтверждённого улучшения нет, сохраняем BM25. Выбор на том же validation
не даёт независимой оценки качества выбранного метода.

In [32]:
def rrf(rankings, c=60, k=50):
    if c < 0 or k < 0:
        raise ValueError("c и k должны быть неотрицательными")
    scores = {}
    for ranking in rankings:
        for rank, item_id in enumerate(dict.fromkeys(ranking), start=1):
            scores[item_id] = scores.get(item_id, 0.0) + 1.0 / (c + rank)
    return sorted(scores, key=lambda item_id: (-scores[item_id], item_id))[:k]


assert rrf([["b", "a"], ["a", "b"]]) == ["a", "b"]
assert rrf([["a", "b"], ["b", "c"]], c=0) == ["b", "a", "c"]
assert rrf([["a", "a", "b"], []]) == ["a", "b"]
assert rrf([[], []]) == [] and rrf([["a"]], k=0) == []
assert rrf([[], ["b", "a"]]) == ["b", "a"]
assert rrf([["a", "b", "c"], ["c", "b", "a"]], c=0, k=2) == ["a", "c"]
# Проверяем формулу независимой таблицей рангов, включая общие ID и один канал.
rrf_test_rankings = [["d", "a", "b"], ["b", "a", "c"]]
rrf_test_ids = sorted(set().union(*map(set, rrf_test_rankings)))
rrf_reference = {item_id: sum(1 / (60 + ranking.index(item_id) + 1)
                 for ranking in rrf_test_rankings if item_id in ranking) for item_id in rrf_test_ids}
assert rrf(rrf_test_rankings) == sorted(rrf_test_ids, key=lambda x: (-rrf_reference[x], x))
print("RRF: ранги, пропуски, дубли и равенства — OK")

RRF: ранги, пропуски, дубли и равенства — OK

In [33]:
max_depth = max(config["depth"] for config in RRF_VARIANTS.values())
start = perf_counter()
lexical_pool = {text: item_ids[top_k(bm25_scores(retriever, tokens), max_depth)].tolist()
                for text, tokens in zip(val_texts, tokenize(val_texts))}
e4_lexical_seconds = perf_counter() - start
start = perf_counter()
dense_pool_positions, e4_dense_ties = dense_top_k(
    query_embeddings, corpus_embeddings, k=max_depth, batch_size=DENSE_CONFIG["search_batch_size"])
synchronize_device(DEVICE)
dense_pool = {text: item_ids[pos].tolist() for text, pos in zip(val_texts, dense_pool_positions)}
e4_dense_seconds = perf_counter() - start
assert all(lexical_pool[t][:50] == predictions[t] for t in val_texts)
assert all(dense_pool[t][:50] == dense_predictions[t] for t in val_texts)
assert all(len(ids) == len(set(ids)) and set(ids) <= corpus_ids for channel in [lexical_pool, dense_pool] for ids in channel.values())
print(f"Top-{max_depth}: BM25 {e4_lexical_seconds:.2f} с; dense exact {e4_dense_seconds:.2f} с")

Top-200: BM25 4.13 с; dense exact 0.53 с

In [34]:
e4_rows, e4_predictions, e4_per_query, e4_pool_tables = [], {}, {}, {}
for name, config in RRF_VARIANTS.items():
    depth = config["depth"]
    start = perf_counter()
    candidate_predictions = {text: rrf([lexical_pool[text][:depth], dense_pool[text][:depth]], c=config["c"])
                             for text in val_texts}
    fusion_seconds = perf_counter() - start
    assert all(len(ids) == 50 and len(set(ids)) == 50 and set(ids) <= corpus_ids for ids in candidate_predictions.values())
    candidate_per_query = evaluate(validation, candidate_predictions)
    candidate_metrics = candidate_per_query.mean()
    ci = cluster_delta_interval(per_query["Recall@50"], candidate_per_query["Recall@50"],
                                validation.search_query, confidence=E4_CONFIDENCE)
    if depth not in e4_pool_tables:
        pools = {text: set(lexical_pool[text][:depth]) | set(dense_pool[text][:depth]) for text in val_texts}
        pool_rows = []
        for query in validation.itertuples():
            pool = pools[query.search_query]
            found = len(query.positives & pool)
            pool_rows.append({
                "union_recall": found / query.n_positives,
                "oracle_Recall@50": min(found, 50) / query.n_positives,
                "available_union_recall": found / query.n_available if query.n_available else np.nan,
                "pool_size": len(pool), "found_pairs": found,
            })
        e4_pool_tables[depth] = pd.DataFrame(pool_rows, index=validation.index)
    pool_table = e4_pool_tables[depth]
    assert np.all(candidate_per_query["Recall@50"] <= pool_table["oracle_Recall@50"] + 1e-12)
    found_top50 = sum(len(q.positives & set(candidate_predictions[q.search_query])) for q in validation.itertuples())
    row = {
        **experiment, "experiment": name, "device": f"cpu+{DEVICE}",
        "config": json.dumps({**config, "channels": ["E0", "E3"], "weights": [1, 1],
                              "tie_break": "item_id ascending", "dense": DENSE_CONFIG}, sort_keys=True),
        **{key: float(value) for key, value in candidate_metrics.items()},
        "delta_Recall@50": candidate_metrics["Recall@50"] - metrics["Recall@50"],
        "delta_ci_low": ci[0], "delta_ci_high": ci[1],
        "bootstrap_confidence": E4_CONFIDENCE, "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
        "index_seconds": experiment["index_seconds"] + dense_index_seconds,
        "index_MiB": experiment["index_MiB"] + corpus_embeddings.nbytes / 2**20,
        "search_seconds": e4_lexical_seconds + dense_query_encode_seconds + e4_dense_seconds + fusion_seconds,
        "fusion_seconds": fusion_seconds, "retrieval_depth_measured": max_depth,
        "pool_recall": pool_table.union_recall.mean(), "pool_oracle_Recall@50": pool_table["oracle_Recall@50"].mean(),
        "available_pool_recall": pool_table.available_union_recall.mean(),
        "mean_pool_size": pool_table.pool_size.mean(), "pool_found_pairs": pool_table.found_pairs.sum(),
        "lost_pairs_at_50": pool_table.found_pairs.sum() - found_top50,
        "conclusion": f"Recall@50={candidate_metrics['Recall@50']:.4%}; RRF N={depth}, c={config['c']}",
    }
    e4_rows.append(row)
    e4_predictions[name], e4_per_query[name] = candidate_predictions, candidate_per_query

experiments = pd.concat([experiments.loc[~experiments.experiment.isin(RRF_VARIANTS)], pd.DataFrame(e4_rows)], ignore_index=True)
assert experiments.experiment.is_unique
experiments.to_csv(EXPERIMENTS_PATH, index=False)
e4_results = pd.DataFrame(e4_rows).set_index("experiment")
display(e4_results[["Recall@50", "available_Recall@50", "delta_Recall@50", "delta_ci_low", "delta_ci_high"]].round(6))
display(e4_results[["pool_recall", "pool_oracle_Recall@50", "available_pool_recall", "mean_pool_size", "pool_found_pairs", "lost_pairs_at_50"]].round(6))

,Recall@50,available_Recall@50,delta_Recall@50,delta_ci_low,delta_ci_high
experiment,,,,,
E4_n100_c60,0.021258,0.331318,0.002091,0.001313,0.002922
E4_n200_c60,0.021566,0.336015,0.002399,0.001580,0.003237
E4_n200_c20,0.021485,0.333207,0.002317,0.001562,0.003110

,pool_recall,pool_oracle_Recall@50,available_pool_recall,mean_pool_size,pool_found_pairs,lost_pairs_at_50
experiment,,,,,,
E4_n100_c60,0.034032,0.034032,0.542786,168.653588,3045,1216
E4_n200_c60,0.041887,0.041887,0.675014,327.869277,3823,1967
E4_n200_c20,0.041887,0.041887,0.675014,327.869277,3823,1989

Каналы один раз извлекают top-200; варианты N=100 используют его префикс.
В журнале время поиска включает общий retrieval до 200 и отдельное время fusion.
Это измерение данного прогона, а не оптимизированного отдельного сервиса N=100.
Память индекса включает массивы BM25 и embeddings, но не веса encoder и рабочую память.

## 14. Выбор и разбор результата

Сравниваем все выполненные методы по одной метрике и одному split.
Удаление dense из гибрида даёт E0, удаление BM25 — E3; это проверка вклада двух каналов.

In [35]:
eligible = [name for name in RRF_VARIANTS if e4_results.loc[name, "delta_ci_low"] > 0]
FINAL_METHOD = (sorted(eligible, key=lambda name: (-e4_results.loc[name, "Recall@50"],
                RRF_VARIANTS[name]["depth"], -RRF_VARIANTS[name]["c"]))[0] if eligible else "E0")
final_validation_predictions = predictions if FINAL_METHOD == "E0" else e4_predictions[FINAL_METHOD]
final_per_query = per_query if FINAL_METHOD == "E0" else e4_per_query[FINAL_METHOD]
# Лучший RRF показываем и при выборе E0, чтобы не скрывать неудачный эксперимент.
best_rrf = e4_results["Recall@50"].idxmax()
display(experiments[["experiment", "Recall@1", "Recall@5", "Recall@10", "Recall@20", "Recall@50",
                     "available_Recall@50", "index_seconds", "search_seconds"]].round(6))
print(f"Выбран: {FINAL_METHOD}; Recall@50={final_per_query['Recall@50'].mean():.4%}")
display(experiments.set_index("experiment").loc[["E0", "E3", best_rrf], ["Recall@50", "available_Recall@50"]])

example_table = pd.DataFrame(dense_examples)
example_table["Ранг RRF top-50"] = [
    e4_predictions[best_rrf][row.Запрос].index(row.item_id) + 1
    if row.item_id in e4_predictions[best_rrf][row.Запрос] else ">50"
    for row in example_table.itertuples()]
display(example_table)

# Длина измерена в словах; частота — число уникальных train-групп с данным текстом.
# Из-за split по текстам validation-тексты не встречаются в train: такой срез тривиален.
slice_table = validation[["search_query"]].copy()
slice_table["Слов в запросе"] = pd.cut(slice_table.search_query.str.split().str.len(),
                                       bins=[-1, 1, 3, np.inf], labels=["0–1", "2–3", "4+"])
slice_table["BM25"] = per_query["Recall@50"]
slice_table["Dense"] = dense_per_query["Recall@50"]
slice_table["Выбранный метод"] = final_per_query["Recall@50"]
display(slice_table.groupby("Слов в запросе", observed=True).agg(
    Групп=("BM25", "size"), Текстов=("search_query", "nunique"),
    BM25=("BM25", "mean"), Dense=("Dense", "mean"), Итог=("Выбранный метод", "mean")))

,experiment,Recall@1,Recall@5,Recall@10,Recall@20,Recall@50,available_Recall@50,index_seconds,search_seconds
0,E0,0.001626,0.005165,0.008089,0.012069,0.019168,0.297620,21.406764,3.486597
1,E1_title,0.001385,0.004453,0.006679,0.009545,0.014627,0.233371,1.503129,2.268647
2,E1_description,0.001275,0.004290,0.007144,0.010456,0.016294,0.253143,21.668928,3.944716
3,E1_title1_description1,0.001782,0.005579,0.008227,0.012068,0.018960,0.298519,23.172057,4.760637
4,E1_title2_description1,0.001769,0.005324,0.008113,0.011961,0.018315,0.290581,23.172057,4.761252
5,E1_title4_description1,0.001545,0.005050,0.007639,0.011418,0.017560,0.278194,23.172057,4.765682
6,E2_word,0.000755,0.002981,0.005523,0.009084,0.015504,0.239996,45.299374,1.780601
7,E2_char,0.000714,0.002582,0.004389,0.007419,0.013516,0.204643,131.221634,12.343916
8,E3,0.001363,0.004886,0.007467,0.011443,0.018395,0.287525,148.580158,1.841308
9,E4_n100_c60,0.001863,0.005888,0.008939,0.013393,0.021258,0.331318,169.986922,6.615476
10,E4_n200_c60,0.001863,0.005941,0.008887,0.013505,0.021566,0.336015,169.986922,7.083052
11,E4_n200_c20,0.001877,0.005955,0.008774,0.013207,0.021485,0.333207,169.986922,7.049692

Выбран: E4_n200_c60; Recall@50=2.1566%

             Recall@50  available_Recall@50
experiment
E0            0.019168             0.297620
E3            0.018395             0.287525
E4_n200_c60   0.021566             0.336015

,Случай,Запрос,group_id,item_id,Заголовок,Ранг BM25,Ранг dense,Ранг RRF top-50
0,Только BM25,3d печать,424,c9a823ae64fbd1eb,Профессиональная 3D печать,25,>50,45
1,Только dense,3d печать,412,6cb949d70341a638,3D печать,>50,16,29
2,Только BM25,777,888,d1f9f13c96294d41,Домашний интернет и тв в частный дом,6,>50,12
3,Только dense,ip видеонаблюдение,1466,960ee99868b1118f,Монтаж и обслуживание видеонаблюдения,>50,39,>50
4,Только dense,iphone ломбард покупка,1481,cbe5f414681fd4da,Выкуп iPhone/MacBook/Samsung,>50,39,33
5,Только BM25,mercari выкуп,2071,fab5bf956436a174,Байер Япония (Mercari/Yahoo/Rakuten и тд),1,>50,4
6,Только BM25,sla печать,2512,b765441de5364699,"Художественная SLA печать,покрас 3D моделей",31,>50,40
7,Только BM25,smas лифтинг,2527,6fce025768d766a2,Микроигольчатый РФ лифтинг. Лицо+Шея. Ищу моделей,42,>50,>50
8,Только dense,volkswagen polo,2835,20277fdaf89ff58f,"Volkswagen Polo 2015 Аренда авто с выкупом, лизинг",>50,14,31
9,Только dense,аварийное вскрытие замков двери 24/7,3190,d86a5c4ef8197e64,Аварийное вскрытие замков двери 24/7,>50,20,>50

                Групп  Текстов      BM25     Dense      Итог
Слов в запросе
0–1              7052      675  0.011741  0.009628  0.013311
2–3             50406     9360  0.018915  0.018625  0.021381
4+              10923     4746  0.025129  0.022991  0.027752

Выбран **E4_n200_c60**: Recall@50 **2.1566%**, по доступным позитивам **33.60%**. Разница с BM25 — **+0.2399 п.п.**, 98,33% интервал [+0.1580; +0.3237] п.п.

Полнота объединённого пула — 4.1887%; после сокращения до 50 теряются 1967 найденных в пуле позитивных пар. Полнота пула не является итоговым качеством выдачи.

Оценка условна на доступный корпус и данный split: позитивы вне корпуса остаются
в знаменателе, разметка не описывает все релевантные объявления. Контекстные признаки
не используются. Конфигурация выбрана на этом validation, поэтому результат не является
независимой оценкой после выбора. Для итоговых запросов качество без разметки неизвестно.

### Близкие копии

Проверяем воспроизводимую выборку 500 различных нормализованных текстов корпуса (seed 42).
Для каждого ищем до 10 ближайших других текстов по character TF-IDF, исключив точные копии
до поиска. Cosine ≥ 0,95 считаем признаком близкого текста. Порог задан для аудита,
не для изменения выдачи. Это оценка выборки и примеры, а не полный поиск всех копий корпуса.
ID сохраняем: похожие объявления могут соответствовать разным услугам или исполнителям.

In [36]:
unique_text_positions = np.flatnonzero(~corpus_text.duplicated().to_numpy())
near_sample = np.sort(np.random.default_rng(SEED).choice(unique_text_positions,
                        size=min(NEAR_COPY_SAMPLE, len(unique_text_positions)), replace=False))
char_vectorizer, char_documents_t = tfidf_models["E2_char"]
near_queries = char_vectorizer.transform(corpus_text.iloc[near_sample]).tocsr()
unique_char_t = char_documents_t[:, unique_text_positions].tocsr()
near_positions, _ = sparse_top_k(near_queries, unique_char_t, k=11)
near_pairs, near_found = [], 0
for row, (source_pos, candidates) in enumerate(zip(near_sample, near_positions)):
    others = [int(unique_text_positions[pos]) for pos in candidates if unique_text_positions[pos] != source_pos][:10]
    similarities = (near_queries.getrow(row) @ char_documents_t[:, others]).toarray().ravel() if others else []
    close = [(pos, float(score)) for pos, score in zip(others, similarities) if score >= NEAR_COPY_THRESHOLD]
    near_found += bool(close)
    if close and len(near_pairs) < 5:
        target_pos, score = close[0]
        near_pairs.append({"item_id": item_ids[source_pos], "Похожий item_id": item_ids[target_pos],
                           "Cosine": score, "Заголовок": items.iloc[source_pos].item_title_raw,
                           "Похожий заголовок": items.iloc[target_pos].item_title_raw,
                           "Фрагмент": corpus_text.iloc[source_pos][:250],
                           "Похожий фрагмент": corpus_text.iloc[target_pos][:250]})
print(f"Близкий текст найден у {near_found}/{len(near_sample)} текстов выборки ({near_found / len(near_sample):.2%})")
display(pd.DataFrame(near_pairs))
del unique_char_t, near_queries
_ = gc.collect()

Близкий текст найден у 44/500 текстов выборки (8.80%)

,item_id,Похожий item_id,Cosine,Заголовок,Похожий заголовок,Фрагмент,Похожий фрагмент
0,05d367cef623cec9,b759d3f8d355f25e,0.991968,Гадание На картах таро,Гадание таро любовная магия,гадание на картах таро tapолoг ⚡️ гадaния нa таро ⚡️ oбучениe ⚡️ астролoгия ⚡️ энеpгетичecкaя пo...,гадание таро любовная магия tapолoг ⚡️ гадaния нa таро ⚡️ oбучениe ⚡️ астролoгия ⚡️ энеpгетичecк...
1,082687eb5c99c68b,739cd786a9368cb9,0.999138,Репетитор по информатике,Репетитор по информатике,репетитор по информатике 🎁 скидка 10% на первый месяц для новых учеников 🚀 открыта запись на онл...,репетитор по информатике 🎁 скидка 10% на первый месяц для новых учеников 🚀 открыта запись на онл...
2,1018fd04b3ee5138,63d243c56ae28d3f,0.993268,Такси межгород трансфер аэропорт аренда минивена,Такси межгород трансфер аэропорт ж.д + аренда авто,такси межгород трансфер аэропорт аренда минивена transfer-agency | такси межгород – пассажирские...,такси межгород трансфер аэропорт ж.д + аренда авто transfer-agency | такси межгород – пассажирск...
3,12baa4ff384d0dc7,69ea41d276ec523d,1.000000,Замена венцов Реконструкция домов,Замена венцов Реконструкция домов,"замена венцов реконструкция домов 🔨 надежный фундамент – долговечность вашего дома! заливка, рем...","замена венцов реконструкция домов 🔨 надежный фундамент – долговечность вашего дома! заливка, рем..."
4,19da8eb80d991e61,e55ef11f445f7eaf,0.996362,Уничтожение клопов тараканов клещей Дезинфекция,Уничтожение клопов тараканов клещей Дезинфекция,"уничтожение клопов тараканов клещей дезинфекция профессиональная дезинсекция, дезинфекция и дера...","уничтожение клопов тараканов клещей дезинфекция профессиональная дезинсекция, дезинфекция и дера..."

## 15. Замена bi-encoder: Harrier 270M

Сравниваем Harrier 270M без обучения. Корпус, split, исходные тексты,
длина 512 токенов и float32 те же. Отличаются модель, размерность и её штатная
инструкция запроса; pooling — last-token, документы без префикса.
Модель оцениваем отдельно и с BM25 через фиксированный RRF N=200, c=60.

Dense сравниваем с E3, гибрид — с E4_n200_c60. Сохраняем 97,5% интервалы
первоначального протокола: bootstrap по текстовым кластерам, 2000 повторов, seed 42.
Новый гибрид выбираем только при положительной нижней границе разницы с прежним E4.
Результат платформы не участвует в подборе. Параметры RRF не перенастраиваем.

In [ ]:
def load_harrier(config, device=DEVICE):
    model = SentenceTransformer(config["model"], revision=config["revision"],
        cache_folder=".cache/huggingface", local_files_only=True, trust_remote_code=False,
        device=str(device), model_kwargs={"dtype": torch.float32})
    model.float().eval()
    model.max_seq_length = config["max_length"]
    model.tokenizer.truncation_side = "right"
    assert model.get_embedding_dimension() == config["dimension"]
    assert model[1].pooling_mode == "lasttoken"
    assert model.prompts["web_search_query"] == config["query_prefix"]
    return model


harrier_rows, harrier_predictions, harrier_per_query = [], {}, {}
harrier_configs = {name: {**HARRIER_COMMON, **config} for name, config in HARRIER_MODELS.items()}
incumbent_name = "E4_n200_c60"
incumbent_per_query = e4_per_query[incumbent_name]
# Предыдущий encoder больше не нужен в GPU до выбора итогового метода.
encoder.to("cpu")
if DEVICE.type == "cuda":
    torch.cuda.empty_cache()

In [ ]:
for name, config in harrier_configs.items():
    folder = Path(".cache") / name.lower()
    reuse_embeddings = os.environ.get("AVITO_REUSE_H270", "0") == "1"
    if reuse_embeddings:
        metadata = json.loads((folder / "metadata.json").read_text())
        timing = json.loads((folder / "timing.json").read_text())
        assert metadata["config"] == timing["config"] == config
        assert metadata["split_sha256"] == SPLIT_HASH
        assert metadata["corpus_sha256"] == experiment["corpus_sha256"]
        assert metadata["train_sha256"] == experiment["train_sha256"]
        assert metadata["device"] == str(DEVICE)
        assert metadata["versions"] == dense_metadata["versions"]
        assert timing["metadata_sha256"] == sha256(folder / "metadata.json")
        for filename, digest in metadata["files"].items():
            assert sha256(folder / filename) == digest
        np.testing.assert_array_equal(pd.read_csv(folder / "items.csv", dtype={"item_id": str}).item_id, item_ids)
        assert (folder / "queries.csv").read_bytes() == Path(".cache/e3/queries.csv").read_bytes()
        h_documents = np.load(folder / "corpus.npy", allow_pickle=False)
        h_queries = np.load(folder / "queries.npy", allow_pickle=False)
        h_index_seconds = timing["index_seconds"]
        h_query_seconds = timing["query_encode_seconds"]
        load_seconds = timing["model_load_seconds"]
        print("Harrier: проверенный кэш; время кодирования сохранено из исходного прогона")
    else:
        start = perf_counter()
        harrier_encoder = load_harrier(config)
        load_seconds = perf_counter() - start
        start = perf_counter()
        h_documents = harrier_encoder.encode(dense_documents, prompt=config["document_prefix"],
            batch_size=config["batch_size"], normalize_embeddings=True, show_progress_bar=True)
        synchronize_device(DEVICE)
        h_index_seconds = perf_counter() - start
        start = perf_counter()
        h_queries = harrier_encoder.encode(dense_queries, prompt=config["query_prefix"],
            batch_size=config["batch_size"], normalize_embeddings=True, show_progress_bar=True)
        synchronize_device(DEVICE)
        h_query_seconds = perf_counter() - start
    for vectors, count in [(h_documents, len(item_ids)), (h_queries, len(val_texts))]:
        assert vectors.shape == (count, config["dimension"]) and vectors.dtype == np.float32
        assert np.isfinite(vectors).all()
        np.testing.assert_allclose(np.linalg.norm(vectors, axis=1), 1, atol=2e-5)
    # Полное произведение на том же устройстве проверяет поиск на новых embeddings.
    with torch.inference_mode():
        reference_scores = (torch.as_tensor(h_queries[:8], device=DEVICE)
                            @ torch.as_tensor(h_documents[:1000], device=DEVICE).T).cpu().numpy()
    found, _ = dense_top_k(h_queries[:8], h_documents[:1000], k=50)
    for actual, scores in zip(found, reference_scores):
        np.testing.assert_array_equal(actual, np.lexsort((np.arange(len(scores)), -scores))[:50])
    folder = Path(".cache") / name.lower()
    folder.mkdir(parents=True, exist_ok=True)
    np.save(folder / "corpus.npy", h_documents, allow_pickle=False)
    np.save(folder / "queries.npy", h_queries, allow_pickle=False)
    shutil.copyfile(Path(".cache/e3/items.csv"), folder / "items.csv")
    shutil.copyfile(Path(".cache/e3/queries.csv"), folder / "queries.csv")
    manifest = {"config": config, "device": str(DEVICE), "split_sha256": SPLIT_HASH,
                "corpus_sha256": experiment["corpus_sha256"], "train_sha256": experiment["train_sha256"],
                "versions": dense_metadata["versions"],
                "files": {file: sha256(folder / file) for file in ["corpus.npy", "queries.npy", "items.csv", "queries.csv"]}}
    (folder / "metadata.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2))
    timing = {"config": config, "index_seconds": h_index_seconds,
              "query_encode_seconds": h_query_seconds, "model_load_seconds": load_seconds,
              "metadata_sha256": sha256(folder / "metadata.json")}
    (folder / "timing.json").write_text(json.dumps(timing, ensure_ascii=False, indent=2))
    start = perf_counter()
    h_positions, h_pool_ties = dense_top_k(h_queries, h_documents, k=200, batch_size=config["search_batch_size"])
    synchronize_device(DEVICE)
    h_search_seconds = perf_counter() - start
    h_pool = {text: item_ids[positions].tolist() for text, positions in zip(val_texts, h_positions)}
    h_dense_predictions = {text: ids[:50] for text, ids in h_pool.items()}
    start = perf_counter()
    h_rrf_predictions = {text: rrf([lexical_pool[text][:200], h_pool[text]], c=60) for text in val_texts}
    h_fusion_seconds = perf_counter() - start
    for suffix, candidate_predictions, baseline, baseline_name in [
        ("dense", h_dense_predictions, dense_per_query, "E3"),
        ("rrf", h_rrf_predictions, incumbent_per_query, incumbent_name),
    ]:
        method = f"{name}_{suffix}"
        assert set(candidate_predictions) == set(val_texts)
        assert all(len(ids) == len(set(ids)) == 50 and set(ids) <= corpus_ids for ids in candidate_predictions.values())
        candidate_per_query = evaluate(validation, candidate_predictions)
        candidate_metrics = candidate_per_query.mean()
        assert candidate_per_query.index.equals(per_query.index)
        assert candidate_metrics["Recall@50"] <= ceiling + 1e-12
        ci = cluster_delta_interval(baseline["Recall@50"], candidate_per_query["Recall@50"], validation.search_query,
                                    confidence=HARRIER_CONFIDENCE)
        row = {**experiment, "experiment": method, "device": str(DEVICE),
               "config": json.dumps({"dense": config, "rrf": {"depth": 200, "c": 60} if suffix == "rrf" else None}, sort_keys=True),
               **{key: float(value) for key, value in candidate_metrics.items()},
               "bm25s_version": importlib.metadata.version("bm25s") if suffix == "rrf" else None,
               "token_pattern": TOKEN_PATTERN if suffix == "rrf" else None,
               "comparison_baseline": baseline_name,
               "delta_vs_baseline": candidate_metrics["Recall@50"] - baseline["Recall@50"].mean(),
               "delta_Recall@50": candidate_metrics["Recall@50"] - metrics["Recall@50"],
               "delta_ci_low": ci[0], "delta_ci_high": ci[1],
               "bootstrap_confidence": HARRIER_CONFIDENCE, "bootstrap_resamples": BOOTSTRAP_RESAMPLES,
               "index_seconds": h_index_seconds + (experiment["index_seconds"] if suffix == "rrf" else 0),
               "index_MiB": h_documents.nbytes / 2**20 + (experiment["index_MiB"] if suffix == "rrf" else 0),
               "query_encode_seconds": h_query_seconds, "exact_search_seconds": h_search_seconds,
               "search_seconds": h_query_seconds + h_search_seconds + (e4_lexical_seconds + h_fusion_seconds if suffix == "rrf" else 0),
               "fusion_seconds": h_fusion_seconds if suffix == "rrf" else 0,
               "model_load_seconds": load_seconds, "retrieval_depth_measured": 200,
               "pool_boundary_tie_queries": h_pool_ties, "embeddings_reused": reuse_embeddings,
               "sentence_transformers_version": importlib.metadata.version("sentence-transformers"),
               "transformers_version": importlib.metadata.version("transformers"),
               "conclusion": f"Recall@50={candidate_metrics['Recall@50']:.4%}; {method}"}
        harrier_rows.append(row)
        harrier_predictions[method], harrier_per_query[method] = candidate_predictions, candidate_per_query
        print(f"{method}: Recall@50={candidate_metrics['Recall@50']:.4%}; разница с {baseline_name}: {row['delta_vs_baseline']:+.6f}")
    # Освобождаем модель перед загрузкой следующей; embeddings сохранены с mapping.
    if not reuse_embeddings:
        del harrier_encoder
    del h_documents, h_queries
    gc.collect()
    if DEVICE.type == "cuda":
        torch.cuda.empty_cache()

harrier_results = pd.DataFrame(harrier_rows).set_index("experiment")
experiments = pd.concat([experiments.loc[~experiments.experiment.isin(harrier_results.index)], pd.DataFrame(harrier_rows)], ignore_index=True)
assert experiments.experiment.is_unique
experiments.to_csv(EXPERIMENTS_PATH, index=False)
display(harrier_results[["Recall@50", "available_Recall@50", "comparison_baseline", "delta_vs_baseline", "delta_ci_low", "delta_ci_high"]])
display(harrier_results[["index_seconds", "query_encode_seconds", "exact_search_seconds", "fusion_seconds", "index_MiB"]].round(3))

In [ ]:
eligible_harrier = [f"{name}_rrf" for name in HARRIER_MODELS if harrier_results.loc[f"{name}_rrf", "delta_ci_low"] > 0]
FINAL_METHOD = (sorted(eligible_harrier, key=lambda method: (-harrier_results.loc[method, "Recall@50"], method))[0]
                if eligible_harrier else incumbent_name)
final_validation_predictions = (harrier_predictions[FINAL_METHOD] if eligible_harrier else e4_predictions[FINAL_METHOD])
final_per_query = harrier_per_query[FINAL_METHOD] if eligible_harrier else e4_per_query[FINAL_METHOD]
print(f"Итоговый метод: {FINAL_METHOD}; Recall@50={final_per_query['Recall@50'].mean():.4%}")
display(experiments[["experiment", "Recall@50", "available_Recall@50"]])
if eligible_harrier:
    selected_name = FINAL_METHOD.split("_")[0]
    DENSE_CONFIG = harrier_configs[selected_name]
    DENSE_DIR = Path(".cache") / selected_name.lower()
    selected_metadata = json.loads((DENSE_DIR / "metadata.json").read_text())
    assert selected_metadata["config"] == DENSE_CONFIG and selected_metadata["split_sha256"] == SPLIT_HASH
    for filename, digest in selected_metadata["files"].items():
        assert sha256(DENSE_DIR / filename) == digest
    np.testing.assert_array_equal(pd.read_csv(DENSE_DIR / "items.csv", dtype={"item_id": str}).item_id, item_ids)
    corpus_embeddings = np.load(DENSE_DIR / "corpus.npy")
    del encoder
    encoder = load_harrier(DENSE_CONFIG)
else:
    encoder.to(DEVICE)
FINAL_RRF_CONFIG = {"depth": 200, "c": 60}

## 16. География и известные позитивы из train

У 84% доступных позитивных пар из train совпадают локации поиска и объявления. Для каждого запроса берём 40 кандидатов из локального BM25 + E3 через RRF и дополняем глобальной выдачей E4 до 50. Если объявлений в локации нет, остаётся глобальная выдача. Долю локального пула проверяем на прежнем validation без использования его разметки при поиске.

После выбора метода для итоговых запросов добавляем позитивы из полного разрешённого train по нормализованному тексту и категории: сначала с той же локацией поиска, затем остальные. Это правило не использует `query_id` и не применяется к validation. На платформе получен Recall@50 = 0.736026; локальная validation измеряет другой срез данных.

In [ ]:
item_location_positions = {
    int(location): positions.to_numpy()
    for location, positions in items.groupby("item_location_id").groups.items()
}
document_vectors = torch.as_tensor(corpus_embeddings, device=DEVICE)


@torch.inference_mode()
def geo_candidates(text, location_id, query_vector, global_candidates):
    positions = item_location_positions.get(int(location_id))
    if positions is None or not len(positions):
        return global_candidates[:50]
    tokens = tokenize([text])[0]
    scores = bm25_scores(retriever, tokens) if tokens else np.zeros(len(item_ids), dtype=np.float32)
    lexical = positions[top_k(scores[positions], 200)]
    local_vectors = document_vectors[torch.as_tensor(positions, device=DEVICE)]
    similarities = (local_vectors @ torch.as_tensor(query_vector, device=DEVICE)).float().cpu().numpy()
    dense = positions[np.lexsort((positions, -similarities))[:200]]
    local = rrf([item_ids[lexical].tolist(), item_ids[dense].tolist()], c=60, k=40)
    return list(dict.fromkeys(local + global_candidates))[:50]


location_by_group = train.drop_duplicates("group_id").set_index("group_id")["search_location_id"]
val_available = validation.loc[validation.n_available.gt(0)].copy()
val_available["search_location_id"] = location_by_group.loc[val_available.index]
contexts = val_available[["search_query", "search_location_id"]].drop_duplicates()
val_vector_by_text = dict(zip(val_texts, query_embeddings))
geo_validation = {
    (row.search_query, int(row.search_location_id)): geo_candidates(
        row.search_query, row.search_location_id,
        val_vector_by_text[row.search_query], e4_predictions["E4_n200_c60"][row.search_query]
    )
    for row in contexts.itertuples(index=False)
}
geo_recall = e4_per_query["E4_n200_c60"]["Recall@50"].copy()
for row in val_available.itertuples():
    candidates = geo_validation[(row.search_query, int(row.search_location_id))]
    geo_recall.loc[row.Index] = len(row.positives.intersection(candidates)) / row.n_positives
print(f"E4 Recall@50: {e4_per_query['E4_n200_c60']['Recall@50'].mean():.6f}")
print(f"E4 + география Recall@50: {geo_recall.mean():.6f}")

In [37]:
def validate_answer(frame, expected_query_ids, valid_item_ids):
    if frame.columns.tolist() != ["query_id", "answer"]:
        raise ValueError("Нужны ровно query_id,answer")
    if frame.isna().any().any() or not frame.query_id.is_unique:
        raise ValueError("Пропуски или повтор query_id")
    if not frame.query_id.map(lambda x: isinstance(x, str) and len(x) == 16).all():
        raise ValueError("query_id должен быть строкой длины 16")
    if len(frame) != len(expected_query_ids) or set(frame.query_id) != set(expected_query_ids):
        raise ValueError("Набор query_id не совпадает с benchmark")
    import re
    for value in frame.answer:
        if not isinstance(value, str):
            raise ValueError("answer должен быть строкой")
        ids = value.split(" ") if value else []
        if len(ids) > 50 or len(ids) != len(set(ids)):
            raise ValueError("Больше 50 кандидатов или дубли")
        if any(not re.fullmatch(r"[0-9a-f]{16}", x) or x not in valid_item_ids for x in ids):
            raise ValueError("Некорректный item_id или разделитель")


toy_qid, toy_id = "AbC0123456789xyz", "0000000000000001"
toy_answer = pd.DataFrame({"query_id": [toy_qid], "answer": [toy_id]})
validate_answer(toy_answer, [toy_qid], {toy_id})
validate_answer(toy_answer.assign(answer=""), [toy_qid], {toy_id})
for bad in [toy_id + " " + toy_id, " " + toy_id, toy_id + ",", "[" + toy_id + "]", "ffffffffffffffff"]:
    try:
        validate_answer(toy_answer.assign(answer=bad), [toy_qid], {toy_id})
    except ValueError:
        pass
    else:
        raise AssertionError("Некорректный answer не отклонён")
print("Формат ответа: проверки пройдены")

Формат ответа: проверки пройдены

In [ ]:
benchmark = pd.read_parquet(DATA_DIR / "benchmark_queries.parquet").sort_values("query_id").reset_index(drop=True)
benchmark["normalized"] = normalize_text(benchmark.search_query)
benchmark_texts = sorted(benchmark.normalized.unique())
start = perf_counter()
benchmark_lexical = {
    text: item_ids[top_k(bm25_scores(retriever, tokens), 200)].tolist()
    for text, tokens in zip(benchmark_texts, tokenize(benchmark_texts))
}
raw_map = benchmark.sort_values("search_query").drop_duplicates("normalized").set_index("normalized").search_query
benchmark_embeddings = encoder.encode(
    raw_map.loc[benchmark_texts].fillna("").tolist(), prompt=DENSE_CONFIG["query_prefix"],
    batch_size=DENSE_CONFIG["batch_size"], normalize_embeddings=True, show_progress_bar=True,
)
benchmark_dense_positions, _ = dense_top_k(
    benchmark_embeddings, corpus_embeddings, k=200, batch_size=DENSE_CONFIG["search_batch_size"]
)
global_predictions = {
    text: rrf([benchmark_lexical[text], item_ids[pos].tolist()], c=60)
    for text, pos in zip(benchmark_texts, benchmark_dense_positions)
}
benchmark_vector_by_text = dict(zip(benchmark_texts, benchmark_embeddings))
known = train.loc[train.item_id.isin(corpus_ids)]
known_by_query = known.groupby(["search_query", "search_category"], sort=False).item_id.agg(
    lambda values: list(dict.fromkeys(values))
).to_dict()
known_by_location = known.groupby(
    ["search_query", "search_category", "search_location_id"], sort=False
).item_id.agg(lambda values: list(dict.fromkeys(values))).to_dict()
item_location_by_id = items.set_index("item_id").item_location_id.to_dict()

predictions = []
for row in benchmark.itertuples(index=False):
    candidates = geo_candidates(
        row.normalized, row.search_location_id, benchmark_vector_by_text[row.normalized],
        global_predictions[row.normalized]
    )
    exact = known_by_location.get((row.normalized, row.search_category, row.search_location_id), [])
    related = known_by_query.get((row.normalized, row.search_category), [])
    related = sorted(related, key=lambda item_id: (
        item_location_by_id[item_id] != row.search_location_id, -int(item_id in candidates)
    ))
    predictions.append(list(dict.fromkeys(exact + related + candidates))[:50])

answer = pd.DataFrame({
    "query_id": benchmark.query_id,
    "answer": [" ".join(candidates) for candidates in predictions],
})
validate_answer(answer, benchmark.query_id.tolist(), corpus_ids)
answer.to_csv("answer.csv", index=False, encoding="utf-8")
restored_answer = pd.read_csv("answer.csv", dtype=str, keep_default_na=False)
validate_answer(restored_answer, benchmark.query_id.tolist(), corpus_ids)
pd.testing.assert_frame_equal(restored_answer, answer)

FINAL_DIR = Path(".cache/final")
FINAL_DIR.mkdir(parents=True, exist_ok=True)
shutil.copyfile("answer.csv", FINAL_DIR / "answer.csv")
final_manifest = {
    "method": "E4_geo_train", "geo_slots": 40, "global_slots": 10,
    "known_positives": "same normalized text and category; same location first",
    "bm25": BM25_CONFIG, "dense": DENSE_CONFIG,
    "split_sha256": SPLIT_HASH, "corpus_sha256": experiment["corpus_sha256"],
    "train_sha256": experiment["train_sha256"],
    "benchmark_sha256": sha256(DATA_DIR / "benchmark_queries.parquet"),
    "answer_sha256": sha256(Path("answer.csv")), "rows": len(answer),
    "device": str(DEVICE), "seed": SEED,
    "search_seconds": perf_counter() - start,
}
(FINAL_DIR / "manifest.json").write_text(json.dumps(final_manifest, ensure_ascii=False, indent=2))
print(f"answer.csv: {len(answer):,} строк; SHA-256: {final_manifest['answer_sha256']}")
print(f"Локальная validation Recall@50: {geo_recall.mean():.6f}")